Repository dbt-labs/metricflow, pull requests merged in 2023-05, with the labels that each got.

#459 Matching dbt-core Github Issues
  .changes/unreleased/Under the Hood-20230427-092509.yaml
  .github/ACTIONS_README.md
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature-request.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/regression-report.yml
  .github/pull_request_template.md
Labels: cla:yes

#486 Move *References objects to dbt-semantic-interfaces
  .changes/unreleased/Under the Hood-20230501-191406.yaml
  dbt_semantic_interfaces/dbt_semantic_interfaces/objects/data_source.py
  dbt_semantic_interfaces/dbt_semantic_interfaces/objects/elements/dimension.py
  dbt_semantic_interfaces/dbt_semantic_interfaces/objects/elements/identifier.py
  dbt_semantic_interfaces/dbt_semantic_interfaces/objects/elements/measure.py
  dbt_semantic_interfaces/dbt_semantic_interfaces/objects/metric.py
  dbt_semantic_interfaces/dbt_semantic_interfaces/references.py
  dbt_semantic_interfaces/dbt_semantic_interfaces/transformations/agg_time_dimension.py
  metricflow/dataflow/builder/dataflow_plan_builder.py
  metricflow/dataflow/dataflow_plan.py
  metricflow/dataset/convert_data_source.py
  metricflow/dataset/data_source_adapter.py
  metricflow/dataset/dataset.py
  metricflow/engine/metricflow_engine.py
  metricflow/instances.py
  metricflow/model/data_warehouse_model_validator.py
  metricflow/model/object_to_reference.py
  metricflow/model/semantics/data_source_join_evaluator.py
  metricflow/model/semantics/data_source_semantics.py
  metricflow/model/semantics/linkable_spec_resolver.py
  metricflow/model/semantics/metric_semantics.py
  metricflow/model/validations/agg_time_dimension.py
  metricflow/model/validations/common_identifiers.py
  metricflow/model/validations/data_sources.py
  metricflow/model/validations/dimension_const.py
  metricflow/model/validations/element_const.py
  metricflow/model/validations/identifiers.py
  metricflow/model/validations/measures.py
  metricflow/model/validations/metrics.py
  metricflow/model/validations/reserved_keywords.py
  metricflow/model/validations/unique_valid_name.py
  metricflow/model/validations/validator_helpers.py
  metricflow/plan_conversion/dataflow_to_sql.py
  metricflow/plan_conversion/instance_converters.py
  metricflow/plan_conversion/node_processor.py
  metricflow/plan_conversion/sql_dataset.py
  metricflow/protocols/semantics.py
  metricflow/query/query_parser.py
  metricflow/references.py
  metricflow/specs.py
  metricflow/test/dataflow/builder/test_node_data_set.py
  metricflow/test/dataset/test_convert_data_source.py
  metricflow/test/examples/test_node_sql.py
  metricflow/test/model/semantics/test_data_source_join_evaluator.py
  metricflow/test/model/semantics/test_linkable_spec_resolver.py
  metricflow/test/model/test_data_source_container.py
  metricflow/test/model/validations/test_dimension_const.py
  metricflow/test/model/validations/test_metrics.py
  metricflow/test/model/validations/test_validator_helpers.py
  metricflow/test/plan_conversion/dataflow_to_sql/test_metric_time_dimension_to_sql.py
  metricflow/test/plan_conversion/test_dataflow_to_sql_plan.py
  metricflow/test/time/test_time_granularity_solver.py
  metricflow/time/time_granularity_solver.py
Labels: cla:yes

#487 Move TimeGranularity to dbt_semantic_interfaces
  dbt_semantic_interfaces/dbt_semantic_interfaces/objects/elements/dimension.py
  dbt_semantic_interfaces/dbt_semantic_interfaces/objects/metric.py
  dbt_semantic_interfaces/dbt_semantic_interfaces/objects/time_granularity.py
  metricflow/constraints/time_constraint.py
  metricflow/dataflow/builder/dataflow_plan_builder.py
  metricflow/dataflow/dataflow_plan.py
  metricflow/dataset/convert_data_source.py
  metricflow/dataset/dataset.py
  metricflow/model/dbt_mapping_rules/dbt_metric_to_dimensions_rules.py
  metricflow/model/semantics/linkable_spec_resolver.py
  metricflow/model/transformations/dbt_to_metricflow.py
  metricflow/model/validations/dimension_const.py
  metricflow/model/validations/unique_valid_name.py
  metricflow/naming/linkable_spec_name.py
  metricflow/plan_conversion/column_resolver.py
  metricflow/plan_conversion/instance_converters.py
  metricflow/plan_conversion/time_spine.py
  metricflow/query/query_parser.py
  metricflow/specs.py
  metricflow/sql/render/big_query.py
  metricflow/sql/render/duckdb_renderer.py
  metricflow/sql/render/expr_renderer.py
  metricflow/sql/render/postgres.py
  metricflow/sql/sql_exprs.py
  metricflow/test/dataflow/builder/test_dataflow_plan_builder.py
  metricflow/test/dataflow/builder/test_node_data_set.py
  metricflow/test/dataflow/builder/test_node_evaluator.py
  metricflow/test/dataflow/optimizer/source_scan/test_source_scan_optimizer.py
  metricflow/test/dataset/test_convert_data_source.py
  metricflow/test/examples/test_node_sql.py
  metricflow/test/fixtures/table_fixtures.py
  metricflow/test/integration/test_configured_cases.py
  metricflow/test/model/parsing/test_data_source_parsing.py
  metricflow/test/model/parsing/test_metric_parsing.py
  metricflow/test/model/validations/test_data_sources.py
  metricflow/test/model/validations/test_dimension_const.py
  metricflow/test/model/validations/test_identifiers.py
  metricflow/test/model/validations/test_metrics.py
  metricflow/test/plan_conversion/instance_converters/test_create_validity_window_join_description.py
  metricflow/test/plan_conversion/test_dataflow_to_sql_plan.py
  metricflow/test/query/test_query_parser.py
  metricflow/test/sql/test_sql_expr_render.py
  metricflow/test/test_specs.py
  metricflow/test/time/metric_time_dimension.py
  metricflow/test/time/test_time_granularity_solver.py
  metricflow/time/time_constants.py
  metricflow/time/time_granularity.py
  metricflow/time/time_granularity_solver.py
Labels: cla:yes, Skip Changelog

#492 Remove use of `SqlTable` in `reserved_keywords.py` validation rule
  metricflow/model/validations/reserved_keywords.py
Labels: cla:yes, Skip Changelog

#489 Move enum_extensions to dbt_semantic_interfaces
  dbt_semantic_interfaces/dbt_semantic_interfaces/enum_extension.py
  dbt_semantic_interfaces/dbt_semantic_interfaces/objects/data_source.py
  dbt_semantic_interfaces/dbt_semantic_interfaces/objects/elements/dimension.py
  dbt_semantic_interfaces/dbt_semantic_interfaces/objects/elements/identifier.py
  dbt_semantic_interfaces/dbt_semantic_interfaces/objects/metric.py
  dbt_semantic_interfaces/dbt_semantic_interfaces/objects/time_granularity.py
  metricflow/aggregation_properties.py
  metricflow/model/objects/materialization.py
  metricflow/model/validations/unique_valid_name.py
  metricflow/model/validations/validator_helpers.py
  metricflow/plan_conversion/dataflow_to_sql.py
  metricflow/sql/render/databricks.py
  metricflow/sql/render/duckdb_renderer.py
  metricflow/sql/render/postgres.py
  metricflow/sql/render/redshift.py
  metricflow/sql/render/snowflake.py
  metricflow/sql/sql_exprs.py
  metricflow/sql_clients/common_client.py
  metricflow/test/integration/test_configured_cases.py
  metricflow/test/model/semantics/test_data_source_join_evaluator.py
  metricflow/test/sql_clients/test_async.py
  metricflow/test/sql_clients/test_sql_client.py
  metricflow/test/table_snapshot/table_snapshots.py
  metricflow/time/time_granularity.py
Labels: cla:yes, Skip Changelog

#495 Removing DimensionTypeParams time_format
  .changes/unreleased/Breaking Changes-20230503-110825.yaml
  dbt_semantic_interfaces/dbt_semantic_interfaces/objects/elements/dimension.py
  dbt_semantic_interfaces/dbt_semantic_interfaces/parsing/schemas.py
  dbt_semantic_interfaces/dbt_semantic_interfaces/parsing/schemas/metricflow.json
  metricflow/test/model/parsing/test_data_source_parsing.py
Labels: cla:yes

#496 Remove `SUPPORTED_GRANULARITIES` check from `DataSourceTimeDimensionWarningsRule`
  metricflow/model/validations/data_sources.py
Labels: cla:yes, Skip Changelog

#497 Move dataclass_serialization.py to dbt_semantic_interfaces
  dbt_semantic_interfaces/dbt_semantic_interfaces/dataclass_serialization.py
  dbt_semantic_interfaces/dbt_semantic_interfaces/references.py
  metricflow/column_assoc.py
  metricflow/constraints/time_constraint.py
  metricflow/instances.py
  metricflow/specs.py
  metricflow/sql/sql_bind_parameters.py
  metricflow/test/sql/test_bind_parameter_serialization.py
  metricflow/test/test_dataclass_serialization.py
  metricflow/test/test_instance_serialization.py
Labels: cla:yes, Skip Changelog

#484 Simplify test model templates
  metricflow/test/fixtures/model_fixtures.py
  metricflow/test/fixtures/model_yamls/composite_identifier_model/messages_source.yaml
  metricflow/test/fixtures/model_yamls/composite_identifier_model/more_users_source.yaml
  metricflow/test/fixtures/model_yamls/composite_identifier_model/users_source.yaml
  metricflow/test/fixtures/model_yamls/extended_date_model/data_sources/bookings_from_sql_query_source.yaml
  metricflow/test/fixtures/model_yamls/extended_date_model/data_sources/bookings_monthly_source.yaml
  metricflow/test/fixtures/model_yamls/extended_date_model/data_sources/extended_bookings_source.yaml
  metricflow/test/fixtures/model_yamls/extended_date_model/data_sources/listings_extended_source.yaml
  metricflow/test/fixtures/model_yamls/join_types_model/bookings_source.yaml
  metricflow/test/fixtures/model_yamls/join_types_model/listings_source.yaml
  metricflow/test/fixtures/model_yamls/multi_hop_join_model/partitioned_data_sources/account_month_txns.yaml
  metricflow/test/fixtures/model_yamls/multi_hop_join_model/partitioned_data_sources/bridge_table.yaml
  metricflow/test/fixtures/model_yamls/multi_hop_join_model/partitioned_data_sources/customer_other_data.yaml
  metricflow/test/fixtures/model_yamls/multi_hop_join_model/partitioned_data_sources/customer_table.yaml
  metricflow/test/fixtures/model_yamls/multi_hop_join_model/partitioned_data_sources/third_hop_table.yaml
  metricflow/test/fixtures/model_yamls/multi_hop_join_model/unpartitioned_data_sources/account_month_txns.yaml
  metricflow/test/fixtures/model_yamls/multi_hop_join_model/unpartitioned_data_sources/bridge_table.yaml
  metricflow/test/fixtures/model_yamls/multi_hop_join_model/unpartitioned_data_sources/customer_other_data.yaml
  metricflow/test/fixtures/model_yamls/multi_hop_join_model/unpartitioned_data_sources/customer_table.yaml
  metricflow/test/fixtures/model_yamls/multi_hop_join_model/unpartitioned_data_sources/third_hop_table.yaml
  metricflow/test/fixtures/model_yamls/non_ds_model/bookings_source.yaml
  metricflow/test/fixtures/model_yamls/non_ds_model/listings_latest.yaml
  metricflow/test/fixtures/model_yamls/scd_model/scd_accounts.yaml
  metricflow/test/fixtures/model_yamls/scd_model/scd_bookings.yaml
  metricflow/test/fixtures/model_yamls/scd_model/scd_companies.yaml
  metricflow/test/fixtures/model_yamls/scd_model/scd_listings.yaml
  metricflow/test/fixtures/model_yamls/scd_model/scd_lux_listings.yaml
  metricflow/test/fixtures/model_yamls/scd_model/scd_users.yaml
  metricflow/test/fixtures/model_yamls/simple_model/data_sources/accounts_source.yaml
  metricflow/test/fixtures/model_yamls/simple_model/data_sources/bookings_source.yaml
  metricflow/test/fixtures/model_yamls/simple_model/data_sources/companies.yaml
  metricflow/test/fixtures/model_yamls/simple_model/data_sources/id_verifications.yaml
  metricflow/test/fixtures/model_yamls/simple_model/data_sources/listings_latest.yaml
  metricflow/test/fixtures/model_yamls/simple_model/data_sources/lux_listing_mapping.yaml
  metricflow/test/fixtures/model_yamls/simple_model/data_sources/revenue.yaml
  metricflow/test/fixtures/model_yamls/simple_model/data_sources/user_ds_source.yaml
  metricflow/test/fixtures/model_yamls/simple_model/data_sources/users_latest.yaml
  metricflow/test/fixtures/model_yamls/simple_model/data_sources/views_source.yaml
Labels: cla:yes, Skip Changelog

#500 Disable using --use-persistent-schema in CI tests
  .github/workflows/cd-sql-engine-tests.yaml
  .github/workflows/ci-metricflow-unit-tests.yaml
Labels: cla:yes, Skip Changelog

#502 Making AggregationType use ExtendedEnum again
  dbt_semantic_interfaces/dbt_semantic_interfaces/objects/aggregation_type.py
Labels: cla:yes, Skip Changelog

#501 Move pretty_print and pformat_big_objects to dbt_semantic_interfaces
  dbt_semantic_interfaces/dbt_semantic_interfaces/dataclass_serialization.py
  dbt_semantic_interfaces/dbt_semantic_interfaces/pretty_print.py
  metricflow/dag/dag_to_text.py
  metricflow/dataflow/builder/dataflow_plan_builder.py
  metricflow/dataflow/builder/node_evaluator.py
  metricflow/dataflow/dataflow_plan.py
  metricflow/engine/metricflow_engine.py
  metricflow/model/semantics/data_source_join_evaluator.py
  metricflow/model/semantics/linkable_spec_resolver.py
  metricflow/plan_conversion/node_processor.py
  metricflow/query/query_parser.py
  metricflow/specs.py
  metricflow/sql_clients/async_request.py
  metricflow/sql_clients/base_sql_client_implementation.py
  metricflow/telemetry/handlers/python_log.py
  metricflow/test/examples/test_node_sql.py
  metricflow/test/fixtures/table_fixtures.py
  metricflow/test/table_snapshot/table_snapshots.py
  metricflow/test/test_object_utils.py
Labels: cla:yes, Skip Changelog

#503 Refactor objects/common.py to only hold subobjects of `UserConfiguredModel`
  dbt_semantic_interfaces/dbt_semantic_interfaces/objects/data_source.py
  dbt_semantic_interfaces/dbt_semantic_interfaces/objects/elements/dimension.py
  dbt_semantic_interfaces/dbt_semantic_interfaces/objects/elements/entity.py
  dbt_semantic_interfaces/dbt_semantic_interfaces/objects/elements/measure.py
  dbt_semantic_interfaces/dbt_semantic_interfaces/objects/metadata.py
  dbt_semantic_interfaces/dbt_semantic_interfaces/objects/metric.py
  dbt_semantic_interfaces/dbt_semantic_interfaces/parsing/dir_to_model.py
  dbt_semantic_interfaces/dbt_semantic_interfaces/parsing/objects.py
  metricflow/model/objects/materialization.py
  metricflow/model/validations/validator_helpers.py
  metricflow/test/fixtures/model_fixtures.py
  metricflow/test/model/parsing/test_data_source_parsing.py
  metricflow/test/model/parsing/test_metadata_parsing.py
  metricflow/test/model/parsing/test_metric_parsing.py
  metricflow/test/model/validations/helpers.py
  metricflow/test/model/validations/test_entities.py
  metricflow/test/model/validations/test_measures.py
  metricflow/test/model/validations/test_validity_param_definitions.py
  metricflow/test/query/test_query_parser.py
  metricflow/test/query/test_query_parser_suggestions.py
Labels: cla:yes, Skip Changelog

#509 Rename SemanticModel -> SemanticManifestLookup
  metricflow/api/metricflow_client.py
  metricflow/cli/cli_context.py
  metricflow/dataflow/builder/dataflow_plan_builder.py
  metricflow/dataflow/builder/node_data_set.py
  metricflow/dataflow/builder/source_node.py
  metricflow/engine/metricflow_engine.py
  metricflow/model/data_warehouse_model_validator.py
  metricflow/model/semantic_manifest_lookup.py
  metricflow/plan_conversion/column_resolver.py
  metricflow/plan_conversion/dataflow_to_sql.py
  metricflow/query/query_parser.py
  metricflow/test/api/conftest.py
  metricflow/test/dataflow/builder/test_node_data_set.py
  metricflow/test/dataflow/builder/test_node_evaluator.py
  metricflow/test/examples/test_node_sql.py
  metricflow/test/fixtures/cli_fixtures.py
  metricflow/test/fixtures/dataflow_fixtures.py
  metricflow/test/fixtures/model_fixtures.py
  metricflow/test/integration/conftest.py
  metricflow/test/integration/test_configured_cases.py
  metricflow/test/model/parsing/test_metadata_parsing.py
  metricflow/test/model/semantics/test_data_source_join_evaluator.py
  metricflow/test/model/semantics/test_linkable_spec_resolver.py
  metricflow/test/plan_conversion/conftest.py
  metricflow/test/plan_conversion/instance_converters/test_create_select_columns_with_measures_aggregated.py
  metricflow/test/plan_conversion/instance_converters/test_create_validity_window_join_description.py
  metricflow/test/plan_conversion/test_dataflow_to_execution.py
  metricflow/test/plan_conversion/test_dataflow_to_sql_plan.py
  metricflow/test/time/test_time_granularity_solver.py
  metricflow/time/time_granularity_solver.py
Labels: cla:yes, Skip Changelog

#519 Update pydantic validator for SemanticModel.relation_name
  dbt_semantic_interfaces/dbt_semantic_interfaces/objects/semantic_model.py
Labels: cla:yes, Skip Changelog

#524 update schema with constraint -> filter
  dbt_semantic_interfaces/dbt_semantic_interfaces/parsing/schemas/metricflow.json
Labels: cla:yes, Skip Changelog

#523 Rename UserConfiguredModel -> SemanticManifest
  dbt_semantic_interfaces/dbt_semantic_interfaces/model_transformer.py
  dbt_semantic_interfaces/dbt_semantic_interfaces/objects/semantic_manifest.py
  dbt_semantic_interfaces/dbt_semantic_interfaces/parsing/dir_to_model.py
  dbt_semantic_interfaces/dbt_semantic_interfaces/transformations/add_input_metric_measures.py
  dbt_semantic_interfaces/dbt_semantic_interfaces/transformations/agg_time_dimension.py
  dbt_semantic_interfaces/dbt_semantic_interfaces/transformations/boolean_measure.py
  dbt_semantic_interfaces/dbt_semantic_interfaces/transformations/convert_count.py
  dbt_semantic_interfaces/dbt_semantic_interfaces/transformations/convert_median.py
  dbt_semantic_interfaces/dbt_semantic_interfaces/transformations/names.py
  dbt_semantic_interfaces/dbt_semantic_interfaces/transformations/proxy_measure.py
  dbt_semantic_interfaces/dbt_semantic_interfaces/transformations/transform_rule.py
  metricflow/api/metricflow_client.py
  metricflow/cli/cli_context.py
  metricflow/cli/main.py
  metricflow/engine/metricflow_engine.py
  metricflow/engine/utils.py
  metricflow/model/data_warehouse_model_validator.py
  metricflow/model/dbt_converter.py
  metricflow/model/model_validator.py
  metricflow/model/parsing/dbt_cloud_to_model.py
  metricflow/model/parsing/dbt_dir_to_model.py
  metricflow/model/semantic_manifest_lookup.py
  metricflow/model/semantics/linkable_spec_resolver.py
  metricflow/model/semantics/metric_semantics.py
  metricflow/model/semantics/semantic_model_semantics.py
  metricflow/model/transformations/dbt_to_metricflow.py
  metricflow/model/validations/agg_time_dimension.py
  metricflow/model/validations/common_entities.py
  metricflow/model/validations/dimension_const.py
  metricflow/model/validations/element_const.py
  metricflow/model/validations/entities.py
  metricflow/model/validations/measures.py
  metricflow/model/validations/metrics.py
  metricflow/model/validations/non_empty.py
  metricflow/model/validations/reserved_keywords.py
  metricflow/model/validations/semantic_models.py
  metricflow/model/validations/unique_valid_name.py
  metricflow/model/validations/validator_helpers.py
  metricflow/test/api/conftest.py
  metricflow/test/fixtures/cli_fixtures.py
  metricflow/test/fixtures/model_fixtures.py
  metricflow/test/model/dbt_cloud_parsing/test_dbt_converter.py
  metricflow/test/model/parsing/test_metadata_parsing.py
  metricflow/test/model/parsing/test_model_deserialization.py
  metricflow/test/model/semantics/test_linkable_spec_resolver.py
  metricflow/test/model/test_semantic_model_container.py
  metricflow/test/model/transformations/test_configurable_transform_rules.py
  metricflow/test/model/validations/test_agg_time_dimension.py
  metricflow/test/model/validations/test_common_entities.py
  metricflow/test/model/validations/test_configurable_rules.py
  metricflow/test/model/validations/test_data_warehouse_tasks.py
  metricflow/test/model/validations/test_dimension_const.py
  metricflow/test/model/validations/test_element_const.py
  metricflow/test/model/validations/test_entities.py
  metricflow/test/model/validations/test_metrics.py
  metricflow/test/model/validations/test_reserved_keywords.py
  metricflow/test/model/validations/test_unique_valid_name.py
  metricflow/test/test_utils.py
  metricflow/test/time/test_time_granularity_solver.py
  metricflow/time/time_granularity_solver.py
Labels: cla:yes, Skip Changelog

#508 Remove Output Column Overrides
  metricflow/plan_conversion/dataflow_to_execution.py
  metricflow/query/query_parser.py
  metricflow/specs.py
  metricflow/test/query/test_query_parser.py
Labels: cla:yes, Skip Changelog

#515 Move model validator and rules to dbt_semantic_interfaces
  dbt_semantic_interfaces/dbt_semantic_interfaces/model_validator.py
  dbt_semantic_interfaces/dbt_semantic_interfaces/objects/where_filter/filter_renderer.py
  dbt_semantic_interfaces/dbt_semantic_interfaces/parsing/dir_to_model.py
  dbt_semantic_interfaces/dbt_semantic_interfaces/validations/__init__.py
  dbt_semantic_interfaces/dbt_semantic_interfaces/validations/agg_time_dimension.py
  dbt_semantic_interfaces/dbt_semantic_interfaces/validations/common_entities.py
  dbt_semantic_interfaces/dbt_semantic_interfaces/validations/dimension_const.py
  dbt_semantic_interfaces/dbt_semantic_interfaces/validations/element_const.py
  dbt_semantic_interfaces/dbt_semantic_interfaces/validations/entities.py
  dbt_semantic_interfaces/dbt_semantic_interfaces/validations/measures.py
  dbt_semantic_interfaces/dbt_semantic_interfaces/validations/metrics.py
  dbt_semantic_interfaces/dbt_semantic_interfaces/validations/non_empty.py
  dbt_semantic_interfaces/dbt_semantic_interfaces/validations/reserved_keywords.py
  dbt_semantic_interfaces/dbt_semantic_interfaces/validations/semantic_models.py
  dbt_semantic_interfaces/dbt_semantic_interfaces/validations/unique_valid_name.py
  dbt_semantic_interfaces/dbt_semantic_interfaces/validations/validator_helpers.py
  metricflow/api/metricflow_client.py
  metricflow/cli/main.py
  metricflow/dataset/dataset.py
  metricflow/model/data_warehouse_model_validator.py
  metricflow/model/dbt_converter.py
  metricflow/model/dbt_mapping_rules/dbt_mapping_rule.py
  metricflow/model/dbt_mapping_rules/dbt_metric_model_to_semantic_model_rules.py
  metricflow/model/dbt_mapping_rules/dbt_metric_to_dimensions_rules.py
  metricflow/model/dbt_mapping_rules/dbt_metric_to_measure.py
  metricflow/model/dbt_mapping_rules/dbt_metric_to_metrics_rules.py
  metricflow/model/transformations/dbt_to_metricflow.py
  metricflow/test/api/test_metricflow_client.py
  metricflow/test/cli/test_cli.py
  metricflow/test/fixtures/model_fixtures.py
  metricflow/test/model/parsing/test_metric_parsing.py
  metricflow/test/model/validations/test_agg_time_dimension.py
  metricflow/test/model/validations/test_common_entities.py
  metricflow/test/model/validations/test_configurable_rules.py
  metricflow/test/model/validations/test_dimension_const.py
  metricflow/test/model/validations/test_element_const.py
  metricflow/test/model/validations/test_entities.py
  metricflow/test/model/validations/test_measures.py
  metricflow/test/model/validations/test_metrics.py
  metricflow/test/model/validations/test_reserved_keywords.py
  metricflow/test/model/validations/test_semantic_models.py
  metricflow/test/model/validations/test_unique_valid_name.py
  metricflow/test/model/validations/test_validator_helpers.py
  metricflow/test/model/validations/test_validity_param_definitions.py
Labels: cla:yes, Skip Changelog

#526 Move tests relevant to dbt_semantic_interfaces to dbt_semantic_interfaces
  dbt_semantic_interfaces/dbt_semantic_interfaces/test/objects/constraints/__init__.py
  dbt_semantic_interfaces/dbt_semantic_interfaces/test_utils.py
  dbt_semantic_interfaces/tests/__init__.py
  dbt_semantic_interfaces/tests/conftest.py
  dbt_semantic_interfaces/tests/fixtures/__init__.py
  dbt_semantic_interfaces/tests/fixtures/model_fixtures.py
  dbt_semantic_interfaces/tests/fixtures/model_yamls/simple_model/metrics.yaml
  dbt_semantic_interfaces/tests/fixtures/model_yamls/simple_model/semantic_models/accounts_source.yaml
  dbt_semantic_interfaces/tests/fixtures/model_yamls/simple_model/semantic_models/bookings_source.yaml
  dbt_semantic_interfaces/tests/fixtures/model_yamls/simple_model/semantic_models/companies.yaml
  dbt_semantic_interfaces/tests/fixtures/model_yamls/simple_model/semantic_models/id_verifications.yaml
  dbt_semantic_interfaces/tests/fixtures/model_yamls/simple_model/semantic_models/listings_latest.yaml
  dbt_semantic_interfaces/tests/fixtures/model_yamls/simple_model/semantic_models/lux_listing_mapping.yaml
  dbt_semantic_interfaces/tests/fixtures/model_yamls/simple_model/semantic_models/revenue.yaml
  dbt_semantic_interfaces/tests/fixtures/model_yamls/simple_model/semantic_models/user_sm_source.yaml
  dbt_semantic_interfaces/tests/fixtures/model_yamls/simple_model/semantic_models/users_latest.yaml
  dbt_semantic_interfaces/tests/fixtures/model_yamls/simple_model/semantic_models/views_source.yaml
  dbt_semantic_interfaces/tests/parsing/__init__.py
  dbt_semantic_interfaces/tests/parsing/test_metadata_parsing.py
  dbt_semantic_interfaces/tests/parsing/test_metric_parsing.py
  dbt_semantic_interfaces/tests/parsing/test_model_deserialization.py
  dbt_semantic_interfaces/tests/parsing/test_semantic_model_parsing.py
  dbt_semantic_interfaces/tests/test_dataclass_serialization.py
  dbt_semantic_interfaces/tests/test_filter_renderer.py
  dbt_semantic_interfaces/tests/test_pretty_print.py
  dbt_semantic_interfaces/tests/transformations/__init__.py
  dbt_semantic_interfaces/tests/transformations/test_configurable_transform_rules.py
  dbt_semantic_interfaces/tests/validations/__init__.py
  dbt_semantic_interfaces/tests/validations/test_agg_time_dimension.py
  dbt_semantic_interfaces/tests/validations/test_common_entities.py
  dbt_semantic_interfaces/tests/validations/test_configurable_rules.py
  dbt_semantic_interfaces/tests/validations/test_dimension_const.py
  dbt_semantic_interfaces/tests/validations/test_element_const.py
  dbt_semantic_interfaces/tests/validations/test_entities.py
  dbt_semantic_interfaces/tests/validations/test_measures.py
  dbt_semantic_interfaces/tests/validations/test_metrics.py
  dbt_semantic_interfaces/tests/validations/test_reserved_keywords.py
  dbt_semantic_interfaces/tests/validations/test_semantic_models.py
  dbt_semantic_interfaces/tests/validations/test_unique_valid_name.py
  dbt_semantic_interfaces/tests/validations/test_validator_helpers.py
  dbt_semantic_interfaces/tests/validations/test_validity_param_definitions.py
  metricflow/test/fixtures/cli_fixtures.py
  metricflow/test/integration/conftest.py
  metricflow/test/integration/test_configured_cases.py
  metricflow/test/model/test_data_warehouse_tasks.py
  metricflow/test/plan_conversion/test_dataflow_to_sql_plan.py
  metricflow/test/query/test_query_parser.py
  metricflow/test/table_snapshot/test_table_snapshots.py
  metricflow/test/test_object_utils.py
  metricflow/test/test_utils.py
Labels: cla:yes, Skip Changelog

#517 Update the naming of SemanticManifestLookup objects
  metricflow/dataflow/builder/dataflow_plan_builder.py
  metricflow/dataflow/builder/node_evaluator.py
  metricflow/dataflow/builder/partitions.py
  metricflow/dataflow/builder/source_node.py
  metricflow/engine/metricflow_engine.py
  metricflow/model/data_warehouse_model_validator.py
  metricflow/model/semantic_manifest_lookup.py
  metricflow/model/semantics/linkable_spec_resolver.py
  metricflow/model/semantics/metric_lookup.py
  metricflow/model/semantics/semantic_model_join_evaluator.py
  metricflow/model/semantics/semantic_model_lookup.py
  metricflow/plan_conversion/dataflow_to_sql.py
  metricflow/plan_conversion/instance_converters.py
  metricflow/plan_conversion/node_processor.py
  metricflow/protocols/semantics.py
  metricflow/query/query_parser.py
  metricflow/test/dataflow/builder/test_node_evaluator.py
  metricflow/test/examples/test_node_sql.py
  metricflow/test/model/semantics/test_linkable_spec_resolver.py
  metricflow/test/model/semantics/test_semantic_model_join_evaluator.py
  metricflow/test/model/test_semantic_model_container.py
  metricflow/test/plan_conversion/instance_converters/test_create_select_columns_with_measures_aggregated.py
  metricflow/test/plan_conversion/instance_converters/test_create_validity_window_join_description.py
  metricflow/time/time_granularity_solver.py
Labels: cla:yes, Skip Changelog

#532 update used gh actions ahead of set-output, node12 deprecation
  .github/ACTIONS_README.md
  .github/workflows/bot-changelog.yml
Labels: cla:yes, Skip Changelog

#535 update used gh actions ahead of node12 deprecation
  .github/workflows/bot-changelog.yml
Labels: cla:yes, Skip Changelog

#539 Dedupe Items Returned By ValidLinkableSpecResolver.get_linkable_elements_for_metrics()
  metricflow/model/semantics/linkable_spec_resolver.py
  metricflow/test/model/test_semantic_model_container.py
Labels: cla:yes, Skip Changelog

#403 Stop updating enum values by reference in BigQuerySqlExpressionRenderer
  .changes/unreleased/Fixes-20230517-163839.yaml
  metricflow/sql/render/big_query.py
Labels: run_mf_sql_engine_tests, cla:yes

#438 Improve typechecking coverage
  .changes/unreleased/Under the Hood-20230517-164028.yaml
  .pre-commit-config.yaml
  metricflow/plan_conversion/instance_converters.py
  mypy.ini
Labels: cla:yes

#538 Move mypy to use the local environment for package dependencies
  .changes/unreleased/Under the Hood-20230518-115000.yaml
  .github/workflows/ci-linting.yaml
  .pre-commit-config.yaml
  metricflow/inference/renderer/config_file.py
  mypy.ini
  poetry.lock
  pyproject.toml
Labels: cla:yes

#541 Update dependency on dbt-semantic-interfaces to 0.1.0.dev1
  metricflow/dataflow/builder/dataflow_plan_builder.py
  metricflow/dataflow/dataflow_plan.py
  metricflow/dataset/convert_semantic_model.py
  metricflow/dataset/dataset.py
  metricflow/filters/time_constraint.py
  metricflow/model/dbt_mapping_rules/dbt_metric_to_dimensions_rules.py
  metricflow/model/semantics/linkable_spec_resolver.py
  metricflow/model/transformations/dbt_to_metricflow.py
  metricflow/naming/linkable_spec_name.py
  metricflow/plan_conversion/column_resolver.py
  metricflow/plan_conversion/instance_converters.py
  metricflow/plan_conversion/time_spine.py
  metricflow/query/query_parser.py
  metricflow/specs/specs.py
  metricflow/specs/where_filter_transform.py
  metricflow/sql/render/big_query.py
  metricflow/sql/render/duckdb_renderer.py
  metricflow/sql/render/expr_renderer.py
  metricflow/sql/render/postgres.py
  metricflow/sql/sql_exprs.py
  metricflow/test/dataflow/builder/test_dataflow_plan_builder.py
  metricflow/test/dataflow/builder/test_node_data_set.py
  metricflow/test/dataflow/builder/test_node_evaluator.py
  metricflow/test/dataflow/optimizer/source_scan/test_source_scan_optimizer.py
  metricflow/test/dataset/test_convert_semantic_model.py
  metricflow/test/examples/test_node_sql.py
  metricflow/test/integration/test_configured_cases.py
  metricflow/test/model/test_where_filter_spec.py
  metricflow/test/plan_conversion/instance_converters/test_create_validity_window_join_description.py
  metricflow/test/plan_conversion/test_dataflow_to_sql_plan.py
  metricflow/test/query/test_query_parser.py
  metricflow/test/sql/test_sql_expr_render.py
  metricflow/test/test_specs.py
  metricflow/test/time/metric_time_dimension.py
  metricflow/test/time/test_time_granularity_solver.py
  metricflow/time/time_constants.py
  metricflow/time/time_granularity.py
  metricflow/time/time_granularity_solver.py
  poetry.lock
  pyproject.toml
Labels: cla:yes, Skip Changelog

#542 MetricFlow 0.200.0.dev0
  pyproject.toml
Labels: cla:yes, Skip Changelog

#550 Fix type signatures for log_call decorator
  .changes/unreleased/Fixes-20230523-164125.yaml
  .pre-commit-config.yaml
  metricflow/telemetry/reporter.py
Labels: cla:yes

#533 Update MFEngine models to contain attributes from pydantic models
  .changes/unreleased/Under the Hood-20230523-180725.yaml
  metricflow/engine/metricflow_engine.py
  metricflow/engine/models.py
  metricflow/model/semantic_manifest_lookup.py
  metricflow/test/api/test_metricflow_client.py
Labels: cla:yes

#554 Update metadata for 0.200.0.dev1 release
  README.md
  pyproject.toml
Labels: cla:yes, Skip Changelog

#555 Fix broken publish action
  .github/workflows/cd-push-to-pypi.yaml
Labels: cla:yes, Skip Changelog

#545 Clean up MetricFlow dependencies
  .changes/unreleased/Dependencies-20230525-102100.yaml
  pyproject.toml
Labels: run_mf_sql_engine_tests, cla:yes

#556 Add qualified name to MFEngine Dimension
  .changes/unreleased/Under the Hood-20230525-183003.yaml
  metricflow/engine/metricflow_engine.py
  metricflow/engine/models.py
  pyproject.toml
Labels: cla:yes

#558 Roll pre-release version number back to 0.200.0.dev2 from 0.200.1.dev1
  pyproject.toml
Labels: cla:yes, Skip Changelog
