Repository dbt-labs/metricflow, pull requests merged in 2023-06, with the labels that each got.

#561 duplicate input_measures property to engine.model.Metric
  metricflow/engine/models.py
Labels: cla:yes, Skip Changelog

#570 Update version to 0.200.0.dev3 for latest dev release
  pyproject.toml
Labels: cla:yes, Skip Changelog

#568 Fix tutorial and added tests
  metricflow/cli/sample_models/countries.yaml
  metricflow/cli/sample_models/customers.yaml
  metricflow/cli/sample_models/transactions.yaml
  metricflow/test/cli/test_cli.py
Labels: cla:yes, Skip Changelog

#566 Get dimension values via SQL
  .changes/unreleased/Under the Hood-20230605-145703.yaml
  metricflow/dataflow/builder/dataflow_plan_builder.py
  metricflow/engine/metricflow_engine.py
Labels: cla:yes

#584 added explain dimension values method to protocol
  metricflow/engine/metricflow_engine.py
Labels: cla:yes, Skip Changelog

#586 Specific error for unsupported data platform feature
  .changes/unreleased/Under the Hood-20230608-135447.yaml
  metricflow/errors/errors.py
  metricflow/sql/render/big_query.py
  metricflow/sql/render/databricks.py
  metricflow/sql/render/postgres.py
  metricflow/sql/render/redshift.py
  metricflow/sql/render/snowflake.py
Labels: cla:yes

#588 Bump dev version
  pyproject.toml
Labels: cla:yes, Skip Changelog

#572 Merge AsyncSqlClient with SqlClient
  metricflow/api/metricflow_client.py
  metricflow/cli/cli_context.py
  metricflow/engine/metricflow_engine.py
  metricflow/execution/execution_plan.py
  metricflow/model/data_warehouse_model_validator.py
  metricflow/plan_conversion/dataflow_to_execution.py
  metricflow/protocols/async_sql_client.py
  metricflow/protocols/sql_client.py
  metricflow/sql_clients/base_sql_client_implementation.py
  metricflow/sql_clients/big_query.py
  metricflow/sql_clients/databricks.py
  metricflow/sql_clients/duckdb.py
  metricflow/sql_clients/postgres.py
  metricflow/sql_clients/redshift.py
  metricflow/sql_clients/snowflake.py
  metricflow/sql_clients/sql_statement_metadata.py
  metricflow/sql_clients/sql_utils.py
  metricflow/sql_clients/sqlalchemy_dialect.py
  metricflow/test/api/conftest.py
  metricflow/test/execution/test_tasks.py
  metricflow/test/fixtures/cli_fixtures.py
  metricflow/test/fixtures/sql_client_fixtures.py
  metricflow/test/integration/conftest.py
  metricflow/test/integration/test_configured_cases.py
  metricflow/test/model/test_data_warehouse_tasks.py
  metricflow/test/plan_conversion/test_dataflow_to_execution.py
  metricflow/test/sql_clients/test_async.py
Labels: cla:yes, Skip Changelog

#573 Add support for query tags and isolation in main query and execute methods
  metricflow/protocols/sql_client.py
  metricflow/sql_clients/base_sql_client_implementation.py
Labels: cla:yes, Skip Changelog

#589 Remove support for async queries from SqlClient
  .changes/unreleased/Breaking Changes-20230608-182212.yaml
  metricflow/cli/main.py
  metricflow/execution/execution_plan.py
  metricflow/protocols/sql_client.py
  metricflow/sql_clients/base_sql_client_implementation.py
  metricflow/sql_clients/big_query.py
  metricflow/sql_clients/databricks.py
  metricflow/sql_clients/duckdb.py
  metricflow/sql_clients/postgres.py
  metricflow/sql_clients/redshift.py
  metricflow/sql_clients/snowflake.py
  metricflow/sql_clients/sql_utils.py
  metricflow/sql_clients/sqlalchemy_dialect.py
  metricflow/test/sql_clients/test_async.py
  metricflow/test/sql_clients/test_sql_client.py
Labels: run_mf_sql_engine_tests, cla:yes

#600 Bump DSI and update MF
  metricflow/cli/sample_models/countries.yaml
  pyproject.toml
Labels: cla:yes, Skip Changelog

#601 Remove introspective queries and on the fly creation of time spine tables
  .changes/unreleased/Breaking Changes-20230613-115512.yaml
  metricflow/cli/tutorial.py
  metricflow/engine/metricflow_engine.py
  metricflow/plan_conversion/time_spine.py
  metricflow/test/cli/test_cli.py
  metricflow/test/fixtures/dataflow_fixtures.py
  metricflow/test/fixtures/table_fixtures.py
Labels: cla:yes

#602 Clean up legacy constructs in SqlClient interface
  .changes/unreleased/Under the Hood-20230613-114714.yaml
  metricflow/cli/cli_context.py
  metricflow/cli/tutorial.py
  metricflow/protocols/sql_client.py
  metricflow/sql_clients/base_sql_client_implementation.py
  metricflow/sql_clients/big_query.py
  metricflow/sql_clients/common_client.py
  metricflow/sql_clients/databricks.py
  metricflow/sql_clients/duckdb.py
  metricflow/sql_clients/postgres.py
  metricflow/sql_clients/redshift.py
  metricflow/sql_clients/snowflake.py
  metricflow/sql_clients/sql_utils.py
  metricflow/sql_clients/sqlalchemy_dialect.py
  metricflow/test/execution/test_tasks.py
  metricflow/test/fixtures/table_fixtures.py
  metricflow/test/integration/configured_test_case.py
  metricflow/test/integration/test_cases/itest_cumulative_metric.yaml
  metricflow/test/integration/test_cases/itest_granularity.yaml
  metricflow/test/integration/test_cases/itest_measure_constraints.yaml
  metricflow/test/integration/test_cases/itest_metrics.yaml
  metricflow/test/integration/test_cases/itest_order_limit.yaml
  metricflow/test/integration/test_cases/itest_simple.yaml
  metricflow/test/integration/test_configured_cases.py
  metricflow/test/plan_conversion/test_time_spine.py
  metricflow/test/sql_clients/test_sql_client.py
Labels: run_mf_sql_engine_tests, cla:yes

#604 Eliminate engine attribute structs from SqlClient protocol
  .changes/unreleased/Breaking Changes-20230614-173609.yaml
  metricflow/cli/cli_context.py
  metricflow/engine/metricflow_engine.py
  metricflow/model/data_warehouse_model_validator.py
  metricflow/plan_conversion/dataflow_to_execution.py
  metricflow/plan_conversion/dataflow_to_sql.py
  metricflow/protocols/sql_client.py
  metricflow/sql/render/big_query.py
  metricflow/sql/render/databricks.py
  metricflow/sql/render/duckdb_renderer.py
  metricflow/sql/render/expr_renderer.py
  metricflow/sql/render/postgres.py
  metricflow/sql/render/redshift.py
  metricflow/sql/render/snowflake.py
  metricflow/sql_clients/base_sql_client_implementation.py
  metricflow/sql_clients/big_query.py
  metricflow/sql_clients/databricks.py
  metricflow/sql_clients/duckdb.py
  metricflow/sql_clients/postgres.py
  metricflow/sql_clients/redshift.py
  metricflow/sql_clients/snowflake.py
  metricflow/test/examples/test_node_sql.py
  metricflow/test/integration/test_configured_cases.py
  metricflow/test/plan_conversion/test_dataflow_to_sql_plan.py
  metricflow/test/sql/compare_sql_plan.py
  metricflow/test/sql/test_engine_specific_rendering.py
Labels: run_mf_sql_engine_tests, cla:yes

#599 Remove dependency on PydanticSemanticManifest on validations
  metricflow/api/metricflow_client.py
  metricflow/cli/cli_context.py
  metricflow/cli/main.py
  metricflow/engine/metricflow_engine.py
  metricflow/engine/utils.py
  metricflow/model/data_warehouse_model_validator.py
  metricflow/model/semantic_manifest_lookup.py
  metricflow/model/semantics/semantic_model_lookup.py
  metricflow/protocols/semantics.py
  metricflow/test/cli/test_cli.py
  metricflow/test/fixtures/cli_fixtures.py
  metricflow/test/fixtures/model_fixtures.py
  metricflow/test/model/test_data_warehouse_tasks.py
  metricflow/test/model/test_semantic_model_container.py
Labels: cla:yes, Skip Changelog

#605 Build a semantic manifest from dbt project root directory
  .changes/unreleased/Breaking Changes-20230616-125446.yaml
  metricflow/cli/cli_context.py
  metricflow/cli/main.py
  metricflow/engine/metricflow_engine.py
  metricflow/engine/utils.py
  metricflow/errors/errors.py
  metricflow/test/cli/test_cli.py
Labels: cla:yes

#611 Fix Typo "resolves" -> "Resolves" in Github PR template
  .github/pull_request_template.md
Labels: cla:yes, Skip Changelog

#615 bump dbt-core to 1.6.0b5 and mf to 0.200.0.dev5
  pyproject.toml
Labels: cla:yes, Skip Changelog

#614 Use dbt postgres adapter wrapper for integration tests
  .changes/unreleased/Features-20230621-183113.yaml
  Makefile
  metricflow/cli/dbt_connectors/__init__.py
  metricflow/cli/dbt_connectors/adapter_backed_client.py
  metricflow/errors/errors.py
  metricflow/sql_clients/sql_utils.py
  metricflow/test/fixtures/dbt_projects/metricflow_testing/.gitignore
  metricflow/test/fixtures/dbt_projects/metricflow_testing/.user.yml
  metricflow/test/fixtures/dbt_projects/metricflow_testing/README.md
  metricflow/test/fixtures/dbt_projects/metricflow_testing/analyses/.gitkeep
  metricflow/test/fixtures/dbt_projects/metricflow_testing/dbt_project.yml
  metricflow/test/fixtures/dbt_projects/metricflow_testing/macros/.gitkeep
  metricflow/test/fixtures/dbt_projects/metricflow_testing/models/example/my_first_dbt_model.sql
  metricflow/test/fixtures/dbt_projects/metricflow_testing/models/example/my_second_dbt_model.sql
  metricflow/test/fixtures/dbt_projects/metricflow_testing/models/example/schema.yml
  metricflow/test/fixtures/dbt_projects/metricflow_testing/profiles.yml
  metricflow/test/fixtures/dbt_projects/metricflow_testing/seeds/.gitkeep
  metricflow/test/fixtures/dbt_projects/metricflow_testing/snapshots/.gitkeep
  metricflow/test/fixtures/dbt_projects/metricflow_testing/tests/.gitkeep
  metricflow/test/fixtures/setup_fixtures.py
  metricflow/test/fixtures/sql_client_fixtures.py
  metricflow/test/generate_snapshots.py
  metricflow/test/sql_clients/test_sql_client.py
  pyproject.toml
Labels: run_mf_sql_engine_tests, cla:yes

#621 Update MetricFlow to depend on dbt-core 1.6.0.b6
  pyproject.toml
Labels: cla:yes, Skip Changelog

#617 `explain_get_dimension_values` & `get_dimension_values` takes metrics lists
  .changes/unreleased/Breaking Changes-20230626-113920.yaml
  metricflow/api/metricflow_client.py
  metricflow/cli/main.py
  metricflow/engine/metricflow_engine.py
  metricflow/test/api/test_metricflow_client.py
  metricflow/test/cli/test_cli.py
Labels: cla:yes

#625 Bump to dev7
  pyproject.toml
Labels: cla:yes

#622 Apply semantic manifest transformations to json parsed output
  .changes/unreleased/Fixes-20230626-110103.yaml
  metricflow/engine/utils.py
  metricflow/test/cli/test_cli.py
Labels: cla:yes

#623 Enable dbt AdapterBackedSqlClient queries from the MetricFlow CLI
  .changes/unreleased/Features-20230626-133439.yaml
  metricflow/cli/cli_context.py
  metricflow/cli/dbt_connectors/dbt_config_accessor.py
  metricflow/cli/main.py
  metricflow/configuration/config_builder.py
  metricflow/engine/metricflow_engine.py
  metricflow/engine/utils.py
  metricflow/test/cli/test_cli.py
Labels: cla:yes

#626 bump to dev8
  pyproject.toml
Labels: cla:yes, Skip Changelog

#628 Use `--persistent-source-schema` in the Snapshot Generation Script
  metricflow/test/generate_snapshots.py
Labels: Skip Changelog

#629 Remove custom MetricFlow config and all references to it
  .changes/unreleased/Breaking Changes-20230627-173530.yaml
  metricflow/api/metricflow_client.py
  metricflow/cli/cli_context.py
  metricflow/cli/main.py
  metricflow/cli/tutorial.py
  metricflow/cli/utils.py
  metricflow/configuration/config_builder.py
  metricflow/configuration/config_handler.py
  metricflow/configuration/constants.py
  metricflow/configuration/yaml_handler.py
  metricflow/dag/dag_visualization.py
  metricflow/engine/metricflow_engine.py
  metricflow/engine/utils.py
  metricflow/sql_clients/sql_utils.py
  metricflow/telemetry/reporter.py
  metricflow/test/cli/test_cli.py
  metricflow/test/fixtures/cli_fixtures.py
Labels: run_mf_sql_engine_tests, cla:yes

#630 Switch postgres test configuration to source from engine URL
  metricflow/sql_clients/postgres.py
  metricflow/test/fixtures/dbt_projects/metricflow_testing/profiles.yml
  metricflow/test/fixtures/sql_client_fixtures.py
Labels: cla:yes, Skip Changelog

#633 Refactor Tutorial to work with dbt integration
  .changes/unreleased/Features-20230628-131531.yaml
  metricflow/cli/cli_context.py
  metricflow/cli/dbt_connectors/dbt_config_accessor.py
  metricflow/cli/main.py
  metricflow/cli/sample_dbt_models/sample_models/countries.sql
  metricflow/cli/sample_dbt_models/sample_models/countries.yml
  metricflow/cli/sample_dbt_models/sample_models/customers.sql
  metricflow/cli/sample_dbt_models/sample_models/customers.yml
  metricflow/cli/sample_dbt_models/sample_models/metrics.yml
  metricflow/cli/sample_dbt_models/sample_models/transactions.sql
  metricflow/cli/sample_dbt_models/sample_models/transactions.yml
  metricflow/cli/sample_dbt_models/seeds/.gitkeep
  metricflow/cli/sample_dbt_models/seeds/countries_seed.csv
  metricflow/cli/sample_dbt_models/seeds/customers_seed.csv
  metricflow/cli/sample_dbt_models/seeds/transactions_seed.csv
  metricflow/cli/sample_dbt_models/semantic_manifest.json
  metricflow/cli/sample_dbt_models/sources.yml
  metricflow/cli/tutorial.py
  metricflow/cli/utils.py
  metricflow/test/cli/test_cli.py
  metricflow/test/fixtures/cli_fixtures.py
Labels: cla:yes

#631 Move Snowflake queries onto the dbt AdapterBackedSqlClient
  .changes/unreleased/Features-20230627-234808.yaml
  .github/workflows/cd-sql-engine-tests.yaml
  Makefile
  metricflow/cli/dbt_connectors/adapter_backed_client.py
  metricflow/engine/metricflow_engine.py
  metricflow/sql_clients/snowflake.py
  metricflow/test/cli/test_cli.py
  metricflow/test/compare_df.py
  metricflow/test/execution/test_tasks.py
  metricflow/test/fixtures/dbt_projects/metricflow_testing/profiles.yml
  metricflow/test/fixtures/sql_client_fixtures.py
  metricflow/test/integration/test_write_to_table.py
  metricflow/test/sql_clients/test_sql_client.py
  metricflow/test/table_snapshot/test_source_schema.py
  metricflow/test/table_snapshot/test_table_snapshots.py
  pyproject.toml
Labels: run_mf_sql_engine_tests, cla:yes

#636 bump to 0.200.0.dev9
  pyproject.toml
Labels: cla:yes, Skip Changelog

#619 Create dbt-metricflow package
  .changes/unreleased/Features-20230628-165151.yaml
  dbt-metricflow/LICENSE
  dbt-metricflow/README.md
  dbt-metricflow/pyproject.toml
Labels: cla:yes

#638 Fix tutorial loading with dbt project
  metricflow/cli/cli_context.py
  metricflow/cli/dbt_connectors/dbt_config_accessor.py
  metricflow/cli/main.py
  metricflow/cli/utils.py
  metricflow/test/fixtures/cli_fixtures.py
Labels: cla:yes, Skip Changelog

#639 bump to 0.200.0.dev10
  pyproject.toml
Labels: cla:yes, Skip Changelog

#640 Bump dbt-metricflow to 0.0.2
  dbt-metricflow/pyproject.toml
Labels: cla:yes, Skip Changelog

#632 Fix snapshot generation for postgres
  Makefile
  metricflow/test/generate_snapshots.py
Labels: cla:yes, Skip Changelog

#641 changing metricflow docs link
  README.md
Labels: cla:yes, Skip Changelog

#642 change group-bys to group-by in the CLI
  .changes/unreleased/Breaking Changes-20230630-135934.yaml
  metricflow/cli/main.py
  metricflow/cli/utils.py
  metricflow/test/cli/test_cli.py
Labels: cla:yes
