Repository dbt-labs/metricflow, pull requests merged in 2023-10, with the labels that each got.

#796 Clean up SQL time interval math expressions
  metricflow/dag/id_generation.py
  metricflow/plan_conversion/sql_join_builder.py
  metricflow/sql/render/big_query.py
  metricflow/sql/render/duckdb_renderer.py
  metricflow/sql/render/expr_renderer.py
  metricflow/sql/render/postgres.py
  metricflow/sql/sql_exprs.py
  metricflow/test/integration/test_configured_cases.py
Labels: cla:yes, Skip Changelog

#785 Support for `Dimension(...).grain(...)` in where filter
  .changes/unreleased/Features-20231004-102255.yaml
  metricflow/specs/dimension_spec_resolver.py
  metricflow/specs/where_filter_dimension.py
  metricflow/specs/where_filter_time_dimension.py
  metricflow/specs/where_filter_transform.py
  metricflow/test/model/test_where_filter_spec.py
  metricflow/test/specs/test_where_filter_dimension.py
Labels: cla:yes

#798 Surface underlying error message in where parameter
  .changes/unreleased/Under the Hood-20231006-095540.yaml
  metricflow/query/query_parser.py
Labels: cla:yes

#799 Bump to 0.203.0.dev2
  pyproject.toml
Labels: cla:yes, Skip Changelog

#800 Remove query interface
  .changes/unreleased/Under the Hood-20231006-170905.yaml
  metricflow/protocols/query_interface.py
  metricflow/specs/where_filter_dimension.py
  metricflow/specs/where_filter_entity.py
  metricflow/specs/where_filter_time_dimension.py
Labels: cla:yes

#802 Case insensitivity for query params
  .changes/unreleased/Fixes-20231010-144137.yaml
  metricflow/query/query_parser.py
  metricflow/test/query/test_query_parser.py
Labels: cla:yes

#801 Bug fix: source node evaluation
  .changes/unreleased/Fixes-20231009-195312.yaml
  metricflow/dataflow/builder/dataflow_plan_builder.py
Labels: cla:yes

#805 Dev release
  pyproject.toml
Labels: cla:yes, Skip Changelog

#808 Bump dev version
  pyproject.toml
Labels: cla:yes, Skip Changelog

#811 Fix broken SQL engine tests
  .github/workflows/cd-sql-engine-populate-persistent-source-schema.yaml
  .github/workflows/cd-sql-engine-tests.yaml
  metricflow/test/snapshots/test_dataflow_to_sql_plan.py/SqlQueryPlan/Databricks/test_distinct_values__plan0.sql
  metricflow/test/snapshots/test_dataflow_to_sql_plan.py/SqlQueryPlan/Databricks/test_distinct_values__plan0_optimized.sql
  pyproject.toml
Labels: run_mf_sql_engine_tests, cla:yes, Skip Changelog

#813 Remove error for date part with non-metric time dimension
  metricflow/query/query_parser.py
  metricflow/test/integration/test_cases/itest_metrics.yaml
Labels: cla:yes, Skip Changelog

#814 Dev release
  pyproject.toml
Labels: cla:yes, Skip Changelog

#817 Re-categorize `TypeErrors` that arise from `create_from_where_filter` into `InvalidQueryException`
  .changes/unreleased/Under the Hood-20231017-155210.yaml
  metricflow/query/query_parser.py
  metricflow/specs/where_filter_transform.py
  metricflow/test/model/test_where_filter_spec.py
Labels: cla:yes

#821 Dev release
  pyproject.toml
Labels: cla:yes, Skip Changelog

#823 Update minimum typing-extensions version to 4.4
  .changes/unreleased/Dependencies-20231026-151457.yaml
  pyproject.toml
Labels: cla:yes

#824 Add missing snapshots for saved queries
  metricflow/test/generate_snapshots.py
  metricflow/test/snapshots/test_cli.py/str/BigQuery/test_saved_query__cli_output.txt
  metricflow/test/snapshots/test_cli.py/str/BigQuery/test_saved_query_with_limit__cli_output.txt
  metricflow/test/snapshots/test_cli.py/str/BigQuery/test_saved_query_with_where__cli_output.txt
  metricflow/test/snapshots/test_cli.py/str/Databricks/test_saved_query__cli_output.txt
  metricflow/test/snapshots/test_cli.py/str/Databricks/test_saved_query_with_limit__cli_output.txt
  metricflow/test/snapshots/test_cli.py/str/Databricks/test_saved_query_with_where__cli_output.txt
  metricflow/test/snapshots/test_cli.py/str/Redshift/test_saved_query__cli_output.txt
  metricflow/test/snapshots/test_cli.py/str/Redshift/test_saved_query_with_limit__cli_output.txt
  metricflow/test/snapshots/test_cli.py/str/Redshift/test_saved_query_with_where__cli_output.txt
  metricflow/test/snapshots/test_cli.py/str/Snowflake/test_saved_query__cli_output.txt
  metricflow/test/snapshots/test_cli.py/str/Snowflake/test_saved_query_with_limit__cli_output.txt
  metricflow/test/snapshots/test_cli.py/str/Snowflake/test_saved_query_with_where__cli_output.txt
Labels: run_mf_sql_engine_tests, cla:yes, Skip Changelog

#829 Remove unused costing code
  metricflow/dataflow/builder/costing.py
  metricflow/dataflow/builder/dataflow_plan_builder.py
  metricflow/test/dataflow/builder/test_costing.py
  metricflow/test/dataflow/builder/test_cyclic_join.py
  metricflow/test/fixtures/dataflow_fixtures.py
Labels: cla:yes, Skip Changelog

#827 Update sql-engine-test workflow to remove label on completion.
  .github/workflows/cd-sql-engine-tests.yaml
Labels: Skip Changelog

#831 Fix random failures with parallel CLI tests
  metricflow/test/cli/test_cli.py
  metricflow/test/fixtures/cli_fixtures.py
  metricflow/test/fixtures/setup_fixtures.py
  metricflow/test/fixtures/sql_client_fixtures.py
Labels: cla:yes, Skip Changelog
