Repository dbt-labs/metricflow, pull requests merged in 2023-07, with the labels that each got.

#644 Raise `UnknownMetricLinkingError` if a Metric isn't found during linking
  .changes/unreleased/Under the Hood-20230705-141555.yaml
  metricflow/errors/errors.py
  metricflow/model/semantics/linkable_spec_resolver.py
Labels: cla:yes

#645 Remove legacy tutorial helper functions
  metricflow/cli/sample_models/countries.yaml
  metricflow/cli/sample_models/customers.yaml
  metricflow/cli/sample_models/transactions.yaml
  metricflow/cli/tutorial.py
  metricflow/test/cli/test_cli.py
Labels: cla:yes, Skip Changelog

#647 Remove layer of indirection from CLI error messages
  .changes/unreleased/Fixes-20230705-182137.yaml
  metricflow/cli/cli_context.py
  metricflow/errors/errors.py
Labels: cla:yes

#648 Update databricks-sql-connector and click dependency
  pyproject.toml
Labels: run_mf_sql_engine_tests, cla:yes

#649 bump MetricFlow to 0.200.0.dev11
  pyproject.toml
Labels: cla:yes, Skip Changelog

#651 Add version and make compatible fix for dbt-core 1.6.0b8
  .changes/unreleased/Fixes-20230711-132046.yaml
  metricflow/cli/dbt_connectors/dbt_config_accessor.py
  metricflow/cli/main.py
  metricflow/model/dbt_manifest_parser.py
Labels: cla:yes

#652 bump to 0.200.0.dev12
  pyproject.toml
Labels: cla:yes, Skip Changelog

#661 bump dbt-metricflow with the rc version of dbt-core and dsi
  dbt-metricflow/pyproject.toml
Labels: cla:yes, Skip Changelog

#666 Update pyproject.toml for dbt-metricflow to support Python 3.10 and 3.11
  CONTRIBUTING.md
  dbt-metricflow/pyproject.toml
Labels: cla:yes, Skip Changelog

#667 URL for dbt-metricflow for PyPI
  dbt-metricflow/pyproject.toml
Labels: cla:yes, Skip Changelog

#669 Use a keyword that will link a pull request to an issue
  .github/pull_request_template.md
Labels: cla:yes, Skip Changelog

#670 bump dbt-metricflow to 0.0.4
  dbt-metricflow/pyproject.toml
Labels: cla:yes, Skip Changelog

#671 Separate engine-specific tests to dedicated hatch envs
  .changes/unreleased/Under the Hood-20230721-131915.yaml
  .github/workflows/cd-sql-engine-tests.yaml
  CONTRIBUTING.md
  Makefile
  metricflow/test/fixtures/sql_client_fixtures.py
  pyproject.toml
Labels: run_mf_sql_engine_tests, cla:yes

#672 Move SQLAlchemy/SQL engine dependencies to test envs
  .changes/unreleased/Dependencies-20230721-160539.yaml
  metricflow/cli/dbt_connectors/adapter_backed_client.py
  metricflow/execution/execution_plan.py
  metricflow/plan_conversion/dataflow_to_execution.py
  metricflow/protocols/sql_client.py
  metricflow/sql_request/__init__.py
  metricflow/sql_request/sql_request_attributes.py
  metricflow/sql_request/sql_statement_metadata.py
  metricflow/test/fixtures/setup_fixtures.py
  metricflow/test/fixtures/sql_client_fixtures.py
  metricflow/test/fixtures/sql_clients/__init__.py
  metricflow/test/fixtures/sql_clients/base_sql_client_implementation.py
  metricflow/test/fixtures/sql_clients/big_query.py
  metricflow/test/fixtures/sql_clients/common_client.py
  metricflow/test/fixtures/sql_clients/databricks.py
  metricflow/test/fixtures/sql_clients/duckdb.py
  metricflow/test/fixtures/sql_clients/redshift.py
  metricflow/test/fixtures/sql_clients/sqlalchemy_dialect.py
  pyproject.toml
Labels: run_mf_sql_engine_tests, cla:yes

#662 Clean up project metadata for contact and installation instructions
  README.md
  pyproject.toml
Labels: cla:yes, Skip Changelog

#674 Remove unused features in snapshot loader class
  metricflow/test/source_schema_tools.py
  metricflow/test/table_snapshot/table_snapshots.py
  metricflow/test/table_snapshot/test_table_snapshots.py
Labels: cla:yes, Skip Changelog

#675 Remove DDL and other test-only methods from SqlClient protocol
  .changes/unreleased/Under the Hood-20230724-152228.yaml
  metricflow/cli/dbt_connectors/adapter_backed_client.py
  metricflow/execution/execution_plan.py
  metricflow/protocols/sql_client.py
  metricflow/test/execution/test_tasks.py
  metricflow/test/fixtures/sql_client_fixtures.py
  metricflow/test/fixtures/sql_clients/adapter_backed_ddl_client.py
  metricflow/test/fixtures/sql_clients/base_sql_client_implementation.py
  metricflow/test/fixtures/sql_clients/big_query.py
  metricflow/test/fixtures/sql_clients/databricks.py
  metricflow/test/fixtures/sql_clients/ddl_sql_client.py
  metricflow/test/fixtures/sql_clients/duckdb.py
  metricflow/test/fixtures/sql_clients/sqlalchemy_dialect.py
  metricflow/test/fixtures/table_fixtures.py
  metricflow/test/integration/test_write_to_table.py
  metricflow/test/source_schema_tools.py
  metricflow/test/sql_clients/test_sql_client.py
  metricflow/test/table_snapshot/table_snapshots.py
  metricflow/test/table_snapshot/test_table_snapshots.py
Labels: run_mf_sql_engine_tests, cla:yes

#680 Update Snapshot Generation Script with the New Test Setup
  metricflow/test/generate_snapshots.py
Labels: cla:yes, Skip Changelog

#679 Move Logging Module to Avoid Conflicts
  metricflow/cli/dbt_connectors/adapter_backed_client.py
  metricflow/engine/metricflow_engine.py
  metricflow/formatting.py
  metricflow/logging/__init__.py
  metricflow/test/fixtures/sql_clients/base_sql_client_implementation.py
Labels: cla:yes, Skip Changelog

#678 Cut Redshift client over to dbt-redshift adapter
  .changes/unreleased/Features-20230726-084615.yaml
  metricflow/cli/dbt_connectors/adapter_backed_client.py
  metricflow/test/fixtures/dbt_projects/metricflow_testing/profiles.yml
  metricflow/test/fixtures/sql_client_fixtures.py
  metricflow/test/fixtures/sql_clients/redshift.py
  metricflow/test/integration/test_cases/itest_metrics.yaml
  pyproject.toml
Labels: run_mf_sql_engine_tests, cla:yes

#684 Improve CLI error message for generating semantic_manifest
  metricflow/cli/dbt_connectors/dbt_config_accessor.py
Labels: cla:yes, Skip Changelog

#682 Move Databricks query execution to AdapterBackedSqlClient
  .changes/unreleased/Features-20230726-173129.yaml
  metricflow/cli/dbt_connectors/adapter_backed_client.py
  metricflow/test/fixtures/dbt_projects/metricflow_testing/profiles.yml
  metricflow/test/fixtures/sql_client_fixtures.py
  metricflow/test/fixtures/sql_clients/adapter_backed_ddl_client.py
Labels: run_mf_sql_engine_tests, cla:yes

#686 Switch test profile env vars for dbt-backed tests to DBT_ENV_SECRET
  metricflow/test/fixtures/dbt_projects/metricflow_testing/profiles.yml
  metricflow/test/fixtures/sql_client_fixtures.py
Labels: cla:yes, Skip Changelog

#688 Clean up dry run method in AdapterBackedSqlClient
  metricflow/cli/dbt_connectors/adapter_backed_client.py
Labels: cla:yes, Skip Changelog

#689 Remove SQLAlchemy-backed databricks SqlClient
  metricflow/test/fixtures/sql_clients/databricks.py
  pyproject.toml
Labels: cla:yes, Skip Changelog

#690 Improve messaging for populating the persistent source schema
  metricflow/test/source_schema_tools.py
  metricflow/test/table_snapshot/test_source_schema.py
Labels: run_mf_sql_engine_tests, cla:yes, Skip Changelog

#691 Bump MetricFlow version for 0.200.dev14 release
  pyproject.toml
Labels: cla:yes, Skip Changelog

#696 Release MetricFlow 0.200.0.dev15
  pyproject.toml
Labels: cla:yes, Skip Changelog

#697 Bump dbt-metricflow version to 0.0.5 for local deployment
  dbt-metricflow/pyproject.toml
Labels: cla:yes, Skip Changelog
