Repository dbt-labs/metricflow, pull requests merged in 2023-08, with the labels that each got.

#698 Remove unused schema property from MetricFlow runtime
  metricflow/api/metricflow_client.py
  metricflow/cli/cli_context.py
  metricflow/cli/main.py
  metricflow/engine/metricflow_engine.py
  metricflow/model/data_warehouse_model_validator.py
  metricflow/test/api/conftest.py
  metricflow/test/api/test_metricflow_client.py
  metricflow/test/fixtures/cli_fixtures.py
  metricflow/test/integration/conftest.py
  metricflow/test/integration/test_configured_cases.py
  metricflow/test/model/test_data_warehouse_tasks.py
Labels: cla:yes, Skip Changelog

#700 Clean up output of various list dimensions commands
  .changes/unreleased/Fixes-20230802-162013.yaml
  metricflow/cli/main.py
  metricflow/engine/metricflow_engine.py
  metricflow/engine/models.py
  metricflow/test/cli/test_cli.py
Labels: run_mf_sql_engine_tests, cla:yes

#701 Update versions for 0.200.0.rc1
  pyproject.toml
Labels: cla:yes, Skip Changelog

#703 Update dependencies and attribution listing
  .changes/unreleased/Dependencies-20230802-191840.yaml
  attribution.md
  mypy.ini
  pyproject.toml
Labels: run_mf_sql_engine_tests, cla:yes

#704 Update README and other documentation files for 0.200.0
  CONTRIBUTING.md
  README.md
  config-templates/salesforce/README.md
  config-templates/salesforce/account.yaml
  config-templates/salesforce/leads.yaml
  config-templates/salesforce/opportunities.yaml
  config-templates/salesforce/users.yaml
  config-templates/shopify/customer.yaml
  config-templates/shopify/customer_address.yaml
  config-templates/shopify/inventory_item.yaml
  config-templates/shopify/inventory_level.yaml
  config-templates/shopify/order.yaml
  config-templates/shopify/order_line.yaml
  config-templates/shopify/product_variant.yaml
Labels: cla:yes, Skip Changelog

#705 Update deps for dbt-metricflow 0.1.0.rc1 release
  dbt-metricflow/pyproject.toml
Labels: cla:yes, Skip Changelog

#709 Update dbt-metricflow for release 0.1.0
  dbt-metricflow/pyproject.toml
Labels: cla:yes, Skip Changelog

#710 Add dbt-duckdb as a supported adapter and use it for local dev/test
  .changes/unreleased/Features-20230804-064652.yaml
  local-data-warehouses/README.md
  metricflow/cli/dbt_connectors/adapter_backed_client.py
  metricflow/test/fixtures/dbt_projects/metricflow_testing/profiles.yml
  metricflow/test/fixtures/sql_client_fixtures.py
  metricflow/test/fixtures/sql_clients/duckdb.py
  metricflow/test/sql_clients/test_sql_client.py
  pyproject.toml
Labels: cla:yes

#719 Update Pandas dependency to 1.5.x
  .changes/unreleased/Dependencies-20230810-112855.yaml
  pyproject.toml
Labels: cla:yes

#720 Loosen version pins for MetricFlow dependencies
  .changes/unreleased/Dependencies-20230810-112931.yaml
  metricflow/model/parsing/__init__.py
  metricflow/model/parsing/schemas_internal.py
  pyproject.toml
Labels: cla:yes

#721 Make test execution more consistent and convenient
  .changes/unreleased/Under the Hood-20230814-225729.yaml
  .github/workflows/cd-sql-engine-tests.yaml
  metricflow/test/fixtures/setup_fixtures.py
  pyproject.toml
Labels: run_mf_sql_engine_tests, cla:yes

#722 Remove EnvironmentVariable helper class
  metricflow/configuration/__init__.py
  metricflow/configuration/env_var.py
  metricflow/test/fixtures/setup_fixtures.py
  metricflow/test/generate_snapshots.py
Labels: cla:yes, Skip Changelog

#727 Fix click bug with mypy
  pyproject.toml
Labels: cla:yes, Skip Changelog

#728 Update snapshot generation script
  .changes/unreleased/Under the Hood-20230816-150030.yaml
  metricflow/test/generate_snapshots.py
Labels: cla:yes

#730 Release PR for MetricFlow 0.201.0
  .changes/0.201.0.md
  .changes/unreleased/Dependencies-20230810-112855.yaml
  .changes/unreleased/Dependencies-20230810-112931.yaml
  .changes/unreleased/Features-20230804-064652.yaml
  .changes/unreleased/Fixes-20230814-231516.yaml
  .changes/unreleased/Under the Hood-20230814-225729.yaml
  .changes/unreleased/Under the Hood-20230816-150030.yaml
  CHANGELOG.md
  attribution.md
  pyproject.toml
Labels: cla:yes, Skip Changelog

#717 Consolidate query interface params
  .changes/unreleased/Features-20230817-100659.yaml
  metricflow/engine/metricflow_engine.py
  metricflow/query/query_parser.py
  metricflow/specs/query_interface.py
  metricflow/specs/where_filter_dimension.py
  metricflow/specs/where_filter_entity.py
  metricflow/specs/where_filter_time_dimension.py
  metricflow/specs/where_filter_transform.py
  metricflow/test/query/test_query_parser.py
  pyproject.toml
Labels: cla:yes

#738 Bump to 0.201.0.dev0
  pyproject.toml
Labels: cla:yes, Skip Changelog

#737 Modified dimensions_for_metric to allow for returning more details
  metricflow/engine/metricflow_engine.py
  metricflow/engine/models.py
Labels: Skip Changelog

#741 bump to 0.202.0.dev1
  pyproject.toml
Labels: cla:yes, Skip Changelog

#742 Updates to snapshot generation script
  metricflow/test/fixtures/sql_client_fixtures.py
  metricflow/test/generate_snapshots.py
Labels: run_mf_sql_engine_tests, cla:yes, Skip Changelog

#735 Expose measures for metrics on MFEngine
  .changes/unreleased/Features-20230823-131738.yaml
  metricflow/engine/metricflow_engine.py
  metricflow/engine/models.py
  metricflow/test/api/test_metricflow_client.py
Labels: cla:yes

#743 Remove unnecessary `JoinOverTimeRange` step from dataflow plan
  .changes/unreleased/Fixes-20230828-165332.yaml
  metricflow/dataflow/builder/dataflow_plan_builder.py
  metricflow/plan_conversion/dataflow_to_sql.py
  metricflow/test/dataflow/builder/test_dataflow_plan_builder.py
  metricflow/test/snapshots/test_dataflow_plan_builder.py/DataflowPlan/test_cumulative_metric_no_window_or_grain_with_metric_time__dfp_0.xml
  metricflow/test/snapshots/test_dataflow_plan_builder.py/DataflowPlan/test_cumulative_metric_no_window_or_grain_without_metric_time__dfp_0.xml
  metricflow/test/snapshots/test_dataflow_plan_builder.py/DataflowPlan/test_cumulative_metric_with_window__dfp_0.xml
  metricflow/test/snapshots/test_dataflow_to_sql_plan.py/SqlQueryPlan/BigQuery/test_cumulative_metric__plan0.sql
  metricflow/test/snapshots/test_dataflow_to_sql_plan.py/SqlQueryPlan/BigQuery/test_cumulative_metric_grain_to_date__plan0.sql
  metricflow/test/snapshots/test_dataflow_to_sql_plan.py/SqlQueryPlan/BigQuery/test_cumulative_metric_no_ds__plan0.sql
  metricflow/test/snapshots/test_dataflow_to_sql_plan.py/SqlQueryPlan/BigQuery/test_cumulative_metric_no_window__plan0.sql
  metricflow/test/snapshots/test_dataflow_to_sql_plan.py/SqlQueryPlan/BigQuery/test_cumulative_metric_no_window_with_time_constraint__plan0.sql
  metricflow/test/snapshots/test_dataflow_to_sql_plan.py/SqlQueryPlan/BigQuery/test_cumulative_metric_with_time_constraint__plan0.sql
  metricflow/test/snapshots/test_dataflow_to_sql_plan.py/SqlQueryPlan/Databricks/test_cumulative_metric__plan0.sql
  metricflow/test/snapshots/test_dataflow_to_sql_plan.py/SqlQueryPlan/Databricks/test_cumulative_metric_grain_to_date__plan0.sql
  metricflow/test/snapshots/test_dataflow_to_sql_plan.py/SqlQueryPlan/Databricks/test_cumulative_metric_no_ds__plan0.sql
  metricflow/test/snapshots/test_dataflow_to_sql_plan.py/SqlQueryPlan/Databricks/test_cumulative_metric_no_window__plan0.sql
  metricflow/test/snapshots/test_dataflow_to_sql_plan.py/SqlQueryPlan/Databricks/test_cumulative_metric_no_window_with_time_constraint__plan0.sql
  metricflow/test/snapshots/test_dataflow_to_sql_plan.py/SqlQueryPlan/Databricks/test_cumulative_metric_with_time_constraint__plan0.sql
  metricflow/test/snapshots/test_dataflow_to_sql_plan.py/SqlQueryPlan/DuckDB/test_cumulative_metric__plan0.sql
  metricflow/test/snapshots/test_dataflow_to_sql_plan.py/SqlQueryPlan/DuckDB/test_cumulative_metric_grain_to_date__plan0.sql
  metricflow/test/snapshots/test_dataflow_to_sql_plan.py/SqlQueryPlan/DuckDB/test_cumulative_metric_no_ds__plan0.sql
  metricflow/test/snapshots/test_dataflow_to_sql_plan.py/SqlQueryPlan/DuckDB/test_cumulative_metric_no_window__plan0.sql
  metricflow/test/snapshots/test_dataflow_to_sql_plan.py/SqlQueryPlan/DuckDB/test_cumulative_metric_no_window_with_time_constraint__plan0.sql
  metricflow/test/snapshots/test_dataflow_to_sql_plan.py/SqlQueryPlan/DuckDB/test_cumulative_metric_with_time_constraint__plan0.sql
  metricflow/test/snapshots/test_dataflow_to_sql_plan.py/SqlQueryPlan/Postgres/test_cumulative_metric__plan0.sql
  metricflow/test/snapshots/test_dataflow_to_sql_plan.py/SqlQueryPlan/Postgres/test_cumulative_metric_grain_to_date__plan0.sql
  metricflow/test/snapshots/test_dataflow_to_sql_plan.py/SqlQueryPlan/Postgres/test_cumulative_metric_no_ds__plan0.sql
  metricflow/test/snapshots/test_dataflow_to_sql_plan.py/SqlQueryPlan/Postgres/test_cumulative_metric_no_window__plan0.sql
  metricflow/test/snapshots/test_dataflow_to_sql_plan.py/SqlQueryPlan/Postgres/test_cumulative_metric_no_window_with_time_constraint__plan0.sql
  metricflow/test/snapshots/test_dataflow_to_sql_plan.py/SqlQueryPlan/Postgres/test_cumulative_metric_with_time_constraint__plan0.sql
  metricflow/test/snapshots/test_dataflow_to_sql_plan.py/SqlQueryPlan/Redshift/test_cumulative_metric__plan0.sql
  metricflow/test/snapshots/test_dataflow_to_sql_plan.py/SqlQueryPlan/Redshift/test_cumulative_metric_grain_to_date__plan0.sql
  metricflow/test/snapshots/test_dataflow_to_sql_plan.py/SqlQueryPlan/Redshift/test_cumulative_metric_no_ds__plan0.sql
  metricflow/test/snapshots/test_dataflow_to_sql_plan.py/SqlQueryPlan/Redshift/test_cumulative_metric_no_window__plan0.sql
  metricflow/test/snapshots/test_dataflow_to_sql_plan.py/SqlQueryPlan/Redshift/test_cumulative_metric_no_window_with_time_constraint__plan0.sql
  metricflow/test/snapshots/test_dataflow_to_sql_plan.py/SqlQueryPlan/Redshift/test_cumulative_metric_with_time_constraint__plan0.sql
  metricflow/test/snapshots/test_dataflow_to_sql_plan.py/SqlQueryPlan/Snowflake/test_cumulative_metric__plan0.sql
  metricflow/test/snapshots/test_dataflow_to_sql_plan.py/SqlQueryPlan/Snowflake/test_cumulative_metric_grain_to_date__plan0.sql
  metricflow/test/snapshots/test_dataflow_to_sql_plan.py/SqlQueryPlan/Snowflake/test_cumulative_metric_no_ds__plan0.sql
  metricflow/test/snapshots/test_dataflow_to_sql_plan.py/SqlQueryPlan/Snowflake/test_cumulative_metric_no_window__plan0.sql
  metricflow/test/snapshots/test_dataflow_to_sql_plan.py/SqlQueryPlan/Snowflake/test_cumulative_metric_no_window_with_time_constraint__plan0.sql
  metricflow/test/snapshots/test_dataflow_to_sql_plan.py/SqlQueryPlan/Snowflake/test_cumulative_metric_with_time_constraint__plan0.sql
  metricflow/test/time/metric_time_dimension.py
Labels: cla:yes

#746 Bump dev version
  pyproject.toml
Labels: cla:yes, Skip Changelog
