Repository dbt-labs/metricflow, pull requests merged in 2024-12, with the labels that each got.

#1522 Update MF to support breaking changes in DSI for custom calendar
  extra-hatch-configuration/requirements.txt
  metricflow-semantics/extra-hatch-configuration/requirements.txt
  metricflow-semantics/metricflow_semantics/errors/custom_grain_not_supported.py
  metricflow-semantics/metricflow_semantics/naming/dunder_scheme.py
  metricflow-semantics/metricflow_semantics/naming/linkable_spec_name.py
  metricflow-semantics/metricflow_semantics/naming/metric_scheme.py
  metricflow-semantics/metricflow_semantics/naming/naming_scheme.py
  metricflow-semantics/metricflow_semantics/naming/object_builder_scheme.py
  metricflow-semantics/metricflow_semantics/query/group_by_item/candidate_push_down/push_down_visitor.py
  metricflow-semantics/metricflow_semantics/query/group_by_item/filter_spec_resolution/filter_spec_resolver.py
  metricflow-semantics/metricflow_semantics/query/query_parser.py
  metricflow-semantics/metricflow_semantics/specs/where_filter/where_filter_dimension.py
  metricflow-semantics/metricflow_semantics/specs/where_filter/where_filter_entity.py
  metricflow-semantics/metricflow_semantics/specs/where_filter/where_filter_transform.py
  metricflow-semantics/metricflow_semantics/test_helpers/semantic_manifest_yamls/simple_manifest/metrics.yaml
  metricflow-semantics/tests_metricflow_semantics/model/semantics/test_metric_lookup.py
  metricflow-semantics/tests_metricflow_semantics/naming/test_dunder_naming_scheme.py
  metricflow-semantics/tests_metricflow_semantics/naming/test_metric_name_scheme.py
  metricflow-semantics/tests_metricflow_semantics/naming/test_object_builder_naming_scheme.py
  metricflow/dataflow/builder/dataflow_plan_builder.py
  metricflow/dataflow/nodes/join_conversion_events.py
  metricflow/engine/models.py
  metricflow/plan_conversion/sql_join_builder.py
  pyproject.toml
  tests_metricflow/plan_conversion/test_dataflow_to_sql_plan.py
  tests_metricflow/snapshots/test_dataflow_plan_builder.py/DataflowPlan/test_cumulative_metric_with_non_default_grain__dfp_0.xml
  tests_metricflow/snapshots/test_dataflow_plan_builder.py/DataflowPlan/test_cumulative_metric_with_window__dfp_0.xml
  tests_metricflow/snapshots/test_dataflow_plan_builder.py/DataflowPlan/test_derived_cumulative_metric_with_non_default_grain__dfp_0.xml
  tests_metricflow/snapshots/test_dataflow_plan_builder.py/DataflowPlan/test_derived_metric_offset_window__dfp_0.xml
  tests_metricflow/snapshots/test_dataflow_plan_builder.py/DataflowPlan/test_derived_metric_offset_with_granularity__dfp_0.xml
  tests_metricflow/snapshots/test_dataflow_plan_builder.py/DataflowPlan/test_derived_offset_cumulative_metric__dfp_0.xml
  tests_metricflow/snapshots/test_dataflow_plan_builder.py/DataflowPlan/test_join_to_time_spine_derived_metric__dfp_0.xml
  tests_metricflow/snapshots/test_dataflow_plan_builder.py/DataflowPlan/test_nested_derived_metric_with_outer_offset__dfp_0.xml
  tests_metricflow/snapshots/test_dataflow_plan_builder.py/DataflowPlan/test_offset_window_metric_filter_and_query_have_different_granularities__dfp_0.xml
  tests_metricflow/snapshots/test_dataflow_to_sql_plan.py/DataflowPlan/test_join_to_time_spine_node_with_offset_window__plan0.xml
  tests_metricflow/snapshots/test_predicate_pushdown_optimizer.py/DataflowPlan/test_conversion_metric_predicate_pushdown__dfp_0.xml
  tests_metricflow/snapshots/test_predicate_pushdown_optimizer.py/DataflowPlan/test_conversion_metric_predicate_pushdown__dfpo_0.xml
  tests_metricflow/snapshots/test_predicate_pushdown_optimizer.py/DataflowPlan/test_cumulative_metric_predicate_pushdown__dfp_0.xml
  tests_metricflow/snapshots/test_predicate_pushdown_optimizer.py/DataflowPlan/test_cumulative_metric_predicate_pushdown__dfpo_0.xml
  tests_metricflow/snapshots/test_predicate_pushdown_optimizer.py/DataflowPlan/test_fill_nulls_time_spine_metric_predicate_pushdown__dfp_0.xml
  tests_metricflow/snapshots/test_predicate_pushdown_optimizer.py/DataflowPlan/test_fill_nulls_time_spine_metric_predicate_pushdown__dfpo_0.xml
  tests_metricflow/snapshots/test_predicate_pushdown_optimizer.py/DataflowPlan/test_fill_nulls_time_spine_metric_with_post_agg_join_predicate_pushdown__dfp_0.xml
  tests_metricflow/snapshots/test_predicate_pushdown_optimizer.py/DataflowPlan/test_fill_nulls_time_spine_metric_with_post_agg_join_predicate_pushdown__dfpo_0.xml
  tests_metricflow/snapshots/test_predicate_pushdown_optimizer.py/DataflowPlan/test_offset_metric_predicate_pushdown__dfp_0.xml
  tests_metricflow/snapshots/test_predicate_pushdown_optimizer.py/DataflowPlan/test_offset_metric_predicate_pushdown__dfpo_0.xml
Labels: cla:yes, Skip Changelog

#1559 Add log line for SQL generation option set
  metricflow/plan_conversion/dataflow_to_sql.py
Labels: cla:yes, Skip Changelog

#1538 Use helper function to find matching instances in dataset
  metricflow-semantics/metricflow_semantics/instances.py
  metricflow/dataset/sql_dataset.py
  metricflow/plan_conversion/dataflow_to_sql.py
Labels: cla:yes, Skip Changelog

#1539 Minimum grain clean up
  metricflow-semantics/metricflow_semantics/specs/linkable_spec_set.py
  metricflow/dataflow/builder/dataflow_plan_builder.py
Labels: cla:yes, Skip Changelog

#1540 Simplify dataflow to SQL logic for `JoinOverTimeRangeNode`
  metricflow/dataflow/nodes/join_over_time.py
  metricflow/dataset/sql_dataset.py
  metricflow/plan_conversion/dataflow_to_sql.py
  metricflow/plan_conversion/instance_converters.py
  metricflow/plan_conversion/sql_join_builder.py
Labels: cla:yes, Skip Changelog

#1544 Bug fix: apply time constraints after time offsets
  .changes/unreleased/Fixes-20241121-140607.yaml
  metricflow/dataflow/builder/dataflow_plan_builder.py
  tests_metricflow/integration/test_cases/itest_metrics.yaml
  tests_metricflow/snapshots/test_derived_metric_rendering.py/SqlQueryPlan/BigQuery/test_cumulative_time_offset_metric_with_time_constraint__plan0.sql
  tests_metricflow/snapshots/test_derived_metric_rendering.py/SqlQueryPlan/BigQuery/test_cumulative_time_offset_metric_with_time_constraint__plan0_optimized.sql
  tests_metricflow/snapshots/test_derived_metric_rendering.py/SqlQueryPlan/BigQuery/test_nested_offsets_with_time_constraint__plan0.sql
  tests_metricflow/snapshots/test_derived_metric_rendering.py/SqlQueryPlan/BigQuery/test_nested_offsets_with_time_constraint__plan0_optimized.sql
  tests_metricflow/snapshots/test_derived_metric_rendering.py/SqlQueryPlan/BigQuery/test_time_offset_metric_with_time_constraint__plan0.sql
  tests_metricflow/snapshots/test_derived_metric_rendering.py/SqlQueryPlan/BigQuery/test_time_offset_metric_with_time_constraint__plan0_optimized.sql
  tests_metricflow/snapshots/test_derived_metric_rendering.py/SqlQueryPlan/Databricks/test_cumulative_time_offset_metric_with_time_constraint__plan0.sql
  tests_metricflow/snapshots/test_derived_metric_rendering.py/SqlQueryPlan/Databricks/test_cumulative_time_offset_metric_with_time_constraint__plan0_optimized.sql
  tests_metricflow/snapshots/test_derived_metric_rendering.py/SqlQueryPlan/Databricks/test_nested_offsets_with_time_constraint__plan0.sql
  tests_metricflow/snapshots/test_derived_metric_rendering.py/SqlQueryPlan/Databricks/test_nested_offsets_with_time_constraint__plan0_optimized.sql
  tests_metricflow/snapshots/test_derived_metric_rendering.py/SqlQueryPlan/Databricks/test_time_offset_metric_with_time_constraint__plan0.sql
  tests_metricflow/snapshots/test_derived_metric_rendering.py/SqlQueryPlan/Databricks/test_time_offset_metric_with_time_constraint__plan0_optimized.sql
  tests_metricflow/snapshots/test_derived_metric_rendering.py/SqlQueryPlan/DuckDB/test_cumulative_time_offset_metric_with_time_constraint__plan0.sql
  tests_metricflow/snapshots/test_derived_metric_rendering.py/SqlQueryPlan/DuckDB/test_cumulative_time_offset_metric_with_time_constraint__plan0_optimized.sql
  tests_metricflow/snapshots/test_derived_metric_rendering.py/SqlQueryPlan/DuckDB/test_nested_offsets_with_time_constraint__plan0.sql
  tests_metricflow/snapshots/test_derived_metric_rendering.py/SqlQueryPlan/DuckDB/test_nested_offsets_with_time_constraint__plan0_optimized.sql
  tests_metricflow/snapshots/test_derived_metric_rendering.py/SqlQueryPlan/DuckDB/test_time_offset_metric_with_time_constraint__plan0.sql
  tests_metricflow/snapshots/test_derived_metric_rendering.py/SqlQueryPlan/DuckDB/test_time_offset_metric_with_time_constraint__plan0_optimized.sql
  tests_metricflow/snapshots/test_derived_metric_rendering.py/SqlQueryPlan/Postgres/test_cumulative_time_offset_metric_with_time_constraint__plan0.sql
  tests_metricflow/snapshots/test_derived_metric_rendering.py/SqlQueryPlan/Postgres/test_cumulative_time_offset_metric_with_time_constraint__plan0_optimized.sql
  tests_metricflow/snapshots/test_derived_metric_rendering.py/SqlQueryPlan/Postgres/test_nested_offsets_with_time_constraint__plan0.sql
  tests_metricflow/snapshots/test_derived_metric_rendering.py/SqlQueryPlan/Postgres/test_nested_offsets_with_time_constraint__plan0_optimized.sql
  tests_metricflow/snapshots/test_derived_metric_rendering.py/SqlQueryPlan/Postgres/test_time_offset_metric_with_time_constraint__plan0.sql
  tests_metricflow/snapshots/test_derived_metric_rendering.py/SqlQueryPlan/Postgres/test_time_offset_metric_with_time_constraint__plan0_optimized.sql
  tests_metricflow/snapshots/test_derived_metric_rendering.py/SqlQueryPlan/Redshift/test_cumulative_time_offset_metric_with_time_constraint__plan0.sql
  tests_metricflow/snapshots/test_derived_metric_rendering.py/SqlQueryPlan/Redshift/test_cumulative_time_offset_metric_with_time_constraint__plan0_optimized.sql
  tests_metricflow/snapshots/test_derived_metric_rendering.py/SqlQueryPlan/Redshift/test_nested_offsets_with_time_constraint__plan0.sql
  tests_metricflow/snapshots/test_derived_metric_rendering.py/SqlQueryPlan/Redshift/test_nested_offsets_with_time_constraint__plan0_optimized.sql
  tests_metricflow/snapshots/test_derived_metric_rendering.py/SqlQueryPlan/Redshift/test_time_offset_metric_with_time_constraint__plan0.sql
  tests_metricflow/snapshots/test_derived_metric_rendering.py/SqlQueryPlan/Redshift/test_time_offset_metric_with_time_constraint__plan0_optimized.sql
  tests_metricflow/snapshots/test_derived_metric_rendering.py/SqlQueryPlan/Snowflake/test_cumulative_time_offset_metric_with_time_constraint__plan0.sql
  tests_metricflow/snapshots/test_derived_metric_rendering.py/SqlQueryPlan/Snowflake/test_cumulative_time_offset_metric_with_time_constraint__plan0_optimized.sql
  tests_metricflow/snapshots/test_derived_metric_rendering.py/SqlQueryPlan/Snowflake/test_nested_offsets_with_time_constraint__plan0.sql
  tests_metricflow/snapshots/test_derived_metric_rendering.py/SqlQueryPlan/Snowflake/test_nested_offsets_with_time_constraint__plan0_optimized.sql
  tests_metricflow/snapshots/test_derived_metric_rendering.py/SqlQueryPlan/Snowflake/test_time_offset_metric_with_time_constraint__plan0.sql
  tests_metricflow/snapshots/test_derived_metric_rendering.py/SqlQueryPlan/Snowflake/test_time_offset_metric_with_time_constraint__plan0_optimized.sql
  tests_metricflow/snapshots/test_derived_metric_rendering.py/SqlQueryPlan/Trino/test_cumulative_time_offset_metric_with_time_constraint__plan0.sql
  tests_metricflow/snapshots/test_derived_metric_rendering.py/SqlQueryPlan/Trino/test_cumulative_time_offset_metric_with_time_constraint__plan0_optimized.sql
  tests_metricflow/snapshots/test_derived_metric_rendering.py/SqlQueryPlan/Trino/test_nested_offsets_with_time_constraint__plan0.sql
  tests_metricflow/snapshots/test_derived_metric_rendering.py/SqlQueryPlan/Trino/test_nested_offsets_with_time_constraint__plan0_optimized.sql
  tests_metricflow/snapshots/test_derived_metric_rendering.py/SqlQueryPlan/Trino/test_time_offset_metric_with_time_constraint__plan0.sql
  tests_metricflow/snapshots/test_derived_metric_rendering.py/SqlQueryPlan/Trino/test_time_offset_metric_with_time_constraint__plan0_optimized.sql
Labels: cla:yes

#1545 Various cleanup
  metricflow-semantics/metricflow_semantics/specs/time_dimension_spec.py
  metricflow-semantics/metricflow_semantics/time/time_spine_source.py
  metricflow/dataflow/builder/dataflow_plan_builder.py
  metricflow/plan_conversion/dataflow_to_sql.py
  tests_metricflow/plan_conversion/test_dataflow_to_sql_plan.py
  tests_metricflow/snapshots/test_dataflow_to_sql_plan.py/DataflowPlan/test_join_to_time_spine_node_with_offset_to_grain__plan0.xml
  tests_metricflow/snapshots/test_dataflow_to_sql_plan.py/DataflowPlan/test_join_to_time_spine_node_without_offset__plan0.xml
  tests_metricflow/snapshots/test_dataflow_to_sql_plan.py/SqlQueryPlan/test_join_to_time_spine_node_with_offset_to_grain__plan0.xml
  tests_metricflow/snapshots/test_dataflow_to_sql_plan.py/SqlQueryPlan/test_join_to_time_spine_node_with_offset_window__plan0.xml
  tests_metricflow/snapshots/test_dataflow_to_sql_plan.py/SqlQueryPlan/test_join_to_time_spine_node_without_offset__plan0.xml
Labels: cla:yes, Skip Changelog

#1564 Add tags to SavedQueries
  .changes/unreleased/Features-20241210-172725.yaml
  metricflow/engine/models.py
Labels: cla:yes

#1565 Add marker for DuckDb-only tests
  tests_metricflow/fixtures/setup_fixtures.py
  tests_metricflow/test_pytest_markers.py
Labels: cla:yes, Skip Changelog

#1566 Add improved test for the SQL optimization level in the request
  metricflow/dataflow/optimizer/source_scan/cm_branch_combiner.py
  metricflow/dataflow/optimizer/source_scan/source_scan_optimizer.py
  metricflow/sql/optimizer/optimization_levels.py
  tests_metricflow/engine/test_explain.py
  tests_metricflow/integration/test_mf_engine.py
  tests_metricflow/snapshot_utils.py
  tests_metricflow/snapshots/test_explain.py/str/test_optimization_level__result.txt
Labels: cla:yes, Skip Changelog

#1567 Rename `MetricFlowTestConfiguration` in snapshot-generation script
  tests_metricflow/generate_snapshots.py
  tests_metricflow/populate_persistent_source_schemas.py
Labels: cla:yes, Skip Changelog

#1569 Add retries for SQL generation using lower optimization levels
  metricflow/plan_conversion/dataflow_to_sql.py
Labels: cla:yes, Skip Changelog

#1570 Implement `Mergeable` for `SqlExpressionTreeLineage`
  metricflow/sql/optimizer/rewriting_sub_query_reducer.py
  metricflow/sql/optimizer/tag_required_column_aliases.py
  metricflow/sql/sql_exprs.py
Labels: cla:yes, Skip Changelog

#1571 Rename `tag_required_column_aliases.py`
  metricflow/sql/optimizer/column_pruner.py
  metricflow/sql/optimizer/required_column_aliases.py
Labels: cla:yes, Skip Changelog

#1572 Rename `SqlQuery` to `SqlStatement`
  dbt-metricflow/dbt_metricflow/cli/main.py
  metricflow/engine/metricflow_engine.py
  metricflow/execution/dataflow_to_execution.py
  metricflow/execution/execution_plan.py
  metricflow/validation/data_warehouse_model_validator.py
  tests_metricflow/engine/test_explain.py
  tests_metricflow/execution/noop_task.py
  tests_metricflow/execution/test_tasks.py
  tests_metricflow/integration/test_rendered_query.py
  tests_metricflow/plan_conversion/test_dataflow_to_execution.py
  tests_metricflow/snapshots/test_dataflow_to_execution.py/ExecutionPlan/DuckDB/test_combined_metrics_plan__ep_0.xml
  tests_metricflow/snapshots/test_dataflow_to_execution.py/ExecutionPlan/DuckDB/test_joined_plan__ep_0.xml
  tests_metricflow/snapshots/test_dataflow_to_execution.py/ExecutionPlan/DuckDB/test_multihop_joined_plan__ep_0.xml
  tests_metricflow/snapshots/test_dataflow_to_execution.py/ExecutionPlan/DuckDB/test_small_combined_metrics_plan__ep_0.xml
Labels: cla:yes, Skip Changelog

#1562 Create `SqlAddTimeExpression`
  metricflow-semantics/metricflow_semantics/dag/id_prefix.py
  metricflow/sql/render/big_query.py
  metricflow/sql/render/duckdb_renderer.py
  metricflow/sql/render/expr_renderer.py
  metricflow/sql/render/postgres.py
  metricflow/sql/render/trino.py
  metricflow/sql/sql_exprs.py
  tests_metricflow/snapshots/test_engine_specific_rendering.py/SqlQueryPlan/BigQuery/test_add_time_expr__plan0.sql
  tests_metricflow/snapshots/test_engine_specific_rendering.py/SqlQueryPlan/Databricks/test_add_time_expr__plan0.sql
  tests_metricflow/snapshots/test_engine_specific_rendering.py/SqlQueryPlan/DuckDB/test_add_time_expr__plan0.sql
  tests_metricflow/snapshots/test_engine_specific_rendering.py/SqlQueryPlan/Postgres/test_add_time_expr__plan0.sql
  tests_metricflow/snapshots/test_engine_specific_rendering.py/SqlQueryPlan/Redshift/test_add_time_expr__plan0.sql
  tests_metricflow/snapshots/test_engine_specific_rendering.py/SqlQueryPlan/Snowflake/test_add_time_expr__plan0.sql
  tests_metricflow/snapshots/test_engine_specific_rendering.py/SqlQueryPlan/Trino/test_add_time_expr__plan0.sql
  tests_metricflow/sql/test_engine_specific_rendering.py
Labels: cla:yes, Skip Changelog

#1580 Rename snapshots for `test_add_time_expr`
  tests_metricflow/snapshots/test_engine_specific_rendering.py/SqlPlan/BigQuery/test_add_time_expr__plan0.sql
  tests_metricflow/snapshots/test_engine_specific_rendering.py/SqlPlan/Databricks/test_add_time_expr__plan0.sql
  tests_metricflow/snapshots/test_engine_specific_rendering.py/SqlPlan/DuckDB/test_add_time_expr__plan0.sql
  tests_metricflow/snapshots/test_engine_specific_rendering.py/SqlPlan/Postgres/test_add_time_expr__plan0.sql
  tests_metricflow/snapshots/test_engine_specific_rendering.py/SqlPlan/Redshift/test_add_time_expr__plan0.sql
  tests_metricflow/snapshots/test_engine_specific_rendering.py/SqlPlan/Snowflake/test_add_time_expr__plan0.sql
  tests_metricflow/snapshots/test_engine_specific_rendering.py/SqlPlan/Trino/test_add_time_expr__plan0.sql
Labels: Skip Changelog

#1575 Add SQL exprs needed for custom offset window
  metricflow-semantics/metricflow_semantics/dag/id_prefix.py
  metricflow-semantics/metricflow_semantics/sql/sql_exprs.py
  metricflow/dataset/convert_semantic_model.py
  metricflow/plan_conversion/dataflow_to_sql.py
  metricflow/plan_conversion/instance_converters.py
  metricflow/plan_conversion/sql_expression_builders.py
  metricflow/plan_conversion/sql_join_builder.py
  metricflow/sql/optimizer/required_column_aliases.py
  metricflow/sql/optimizer/rewriting_sub_query_reducer.py
  metricflow/sql/optimizer/sub_query_reducer.py
  metricflow/sql/render/big_query.py
  metricflow/sql/render/databricks.py
  metricflow/sql/render/duckdb_renderer.py
  metricflow/sql/render/expr_renderer.py
  metricflow/sql/render/postgres.py
  metricflow/sql/render/redshift.py
  metricflow/sql/render/snowflake.py
  metricflow/sql/render/sql_plan_renderer.py
  metricflow/sql/render/trino.py
  metricflow/sql/sql_plan.py
  tests_metricflow/dataflow/builder/test_node_data_set.py
  tests_metricflow/integration/test_configured_cases.py
  tests_metricflow/mf_logging/test_dag_to_text.py
  tests_metricflow/plan_conversion/instance_converters/test_create_select_columns_with_measures_aggregated.py
  tests_metricflow/snapshots/test_engine_specific_rendering.py/SqlPlan/BigQuery/test_add_time_expr__plan0.sql
  tests_metricflow/snapshots/test_engine_specific_rendering.py/SqlPlan/Postgres/test_add_time_expr__plan0.sql
  tests_metricflow/snapshots/test_engine_specific_rendering.py/SqlPlan/Trino/test_add_time_expr__plan0.sql
  tests_metricflow/sql/optimizer/test_column_pruner.py
  tests_metricflow/sql/optimizer/test_cte_column_pruner.py
  tests_metricflow/sql/optimizer/test_cte_rewriting_sub_query_reducer.py
  tests_metricflow/sql/optimizer/test_cte_table_alias_simplifier.py
  tests_metricflow/sql/optimizer/test_rewriting_sub_query_reducer.py
  tests_metricflow/sql/optimizer/test_sub_query_reducer.py
  tests_metricflow/sql/optimizer/test_table_alias_simplifier.py
  tests_metricflow/sql/test_engine_specific_rendering.py
  tests_metricflow/sql/test_render_cte.py
  tests_metricflow/sql/test_sql_expr_render.py
  tests_metricflow/sql/test_sql_plan_render.py
  tests_metricflow/sql_clients/test_date_time_operations.py
Labels: cla:yes, Skip Changelog

#1576 Add `window_function` attribute to `TimeDimensionSpec`
  metricflow-semantics/metricflow_semantics/instances.py
  metricflow-semantics/metricflow_semantics/specs/dunder_column_association_resolver.py
  metricflow-semantics/metricflow_semantics/specs/time_dimension_spec.py
  metricflow-semantics/tests_metricflow_semantics/collection_helpers/test_pretty_print.py
  metricflow-semantics/tests_metricflow_semantics/fixtures/manifest_fixtures.py
  metricflow/dataflow/nodes/filter_elements.py
  metricflow/engine/metricflow_engine.py
  metricflow/validation/data_warehouse_model_validator.py
  scripts/ci_tests/metricflow_package_test.py
  tests_metricflow/dataflow/builder/test_node_data_set.py
  tests_metricflow/dataflow/builder/test_node_evaluator.py
  tests_metricflow/examples/test_node_sql.py
  tests_metricflow/fixtures/manifest_fixtures.py
  tests_metricflow/integration/conftest.py
  tests_metricflow/integration/test_rendered_query.py
  tests_metricflow/plan_conversion/instance_converters/test_create_select_columns_with_measures_aggregated.py
  tests_metricflow/plan_conversion/test_dataflow_to_execution.py
Labels: cla:yes, Skip Changelog
