Repository dbt-labs/metricflow, pull requests merged in 2024-11, with the labels that each got.

#1485 Change `resolved_primary_entity` helper signature
  metricflow-semantics/metricflow_semantics/model/semantics/semantic_model_helper.py
  metricflow-semantics/metricflow_semantics/model/semantics/semantic_model_lookup.py
  metricflow/engine/metricflow_engine.py
Labels: cla:yes, Skip Changelog

#1486 Add `MeasureLookup` to break-up `SemanticModelLookup`
  metricflow-semantics/metricflow_semantics/model/semantics/linkable_spec_resolver.py
  metricflow-semantics/metricflow_semantics/model/semantics/measure_lookup.py
  metricflow-semantics/metricflow_semantics/model/semantics/metric_lookup.py
  metricflow-semantics/metricflow_semantics/model/semantics/semantic_model_helper.py
  metricflow-semantics/metricflow_semantics/model/semantics/semantic_model_lookup.py
  metricflow-semantics/metricflow_semantics/query/query_resolver.py
  metricflow-semantics/metricflow_semantics/query/validation_rules/metric_time_requirements.py
  metricflow-semantics/metricflow_semantics/specs/linkable_spec_set.py
  metricflow-semantics/metricflow_semantics/specs/time_dimension_spec.py
  metricflow-semantics/tests_metricflow_semantics/model/semantics/test_measure_lookup.py
  metricflow-semantics/tests_metricflow_semantics/model/test_semantic_model_container.py
  metricflow-semantics/tests_metricflow_semantics/snapshots/test_measure_lookup.py/dict/test_measure_properties__obj_0.txt
  metricflow/dataflow/builder/dataflow_plan_builder.py
  metricflow/engine/metricflow_engine.py
  metricflow/plan_conversion/instance_converters.py
Labels: cla:yes, Skip Changelog

#1487 Add `DimensionLookup` to break-up `SemanticModelLookup`
  metricflow-semantics/metricflow_semantics/model/semantics/dimension_lookup.py
  metricflow-semantics/metricflow_semantics/model/semantics/semantic_model_lookup.py
  metricflow-semantics/tests_metricflow_semantics/model/semantics/test_dimension_lookup.py
  metricflow-semantics/tests_metricflow_semantics/snapshots/test_dimension_lookup.py/dict/test_get_invariant__obj_0.txt
  metricflow/dataflow/builder/partitions.py
Labels: cla:yes, Skip Changelog

#1488 Fix Bug with `get_defined_time_granularity()`
  metricflow-semantics/metricflow_semantics/model/semantics/metric_lookup.py
  metricflow-semantics/tests_metricflow_semantics/model/semantics/test_metric_lookup.py
  metricflow/dataflow/builder/dataflow_plan_builder.py
  metricflow/dataflow/builder/measure_spec_properties.py
  tests_metricflow/integration/test_cases/itest_dimensions.yaml
Labels: cla:yes, Skip Changelog

#1494 Fix `SourceScanOptimizer` generating duplicated columns
  .changes/unreleased/Fixes-20241030-201214.yaml
  metricflow-semantics/metricflow_semantics/test_helpers/semantic_manifest_yamls/simple_manifest/metrics.yaml
  metricflow-semantics/tests_metricflow_semantics/snapshots/test_linkable_spec_resolver.py/list/test_linkable_element_set_as_spec_set__set0.txt
  metricflow-semantics/tests_metricflow_semantics/snapshots/test_semantic_model_container.py/str/test_linkable_elements_for_measure__result0.txt
  metricflow-semantics/tests_metricflow_semantics/snapshots/test_semantic_model_container.py/tuple/test_linkable_elements_for_no_metrics_query__result0.txt
  metricflow/dataflow/nodes/compute_metrics.py
  tests_metricflow/dataflow/optimizer/source_scan/test_source_scan_optimizer.py
  tests_metricflow/integration/test_cases/itest_metrics.yaml
  tests_metricflow/query_rendering/test_derived_metric_rendering.py
  tests_metricflow/snapshots/test_derived_metric_rendering.py/SqlQueryPlan/BigQuery/test_derived_metric_that_defines_the_same_alias_in_different_components__plan0.sql
  tests_metricflow/snapshots/test_derived_metric_rendering.py/SqlQueryPlan/BigQuery/test_derived_metric_that_defines_the_same_alias_in_different_components__plan0_optimized.sql
  tests_metricflow/snapshots/test_derived_metric_rendering.py/SqlQueryPlan/Databricks/test_derived_metric_that_defines_the_same_alias_in_different_components__plan0.sql
  tests_metricflow/snapshots/test_derived_metric_rendering.py/SqlQueryPlan/Databricks/test_derived_metric_that_defines_the_same_alias_in_different_components__plan0_optimized.sql
  tests_metricflow/snapshots/test_derived_metric_rendering.py/SqlQueryPlan/DuckDB/test_derived_metric_that_defines_the_same_alias_in_different_components__plan0.sql
  tests_metricflow/snapshots/test_derived_metric_rendering.py/SqlQueryPlan/DuckDB/test_derived_metric_that_defines_the_same_alias_in_different_components__plan0_optimized.sql
  tests_metricflow/snapshots/test_derived_metric_rendering.py/SqlQueryPlan/Postgres/test_derived_metric_that_defines_the_same_alias_in_different_components__plan0.sql
  tests_metricflow/snapshots/test_derived_metric_rendering.py/SqlQueryPlan/Postgres/test_derived_metric_that_defines_the_same_alias_in_different_components__plan0_optimized.sql
  tests_metricflow/snapshots/test_derived_metric_rendering.py/SqlQueryPlan/Redshift/test_derived_metric_that_defines_the_same_alias_in_different_components__plan0.sql
  tests_metricflow/snapshots/test_derived_metric_rendering.py/SqlQueryPlan/Redshift/test_derived_metric_that_defines_the_same_alias_in_different_components__plan0_optimized.sql
  tests_metricflow/snapshots/test_derived_metric_rendering.py/SqlQueryPlan/Snowflake/test_derived_metric_that_defines_the_same_alias_in_different_components__plan0.sql
  tests_metricflow/snapshots/test_derived_metric_rendering.py/SqlQueryPlan/Snowflake/test_derived_metric_that_defines_the_same_alias_in_different_components__plan0_optimized.sql
  tests_metricflow/snapshots/test_derived_metric_rendering.py/SqlQueryPlan/Trino/test_derived_metric_that_defines_the_same_alias_in_different_components__plan0.sql
  tests_metricflow/snapshots/test_derived_metric_rendering.py/SqlQueryPlan/Trino/test_derived_metric_that_defines_the_same_alias_in_different_components__plan0_optimized.sql
  tests_metricflow/snapshots/test_source_scan_optimizer.py/DataflowPlan/test_derived_metric_same_alias_components_combined__dfp_0.xml
  tests_metricflow/snapshots/test_source_scan_optimizer.py/DataflowPlan/test_derived_metric_same_alias_components_combined__dfpo_0.xml
  tests_metricflow/snapshots/test_source_scan_optimizer.py/DataflowPlan/test_derived_metric_same_alias_components_not_combined__dfp_0.xml
  tests_metricflow/snapshots/test_source_scan_optimizer.py/DataflowPlan/test_derived_metric_same_alias_components_not_combined__dfpo_0.xml
Labels: cla:yes, Run Tests With Other SQL Engines

#1496 Update `LinkableSpecName.from_name` to parse custom grains
  metricflow-semantics/metricflow_semantics/model/semantics/semantic_model_lookup.py
  metricflow-semantics/metricflow_semantics/naming/linkable_spec_name.py
  metricflow-semantics/metricflow_semantics/specs/patterns/typed_patterns.py
  metricflow-semantics/metricflow_semantics/specs/query_param_implementations.py
  metricflow-semantics/metricflow_semantics/specs/where_filter/where_filter_time_dimension.py
  metricflow-semantics/metricflow_semantics/specs/where_filter/where_filter_transform.py
  metricflow-semantics/tests_metricflow_semantics/model/test_where_filter_spec.py
  metricflow/dataflow/builder/dataflow_plan_builder.py
  metricflow/engine/metricflow_engine.py
  metricflow/engine/models.py
Labels: cla:yes, Skip Changelog

#1505 Support for `join_to_timespine` metrics with custom grain in the group by
  .changes/unreleased/Features-20241104-193531.yaml
  metricflow-semantics/metricflow_semantics/time/time_spine_source.py
  metricflow/dataflow/builder/dataflow_plan_builder.py
  metricflow/dataset/convert_semantic_model.py
  metricflow/plan_conversion/dataflow_to_sql.py
  tests_metricflow/integration/query_output/test_fill_nulls_with_0.py
  tests_metricflow/integration/test_cases/itest_granularity.yaml
  tests_metricflow/query_rendering/test_custom_granularity.py
  tests_metricflow/snapshots/test_custom_granularity.py/SqlQueryPlan/BigQuery/test_join_to_time_spine_metric_grouped_by_custom_grain__plan0.sql
  tests_metricflow/snapshots/test_custom_granularity.py/SqlQueryPlan/BigQuery/test_join_to_time_spine_metric_grouped_by_custom_grain__plan0_optimized.sql
  tests_metricflow/snapshots/test_custom_granularity.py/SqlQueryPlan/Databricks/test_join_to_time_spine_metric_grouped_by_custom_grain__plan0.sql
  tests_metricflow/snapshots/test_custom_granularity.py/SqlQueryPlan/Databricks/test_join_to_time_spine_metric_grouped_by_custom_grain__plan0_optimized.sql
  tests_metricflow/snapshots/test_custom_granularity.py/SqlQueryPlan/DuckDB/test_join_to_time_spine_metric_grouped_by_custom_grain__plan0.sql
  tests_metricflow/snapshots/test_custom_granularity.py/SqlQueryPlan/DuckDB/test_join_to_time_spine_metric_grouped_by_custom_grain__plan0_optimized.sql
  tests_metricflow/snapshots/test_custom_granularity.py/SqlQueryPlan/Postgres/test_join_to_time_spine_metric_grouped_by_custom_grain__plan0.sql
  tests_metricflow/snapshots/test_custom_granularity.py/SqlQueryPlan/Postgres/test_join_to_time_spine_metric_grouped_by_custom_grain__plan0_optimized.sql
  tests_metricflow/snapshots/test_custom_granularity.py/SqlQueryPlan/Redshift/test_join_to_time_spine_metric_grouped_by_custom_grain__plan0.sql
  tests_metricflow/snapshots/test_custom_granularity.py/SqlQueryPlan/Redshift/test_join_to_time_spine_metric_grouped_by_custom_grain__plan0_optimized.sql
  tests_metricflow/snapshots/test_custom_granularity.py/SqlQueryPlan/Snowflake/test_join_to_time_spine_metric_grouped_by_custom_grain__plan0.sql
  tests_metricflow/snapshots/test_custom_granularity.py/SqlQueryPlan/Snowflake/test_join_to_time_spine_metric_grouped_by_custom_grain__plan0_optimized.sql
  tests_metricflow/snapshots/test_custom_granularity.py/SqlQueryPlan/Trino/test_join_to_time_spine_metric_grouped_by_custom_grain__plan0.sql
  tests_metricflow/snapshots/test_custom_granularity.py/SqlQueryPlan/Trino/test_join_to_time_spine_metric_grouped_by_custom_grain__plan0_optimized.sql
  tests_metricflow/snapshots/test_fill_nulls_with_0.py/str/BigQuery/test_join_to_time_spine_with_custom_grain_in_group_by__query_output.txt
  tests_metricflow/snapshots/test_fill_nulls_with_0.py/str/Databricks/test_join_to_time_spine_with_custom_grain_in_group_by__query_output.txt
  tests_metricflow/snapshots/test_fill_nulls_with_0.py/str/DuckDB/test_join_to_time_spine_with_custom_grain_in_group_by__query_output.txt
  tests_metricflow/snapshots/test_fill_nulls_with_0.py/str/Postgres/test_join_to_time_spine_with_custom_grain_in_group_by__query_output.txt
  tests_metricflow/snapshots/test_fill_nulls_with_0.py/str/Redshift/test_join_to_time_spine_with_custom_grain_in_group_by__query_output.txt
  tests_metricflow/snapshots/test_fill_nulls_with_0.py/str/Snowflake/test_join_to_time_spine_with_custom_grain_in_group_by__query_output.txt
  tests_metricflow/snapshots/test_fill_nulls_with_0.py/str/Trino/test_join_to_time_spine_with_custom_grain_in_group_by__query_output.txt
Labels: cla:yes

#1511 Align dataflow plans
  metricflow/dataflow/builder/dataflow_plan_builder.py
  tests_metricflow/snapshots/test_dataflow_plan_builder.py/DataflowPlan/test_dimensions_with_time_constraint__dfp_0.xml
  tests_metricflow/snapshots/test_dataflow_plan_builder.py/DataflowPlan/test_distinct_values_plan_with_join__dfp_0.xml
  tests_metricflow/snapshots/test_dataflow_plan_builder.py/DataflowPlan/test_metric_time_with_other_dimensions__dfp_0.xml
  tests_metricflow/snapshots/test_predicate_pushdown_optimizer.py/DataflowPlan/test_conversion_metric_predicate_pushdown__dfp_0.xml
  tests_metricflow/snapshots/test_predicate_pushdown_optimizer.py/DataflowPlan/test_conversion_metric_predicate_pushdown__dfpo_0.xml
Labels: cla:yes, Skip Changelog

#1497 Remove unused code
  metricflow-semantics/metricflow_semantics/model/semantics/semantic_model_container.py
  metricflow-semantics/metricflow_semantics/model/semantics/semantic_model_lookup.py
  metricflow-semantics/tests_metricflow_semantics/model/test_semantic_model_container.py
Labels: cla:yes, Skip Changelog

#1500 Add `eq=False` to node classes
  metricflow-semantics/metricflow_semantics/dag/mf_dag.py
  metricflow/dataflow/dataflow_plan.py
  metricflow/dataflow/nodes/add_generated_uuid.py
  metricflow/dataflow/nodes/aggregate_measures.py
  metricflow/dataflow/nodes/combine_aggregated_outputs.py
  metricflow/dataflow/nodes/compute_metrics.py
  metricflow/dataflow/nodes/constrain_time.py
  metricflow/dataflow/nodes/filter_elements.py
  metricflow/dataflow/nodes/join_conversion_events.py
  metricflow/dataflow/nodes/join_over_time.py
  metricflow/dataflow/nodes/join_to_base.py
  metricflow/dataflow/nodes/join_to_custom_granularity.py
  metricflow/dataflow/nodes/join_to_time_spine.py
  metricflow/dataflow/nodes/metric_time_transform.py
  metricflow/dataflow/nodes/min_max.py
  metricflow/dataflow/nodes/order_by_limit.py
  metricflow/dataflow/nodes/read_sql_source.py
  metricflow/dataflow/nodes/semi_additive_join.py
  metricflow/dataflow/nodes/where_filter.py
  metricflow/dataflow/nodes/window_reaggregation_node.py
  metricflow/dataflow/nodes/write_to_data_table.py
  metricflow/dataflow/nodes/write_to_table.py
  metricflow/sql/sql_exprs.py
  metricflow/sql/sql_plan.py
Labels: cla:yes, Skip Changelog

#1513 Support expectations in snapshot files
  metricflow-semantics/metricflow_semantics/test_helpers/snapshot_helpers.py
  metricflow-semantics/tests_metricflow_semantics/snapshots/test_snapshot.py/str/test_expectation_description__result.txt
  metricflow-semantics/tests_metricflow_semantics/test_snapshot.py
  tests_metricflow/snapshot_utils.py
Labels: cla:yes, Skip Changelog

#1501 Split column pruner into two phases
  metricflow/plan_conversion/dataflow_to_sql.py
  metricflow/sql/optimizer/column_pruner.py
  metricflow/sql/optimizer/tag_column_aliases.py
  metricflow/sql/optimizer/tag_required_column_aliases.py
  metricflow/sql/sql_plan.py
  tests_metricflow/snapshots/test_conversion_metrics_to_sql.py/SqlQueryPlan/test_conversion_count_with_no_group_by__plan0.xml
  tests_metricflow/snapshots/test_conversion_metrics_to_sql.py/SqlQueryPlan/test_conversion_metric_join_to_timespine_and_fill_nulls_with_0__plan0.xml
  tests_metricflow/snapshots/test_conversion_metrics_to_sql.py/SqlQueryPlan/test_conversion_rate__plan0.xml
  tests_metricflow/snapshots/test_conversion_metrics_to_sql.py/SqlQueryPlan/test_conversion_rate_with_constant_properties__plan0.xml
  tests_metricflow/snapshots/test_conversion_metrics_to_sql.py/SqlQueryPlan/test_conversion_rate_with_no_group_by__plan0.xml
  tests_metricflow/snapshots/test_conversion_metrics_to_sql.py/SqlQueryPlan/test_conversion_rate_with_window__plan0.xml
  tests_metricflow/snapshots/test_dataflow_to_sql_plan.py/SqlQueryPlan/test_combine_output_node__plan0.xml
  tests_metricflow/snapshots/test_dataflow_to_sql_plan.py/SqlQueryPlan/test_compute_metrics_node__plan0.xml
  tests_metricflow/snapshots/test_dataflow_to_sql_plan.py/SqlQueryPlan/test_compute_metrics_node_ratio_from_multiple_semantic_models__plan0.xml
  tests_metricflow/snapshots/test_dataflow_to_sql_plan.py/SqlQueryPlan/test_compute_metrics_node_ratio_from_single_semantic_model__plan0.xml
  tests_metricflow/snapshots/test_dataflow_to_sql_plan.py/SqlQueryPlan/test_compute_metrics_node_simple_expr__plan0.xml
  tests_metricflow/snapshots/test_dataflow_to_sql_plan.py/SqlQueryPlan/test_constrain_time_range_node__plan0.xml
  tests_metricflow/snapshots/test_dataflow_to_sql_plan.py/SqlQueryPlan/test_dimension_with_joined_where_constraint__plan0.xml
  tests_metricflow/snapshots/test_dataflow_to_sql_plan.py/SqlQueryPlan/test_dimensions_requiring_join__plan0.xml
  tests_metricflow/snapshots/test_dataflow_to_sql_plan.py/SqlQueryPlan/test_filter_node__plan0.xml
  tests_metricflow/snapshots/test_dataflow_to_sql_plan.py/SqlQueryPlan/test_filter_with_where_constraint_node__plan0.xml
  tests_metricflow/snapshots/test_dataflow_to_sql_plan.py/SqlQueryPlan/test_join_to_time_spine_node_with_offset_to_grain__plan0.xml
  tests_metricflow/snapshots/test_dataflow_to_sql_plan.py/SqlQueryPlan/test_join_to_time_spine_node_with_offset_window__plan0.xml
  tests_metricflow/snapshots/test_dataflow_to_sql_plan.py/SqlQueryPlan/test_join_to_time_spine_node_without_offset__plan0.xml
  tests_metricflow/snapshots/test_dataflow_to_sql_plan.py/SqlQueryPlan/test_measure_aggregation_node__plan0.xml
  tests_metricflow/snapshots/test_dataflow_to_sql_plan.py/SqlQueryPlan/test_multi_join_node__plan0.xml
  tests_metricflow/snapshots/test_dataflow_to_sql_plan.py/SqlQueryPlan/test_order_by_node__plan0.xml
  tests_metricflow/snapshots/test_dataflow_to_sql_plan.py/SqlQueryPlan/test_semi_additive_join_node__plan0.xml
  tests_metricflow/snapshots/test_dataflow_to_sql_plan.py/SqlQueryPlan/test_semi_additive_join_node_with_grouping__plan0.xml
  tests_metricflow/snapshots/test_dataflow_to_sql_plan.py/SqlQueryPlan/test_semi_additive_join_node_with_queried_group_by__plan0.xml
  tests_metricflow/snapshots/test_dataflow_to_sql_plan.py/SqlQueryPlan/test_single_join_node__plan0.xml
  tests_metricflow/snapshots/test_dataflow_to_sql_plan.py/SqlQueryPlan/test_source_node__plan0.xml
  tests_metricflow/snapshots/test_distinct_values_to_sql.py/SqlQueryPlan/test_dimension_values_with_a_join_and_a_filter__plan0.xml
  tests_metricflow/snapshots/test_distinct_values_to_sql.py/SqlQueryPlan/test_dimensions_requiring_join__plan0.xml
  tests_metricflow/snapshots/test_metric_time_dimension_to_sql.py/SqlQueryPlan/test_metric_time_dimension_transform_node_using_non_primary_time__plan0.xml
  tests_metricflow/snapshots/test_metric_time_dimension_to_sql.py/SqlQueryPlan/test_metric_time_dimension_transform_node_using_primary_time__plan0.xml
  tests_metricflow/snapshots/test_metric_time_dimension_to_sql.py/SqlQueryPlan/test_simple_query_with_metric_time_dimension__plan0.xml
  tests_metricflow/snapshots/test_metric_time_without_metrics.py/SqlQueryPlan/test_dimensions_with_time_constraint__plan0.xml
  tests_metricflow/snapshots/test_metric_time_without_metrics.py/SqlQueryPlan/test_metric_time_only__plan0.xml
  tests_metricflow/snapshots/test_metric_time_without_metrics.py/SqlQueryPlan/test_metric_time_quarter_alone__plan0.xml
  tests_metricflow/snapshots/test_metric_time_without_metrics.py/SqlQueryPlan/test_metric_time_with_other_dimensions__plan0.xml
  tests_metricflow/sql/optimizer/test_column_pruner.py
Labels: cla:yes, Skip Changelog

#1502 Replace `is_table` with `as_sql_table_node`
  metricflow/sql/render/sql_plan_renderer.py
  metricflow/sql/sql_plan.py
Labels: cla:yes, Skip Changelog

#1503 Support CTEs in the column pruner
  metricflow/plan_conversion/dataflow_to_sql.py
  metricflow/sql/optimizer/column_pruner.py
  metricflow/sql/optimizer/tag_required_column_aliases.py
  metricflow/sql/sql_plan.py
  tests_metricflow/snapshots/test_cte_column_pruner.py/str/test_multi_child_pruning__result.txt
  tests_metricflow/snapshots/test_cte_column_pruner.py/str/test_nested_pruning__result.txt
  tests_metricflow/snapshots/test_cte_column_pruner.py/str/test_no_pruning__result.txt
  tests_metricflow/snapshots/test_cte_column_pruner.py/str/test_simple_pruning__result.txt
  tests_metricflow/sql/optimizer/check_optimizer.py
  tests_metricflow/sql/optimizer/test_cte_column_pruner.py
Labels: cla:yes, Skip Changelog

#1504 Support CTEs in sub-query reducer
  metricflow/sql/optimizer/rewriting_sub_query_reducer.py
  metricflow/sql/optimizer/tag_required_column_aliases.py
  tests_metricflow/snapshots/test_cte_rewriting_sub_query_reducer.py/str/test_reduce_cte__result.txt
  tests_metricflow/snapshots/test_cte_rewriting_sub_query_reducer.py/str/test_reduce_cte_with_use_column_alias_in_group_bys__result.txt
  tests_metricflow/snapshots/test_rewriting_sub_query_reducer.py/SqlQueryPlan/test_reducing_join_statement__after_reducing.sql
  tests_metricflow/snapshots/test_rewriting_sub_query_reducer.py/SqlQueryPlan/test_reducing_join_statement__before_reducing.sql
  tests_metricflow/sql/optimizer/test_cte_rewriting_sub_query_reducer.py
  tests_metricflow/sql/optimizer/test_rewriting_sub_query_reducer.py
Labels: cla:yes, Skip Changelog

#1516 Update `SqlTableAliasSimplifier` to handle CTEs
  metricflow/sql/optimizer/table_alias_simplifier.py
  tests_metricflow/snapshots/test_cte_table_alias_simplifier.py/str/test_table_alias_no_simplification__result.txt
  tests_metricflow/snapshots/test_cte_table_alias_simplifier.py/str/test_table_alias_simplification__result.txt
  tests_metricflow/snapshots/test_table_alias_simplifier.py/SqlQueryPlan/test_table_alias_simplification__after_alias_simplification.sql
  tests_metricflow/snapshots/test_table_alias_simplifier.py/SqlQueryPlan/test_table_alias_simplification__before_alias_simplification.sql
  tests_metricflow/sql/optimizer/test_cte_table_alias_simplifier.py
  tests_metricflow/sql/optimizer/test_table_alias_simplifier.py
Labels: cla:yes, Skip Changelog

#1517 Split traversal component from `DataflowToSqlQueryPlanConverter`
  metricflow/dataflow/builder/node_data_set.py
  metricflow/plan_conversion/dataflow_to_sql.py
Labels: cla:yes, Skip Changelog

#1519 Move `DataflowPlanNodeVisitor` to a separate file
  metricflow/dataflow/dataflow_plan.py
  metricflow/dataflow/dataflow_plan_visitor.py
  metricflow/dataflow/nodes/add_generated_uuid.py
  metricflow/dataflow/nodes/aggregate_measures.py
  metricflow/dataflow/nodes/combine_aggregated_outputs.py
  metricflow/dataflow/nodes/compute_metrics.py
  metricflow/dataflow/nodes/constrain_time.py
  metricflow/dataflow/nodes/filter_elements.py
  metricflow/dataflow/nodes/join_conversion_events.py
  metricflow/dataflow/nodes/join_over_time.py
  metricflow/dataflow/nodes/join_to_base.py
  metricflow/dataflow/nodes/join_to_custom_granularity.py
  metricflow/dataflow/nodes/join_to_time_spine.py
  metricflow/dataflow/nodes/metric_time_transform.py
  metricflow/dataflow/nodes/min_max.py
  metricflow/dataflow/nodes/order_by_limit.py
  metricflow/dataflow/nodes/read_sql_source.py
  metricflow/dataflow/nodes/semi_additive_join.py
  metricflow/dataflow/nodes/where_filter.py
  metricflow/dataflow/nodes/window_reaggregation_node.py
  metricflow/dataflow/nodes/write_to_data_table.py
  metricflow/dataflow/nodes/write_to_table.py
  metricflow/dataflow/optimizer/predicate_pushdown_optimizer.py
  metricflow/dataflow/optimizer/source_scan/cm_branch_combiner.py
  metricflow/dataflow/optimizer/source_scan/source_scan_optimizer.py
  metricflow/execution/dataflow_to_execution.py
  metricflow/plan_conversion/dataflow_to_sql.py
  tests_metricflow/dataflow/optimizer/source_scan/test_source_scan_optimizer.py
Labels: cla:yes, Skip Changelog

#1520 Add a method to figure out common nodes in a dataflow plan
  metricflow-semantics/metricflow_semantics/dag/mf_dag.py
  metricflow-semantics/metricflow_semantics/mf_logging/pretty_print.py
  metricflow-semantics/metricflow_semantics/visitor.py
  metricflow-semantics/tests_metricflow_semantics/collection_helpers/test_pretty_print.py
  metricflow/dataflow/dataflow_plan.py
  metricflow/dataflow/dataflow_plan_analyzer.py
  metricflow/dataflow/dataflow_plan_visitor.py
  tests_metricflow/snapshots/test_common_dataflow_branches.py/str/test_shared_metric_query__result.txt
  tests_metricflow/sql/test_common_dataflow_branches.py
Labels: cla:yes, Skip Changelog

#1530 Cleanup: Remove `extraneous_linkable_specs`
  metricflow/dataflow/builder/dataflow_plan_builder.py
  metricflow/dataflow/builder/node_evaluator.py
  tests_metricflow/snapshots/test_predicate_pushdown_rendering.py/SqlQueryPlan/BigQuery/test_saved_query_with_metric_joins_and_filter__plan0.sql
  tests_metricflow/snapshots/test_predicate_pushdown_rendering.py/SqlQueryPlan/BigQuery/test_skipped_pushdown__plan0.sql
  tests_metricflow/snapshots/test_predicate_pushdown_rendering.py/SqlQueryPlan/Databricks/test_saved_query_with_metric_joins_and_filter__plan0.sql
  tests_metricflow/snapshots/test_predicate_pushdown_rendering.py/SqlQueryPlan/Databricks/test_skipped_pushdown__plan0.sql
  tests_metricflow/snapshots/test_predicate_pushdown_rendering.py/SqlQueryPlan/DuckDB/test_saved_query_with_metric_joins_and_filter__plan0.sql
  tests_metricflow/snapshots/test_predicate_pushdown_rendering.py/SqlQueryPlan/DuckDB/test_skipped_pushdown__plan0.sql
  tests_metricflow/snapshots/test_predicate_pushdown_rendering.py/SqlQueryPlan/Postgres/test_saved_query_with_metric_joins_and_filter__plan0.sql
  tests_metricflow/snapshots/test_predicate_pushdown_rendering.py/SqlQueryPlan/Postgres/test_skipped_pushdown__plan0.sql
  tests_metricflow/snapshots/test_predicate_pushdown_rendering.py/SqlQueryPlan/Redshift/test_saved_query_with_metric_joins_and_filter__plan0.sql
  tests_metricflow/snapshots/test_predicate_pushdown_rendering.py/SqlQueryPlan/Redshift/test_skipped_pushdown__plan0.sql
  tests_metricflow/snapshots/test_predicate_pushdown_rendering.py/SqlQueryPlan/Snowflake/test_saved_query_with_metric_joins_and_filter__plan0.sql
  tests_metricflow/snapshots/test_predicate_pushdown_rendering.py/SqlQueryPlan/Snowflake/test_skipped_pushdown__plan0.sql
  tests_metricflow/snapshots/test_predicate_pushdown_rendering.py/SqlQueryPlan/Trino/test_saved_query_with_metric_joins_and_filter__plan0.sql
  tests_metricflow/snapshots/test_predicate_pushdown_rendering.py/SqlQueryPlan/Trino/test_skipped_pushdown__plan0.sql
Labels: cla:yes, Skip Changelog

#1534 Handle invalid case for `ObjectBuilderNamingScheme.input_str()`
  metricflow-semantics/metricflow_semantics/naming/object_builder_str.py
  metricflow-semantics/tests_metricflow_semantics/naming/test_object_builder_naming_scheme.py
Labels: cla:yes, Skip Changelog
