Repository dbt-labs/metricflow, pull requests merged in 2024-05, with the labels that each got.

#1160 Map joinable metrics to entities instead of semantic models
  metricflow-semantics/metricflow_semantics/model/semantics/linkable_element.py
  metricflow-semantics/metricflow_semantics/model/semantics/linkable_spec_resolver.py
  metricflow-semantics/tests_metricflow_semantics/model/semantics/test_linkable_spec_resolver.py
  metricflow-semantics/tests_metricflow_semantics/snapshots/test_linkable_spec_resolver.py/list/test_linkable_element_set_as_spec_set__set0.txt
  metricflow-semantics/tests_metricflow_semantics/snapshots/test_linkable_spec_resolver.py/str/test_create_linkable_element_set_from_join_path__result0.txt
  metricflow-semantics/tests_metricflow_semantics/snapshots/test_linkable_spec_resolver.py/str/test_create_linkable_element_set_from_join_path_multi_hop__result0.txt
  metricflow-semantics/tests_metricflow_semantics/snapshots/test_semantic_model_container.py/str/test_linkable_elements_for_measure__result0.txt
  metricflow-semantics/tests_metricflow_semantics/snapshots/test_semantic_model_container.py/tuple/test_linkable_elements_for_no_metrics_query__result0.txt
Labels: cla:yes, Skip Changelog

#1163 Track 2 join paths for `LinkableMetrics`
  metricflow-semantics/metricflow_semantics/model/semantics/linkable_element.py
  metricflow-semantics/metricflow_semantics/model/semantics/linkable_spec_resolver.py
  metricflow-semantics/metricflow_semantics/specs/spec_set_transforms.py
  metricflow-semantics/tests_metricflow_semantics/model/semantics/test_linkable_element_set.py
  metricflow-semantics/tests_metricflow_semantics/model/test_where_filter_spec.py
  metricflow-semantics/tests_metricflow_semantics/snapshots/test_linkable_spec_resolver.py/str/test_create_linkable_element_set_from_join_path__result0.txt
  metricflow-semantics/tests_metricflow_semantics/snapshots/test_linkable_spec_resolver.py/str/test_create_linkable_element_set_from_join_path_multi_hop__result0.txt
  metricflow-semantics/tests_metricflow_semantics/snapshots/test_semantic_model_container.py/str/test_linkable_elements_for_measure__result0.txt
  metricflow/plan_conversion/node_processor.py
Labels: cla:yes, Skip Changelog

#1162 `LinkableMetric` tests
  metricflow-semantics/metricflow_semantics/model/semantics/linkable_element.py
  metricflow-semantics/metricflow_semantics/model/semantics/linkable_spec_resolver.py
  metricflow-semantics/metricflow_semantics/specs/spec_set_transforms.py
  metricflow-semantics/tests_metricflow_semantics/fixtures/manifest_fixtures.py
  metricflow-semantics/tests_metricflow_semantics/model/semantics/test_linkable_element_set.py
  metricflow-semantics/tests_metricflow_semantics/model/test_semantic_model_container.py
  metricflow-semantics/tests_metricflow_semantics/model/test_where_filter_spec.py
  metricflow-semantics/tests_metricflow_semantics/snapshots/test_linkable_spec_resolver.py/str/test_create_linkable_element_set_from_join_path__result0.txt
  metricflow-semantics/tests_metricflow_semantics/snapshots/test_linkable_spec_resolver.py/str/test_create_linkable_element_set_from_join_path_multi_hop__result0.txt
  metricflow-semantics/tests_metricflow_semantics/snapshots/test_semantic_model_container.py/str/test_linkable_elements_for_measure__result0.txt
  metricflow-semantics/tests_metricflow_semantics/snapshots/test_semantic_model_container.py/str/test_linkable_elements_for_measure_multi_hop_model__result0.txt
  metricflow/plan_conversion/node_processor.py
  tests_metricflow/fixtures/manifest_fixtures.py
  tests_metricflow/query_rendering/test_metric_filter_rendering.py
  tests_metricflow/snapshots/test_metric_filter_rendering.py/SqlQueryPlan/BigQuery/test_metric_filtered_by_itself__plan0.sql
  tests_metricflow/snapshots/test_metric_filter_rendering.py/SqlQueryPlan/BigQuery/test_metric_filtered_by_itself__plan0_optimized.sql
  tests_metricflow/snapshots/test_metric_filter_rendering.py/SqlQueryPlan/Databricks/test_metric_filtered_by_itself__plan0.sql
  tests_metricflow/snapshots/test_metric_filter_rendering.py/SqlQueryPlan/Databricks/test_metric_filtered_by_itself__plan0_optimized.sql
  tests_metricflow/snapshots/test_metric_filter_rendering.py/SqlQueryPlan/DuckDB/test_metric_filtered_by_itself__plan0.sql
  tests_metricflow/snapshots/test_metric_filter_rendering.py/SqlQueryPlan/DuckDB/test_metric_filtered_by_itself__plan0_optimized.sql
  tests_metricflow/snapshots/test_metric_filter_rendering.py/SqlQueryPlan/Postgres/test_metric_filtered_by_itself__plan0.sql
  tests_metricflow/snapshots/test_metric_filter_rendering.py/SqlQueryPlan/Postgres/test_metric_filtered_by_itself__plan0_optimized.sql
  tests_metricflow/snapshots/test_metric_filter_rendering.py/SqlQueryPlan/Redshift/test_metric_filtered_by_itself__plan0.sql
  tests_metricflow/snapshots/test_metric_filter_rendering.py/SqlQueryPlan/Redshift/test_metric_filtered_by_itself__plan0_optimized.sql
  tests_metricflow/snapshots/test_metric_filter_rendering.py/SqlQueryPlan/Snowflake/test_metric_filtered_by_itself__plan0.sql
  tests_metricflow/snapshots/test_metric_filter_rendering.py/SqlQueryPlan/Snowflake/test_metric_filtered_by_itself__plan0_optimized.sql
  tests_metricflow/snapshots/test_metric_filter_rendering.py/SqlQueryPlan/Trino/test_metric_filtered_by_itself__plan0.sql
  tests_metricflow/snapshots/test_metric_filter_rendering.py/SqlQueryPlan/Trino/test_metric_filtered_by_itself__plan0_optimized.sql
Labels: cla:yes, Skip Changelog

#1164 Use query parser to build group by metric source node
  metricflow-semantics/metricflow_semantics/query/query_parser.py
  metricflow-semantics/metricflow_semantics/specs/spec_classes.py
  metricflow-semantics/tests_metricflow_semantics/query/test_ambiguous_entity_path.py
  metricflow/dataflow/builder/dataflow_plan_builder.py
  metricflow/dataflow/builder/source_node.py
  metricflow/engine/metricflow_engine.py
  scripts/ci_tests/metricflow_package_test.py
  tests_metricflow/fixtures/manifest_fixtures.py
Labels: cla:yes, Skip Changelog

#1165 Track `metric_subquery_entity_links` on `GroupByMetricSpec` and `ElementPathKey`
  metricflow-semantics/metricflow_semantics/model/semantics/linkable_element.py
  metricflow-semantics/metricflow_semantics/query/query_parser.py
  metricflow-semantics/metricflow_semantics/specs/spec_classes.py
  metricflow-semantics/tests_metricflow_semantics/model/semantics/test_linkable_element_set.py
  metricflow-semantics/tests_metricflow_semantics/model/test_where_filter_spec.py
  metricflow-semantics/tests_metricflow_semantics/naming/conftest.py
  metricflow-semantics/tests_metricflow_semantics/naming/test_object_builder_naming_scheme.py
  metricflow-semantics/tests_metricflow_semantics/snapshots/test_linkable_spec_resolver.py/list/test_linkable_element_set_as_spec_set__set0.txt
  metricflow-semantics/tests_metricflow_semantics/snapshots/test_semantic_model_container.py/tuple/test_linkable_elements_for_no_metrics_query__result0.txt
  metricflow-semantics/tests_metricflow_semantics/specs/patterns/test_entity_link_pattern.py
  metricflow-semantics/tests_metricflow_semantics/specs/patterns/test_typed_patterns.py
  metricflow-semantics/tests_metricflow_semantics/test_specs.py
  metricflow/plan_conversion/dataflow_to_sql.py
  metricflow/plan_conversion/instance_converters.py
Labels: cla:yes, Skip Changelog

#1166 Handle both join paths in `GroupByMetricPattern`
  metricflow-semantics/metricflow_semantics/model/semantics/linkable_element.py
  metricflow-semantics/metricflow_semantics/specs/patterns/entity_link_pattern.py
  metricflow-semantics/metricflow_semantics/specs/patterns/typed_patterns.py
  metricflow-semantics/metricflow_semantics/specs/spec_classes.py
  metricflow-semantics/tests_metricflow_semantics/model/semantics/test_linkable_element_set.py
  metricflow-semantics/tests_metricflow_semantics/model/test_where_filter_spec.py
  metricflow-semantics/tests_metricflow_semantics/naming/conftest.py
  metricflow-semantics/tests_metricflow_semantics/naming/test_object_builder_naming_scheme.py
  metricflow-semantics/tests_metricflow_semantics/specs/patterns/test_entity_link_pattern.py
  metricflow-semantics/tests_metricflow_semantics/specs/patterns/test_typed_patterns.py
  metricflow-semantics/tests_metricflow_semantics/test_specs.py
  metricflow/plan_conversion/dataflow_to_sql.py
  tests_metricflow/snapshots/test_dataflow_plan_builder.py/DataflowPlan/test_metric_in_metric_where_filter__dfp_0.xml
  tests_metricflow/snapshots/test_dataflow_plan_builder.py/DataflowPlan/test_metric_in_query_where_filter__dfp_0.xml
Labels: cla:yes, Skip Changelog

#1167 Store entity links on `MetricSubqueryJoinPathElement`
  metricflow-semantics/metricflow_semantics/model/semantics/linkable_element.py
  metricflow-semantics/metricflow_semantics/model/semantics/linkable_spec_resolver.py
  metricflow-semantics/tests_metricflow_semantics/model/semantics/test_linkable_element_set.py
  metricflow-semantics/tests_metricflow_semantics/model/test_where_filter_spec.py
  metricflow-semantics/tests_metricflow_semantics/snapshots/test_linkable_spec_resolver.py/list/test_linkable_element_set_as_spec_set__set0.txt
  metricflow-semantics/tests_metricflow_semantics/snapshots/test_linkable_spec_resolver.py/str/test_create_linkable_element_set_from_join_path__result0.txt
  metricflow-semantics/tests_metricflow_semantics/snapshots/test_linkable_spec_resolver.py/str/test_create_linkable_element_set_from_join_path_multi_hop__result0.txt
  metricflow-semantics/tests_metricflow_semantics/snapshots/test_semantic_model_container.py/str/test_linkable_elements_for_measure__result0.txt
  metricflow-semantics/tests_metricflow_semantics/snapshots/test_semantic_model_container.py/tuple/test_linkable_elements_for_no_metrics_query__result0.txt
Labels: cla:yes, Skip Changelog

#1168 Remove metrics that must be queried with `metric_time` from linkable metric options
  metricflow-semantics/metricflow_semantics/model/semantics/linkable_spec_resolver.py
  metricflow-semantics/tests_metricflow_semantics/snapshots/test_linkable_spec_resolver.py/list/test_linkable_element_set_as_spec_set__set0.txt
  metricflow-semantics/tests_metricflow_semantics/snapshots/test_linkable_spec_resolver.py/str/test_create_linkable_element_set_from_join_path__result0.txt
  metricflow-semantics/tests_metricflow_semantics/snapshots/test_linkable_spec_resolver.py/str/test_create_linkable_element_set_from_join_path_multi_hop__result0.txt
  metricflow-semantics/tests_metricflow_semantics/snapshots/test_semantic_model_container.py/str/test_linkable_elements_for_measure__result0.txt
  metricflow-semantics/tests_metricflow_semantics/snapshots/test_semantic_model_container.py/tuple/test_linkable_elements_for_no_metrics_query__result0.txt
Labels: cla:yes, Skip Changelog

#1169 Update DFP join logic to account for group by metric source nodes
  metricflow-semantics/metricflow_semantics/specs/linkable_spec_set.py
  metricflow-semantics/metricflow_semantics/specs/spec_classes.py
  metricflow/dataflow/builder/dataflow_plan_builder.py
  metricflow/dataflow/builder/node_evaluator.py
  metricflow/dataflow/dataflow_plan.py
  metricflow/dataflow/nodes/compute_metrics.py
  metricflow/dataflow/optimizer/source_scan/cm_branch_combiner.py
  metricflow/dataflow/optimizer/source_scan/source_scan_optimizer.py
  metricflow/dataset/sql_dataset.py
  metricflow/plan_conversion/dataflow_to_sql.py
  metricflow/plan_conversion/node_processor.py
  metricflow/validation/dataflow_join_validator.py
  tests_metricflow/plan_conversion/test_dataflow_to_sql_plan.py
Labels: cla:yes, Skip Changelog

#1172 Dedupe `LinkableMetrics` in snapshots
  metricflow-semantics/metricflow_semantics/test_helpers/snapshot_helpers.py
  metricflow-semantics/tests_metricflow_semantics/snapshots/test_linkable_spec_resolver.py/str/test_create_linkable_element_set_from_join_path__result0.txt
  metricflow-semantics/tests_metricflow_semantics/snapshots/test_linkable_spec_resolver.py/str/test_create_linkable_element_set_from_join_path_multi_hop__result0.txt
  metricflow-semantics/tests_metricflow_semantics/snapshots/test_semantic_model_container.py/str/test_linkable_elements_for_measure__result0.txt
  metricflow-semantics/tests_metricflow_semantics/snapshots/test_semantic_model_container.py/str/test_linkable_elements_for_measure_multi_hop_model__result0.txt
Labels: cla:yes, Skip Changelog

#1173 Test that all available single-hop metrics don't error
  tests_metricflow/dataflow/builder/test_dataflow_plan_builder.py
Labels: cla:yes, Skip Changelog

#1175 Add support for set type collections in the pretty-printer
  metricflow-semantics/metricflow_semantics/mf_logging/pretty_print.py
  metricflow-semantics/tests_metricflow_semantics/snapshots/test_matching_item_for_filters.py/GroupByItemResolution/test_ambiguous_metric_time_in_query_filter__accumulate_last_2_months_metric__result.txt
  metricflow-semantics/tests_metricflow_semantics/snapshots/test_matching_item_for_filters.py/GroupByItemResolution/test_ambiguous_metric_time_in_query_filter__derived_metric_with_different_parent_time_grains__result.txt
  metricflow-semantics/tests_metricflow_semantics/snapshots/test_matching_item_for_filters.py/GroupByItemResolution/test_ambiguous_metric_time_in_query_filter__derived_metric_with_same_parent_time_grains__result.txt
  metricflow-semantics/tests_metricflow_semantics/snapshots/test_matching_item_for_filters.py/GroupByItemResolution/test_ambiguous_metric_time_in_query_filter__metrics_with_different_time_grains__result.txt
  metricflow-semantics/tests_metricflow_semantics/snapshots/test_matching_item_for_filters.py/GroupByItemResolution/test_ambiguous_metric_time_in_query_filter__metrics_with_same_time_grains__result.txt
  metricflow-semantics/tests_metricflow_semantics/snapshots/test_matching_item_for_filters.py/GroupByItemResolution/test_ambiguous_metric_time_in_query_filter__no_metrics__result.txt
  metricflow-semantics/tests_metricflow_semantics/snapshots/test_matching_item_for_filters.py/GroupByItemResolution/test_ambiguous_metric_time_in_query_filter__simple_metric__result.txt
  metricflow-semantics/tests_metricflow_semantics/snapshots/test_spec_lookup.py/str/test_filter_resolution_for_derived_metrics_with_common_filtered_metric__result.txt
  metricflow-semantics/tests_metricflow_semantics/snapshots/test_spec_lookup.py/str/test_filter_resolution_for_invalid_metric_filter__result.txt
  metricflow-semantics/tests_metricflow_semantics/snapshots/test_spec_lookup.py/str/test_filter_resolution_for_invalid_metric_input_filter__result.txt
  metricflow-semantics/tests_metricflow_semantics/snapshots/test_spec_lookup.py/str/test_filter_resolution_for_valid_metric_filter__result.txt
  metricflow-semantics/tests_metricflow_semantics/snapshots/test_spec_lookup.py/str/test_filter_resolution_for_valid_metric_input_filter__result.txt
  metricflow-semantics/tests_metricflow_semantics/snapshots/test_spec_lookup.py/str/test_filter_spec_resolution__accumulate_last_2_months_metric__result.txt
  metricflow-semantics/tests_metricflow_semantics/snapshots/test_spec_lookup.py/str/test_filter_spec_resolution__derived_metric_with_different_parent_time_grains__result.txt
  metricflow-semantics/tests_metricflow_semantics/snapshots/test_spec_lookup.py/str/test_filter_spec_resolution__derived_metric_with_same_parent_time_grains__result.txt
  metricflow-semantics/tests_metricflow_semantics/snapshots/test_spec_lookup.py/str/test_filter_spec_resolution__metrics_with_different_time_grains__result.txt
  metricflow-semantics/tests_metricflow_semantics/snapshots/test_spec_lookup.py/str/test_filter_spec_resolution__metrics_with_same_time_grains__result.txt
  metricflow-semantics/tests_metricflow_semantics/snapshots/test_spec_lookup.py/str/test_filter_spec_resolution__simple_metric__result.txt
Labels: Skip Changelog

#1176 Make LinkabelElementSet non-optional in FilterSpecResolution
  metricflow-semantics/metricflow_semantics/query/group_by_item/filter_spec_resolution/filter_spec_lookup.py
Labels: cla:yes, Skip Changelog

#1177 Revert "Move `_path_key_to_spec` to `ElementPathKey`."
  metricflow-semantics/metricflow_semantics/model/semantics/linkable_element.py
  metricflow-semantics/metricflow_semantics/model/semantics/linkable_element_set.py
  tests_metricflow/dataflow/builder/test_dataflow_plan_builder.py
Labels: cla:yes, Skip Changelog

#1178 Make linkable elements available in FilterSpecResolutionLookup
  metricflow-semantics/metricflow_semantics/model/semantics/linkable_element_set.py
  metricflow-semantics/metricflow_semantics/query/group_by_item/filter_spec_resolution/filter_spec_lookup.py
  metricflow-semantics/metricflow_semantics/specs/spec_classes.py
  metricflow-semantics/tests_metricflow_semantics/model/semantics/test_linkable_element_set.py
Labels: cla:yes, Skip Changelog

#1179 Push resolved linkable elements through to WhereFilterSpec
  metricflow-semantics/metricflow_semantics/model/semantics/linkable_element.py
  metricflow-semantics/metricflow_semantics/specs/rendered_spec_tracker.py
  metricflow-semantics/metricflow_semantics/specs/spec_classes.py
  metricflow-semantics/metricflow_semantics/specs/where_filter_dimension.py
  metricflow-semantics/metricflow_semantics/specs/where_filter_entity.py
  metricflow-semantics/metricflow_semantics/specs/where_filter_metric.py
  metricflow-semantics/metricflow_semantics/specs/where_filter_time_dimension.py
  metricflow-semantics/metricflow_semantics/specs/where_filter_transform.py
  tests_metricflow/plan_conversion/test_dataflow_to_sql_plan.py
  tests_metricflow/snapshots/test_dataflow_plan_builder.py/DataflowPlan/test_distinct_values_plan__dfp_0.xml
  tests_metricflow/snapshots/test_dataflow_plan_builder.py/DataflowPlan/test_distinct_values_plan_with_join__dfp_0.xml
  tests_metricflow/snapshots/test_dataflow_plan_builder.py/DataflowPlan/test_join_to_time_spine_with_filters__dfp_0.xml
  tests_metricflow/snapshots/test_dataflow_plan_builder.py/DataflowPlan/test_measure_constraint_plan__dfp_0.xml
  tests_metricflow/snapshots/test_dataflow_plan_builder.py/DataflowPlan/test_measure_constraint_with_reused_measure_plan__dfp_0.xml
  tests_metricflow/snapshots/test_dataflow_plan_builder.py/DataflowPlan/test_offset_to_grain_metric_filter_and_query_have_different_granularities__dfp_0.xml
  tests_metricflow/snapshots/test_dataflow_plan_builder.py/DataflowPlan/test_offset_window_metric_filter_and_query_have_different_granularities__dfp_0.xml
  tests_metricflow/snapshots/test_dataflow_plan_builder.py/DataflowPlan/test_where_constrained_plan__dfp_0.xml
  tests_metricflow/snapshots/test_dataflow_plan_builder.py/DataflowPlan/test_where_constrained_plan_time_dimension__dfp_0.xml
  tests_metricflow/snapshots/test_dataflow_plan_builder.py/DataflowPlan/test_where_constrained_with_common_linkable_plan__dfp_0.xml
  tests_metricflow/snapshots/test_source_scan_optimizer.py/DataflowPlan/test_constrained_metric_not_combined__dfp_0.xml
  tests_metricflow/snapshots/test_source_scan_optimizer.py/DataflowPlan/test_constrained_metric_not_combined__dfpo_0.xml
Labels: cla:yes, Skip Changelog

#1182 Fix pretty print bug for sets containing enums
  metricflow-semantics/metricflow_semantics/mf_logging/pretty_print.py
  metricflow-semantics/tests_metricflow_semantics/snapshots/test_matching_item_for_filters.py/GroupByItemResolution/test_ambiguous_metric_time_in_query_filter__accumulate_last_2_months_metric__result.txt
  metricflow-semantics/tests_metricflow_semantics/snapshots/test_matching_item_for_filters.py/GroupByItemResolution/test_ambiguous_metric_time_in_query_filter__derived_metric_with_different_parent_time_grains__result.txt
  metricflow-semantics/tests_metricflow_semantics/snapshots/test_matching_item_for_filters.py/GroupByItemResolution/test_ambiguous_metric_time_in_query_filter__derived_metric_with_same_parent_time_grains__result.txt
  metricflow-semantics/tests_metricflow_semantics/snapshots/test_matching_item_for_filters.py/GroupByItemResolution/test_ambiguous_metric_time_in_query_filter__metrics_with_different_time_grains__result.txt
  metricflow-semantics/tests_metricflow_semantics/snapshots/test_matching_item_for_filters.py/GroupByItemResolution/test_ambiguous_metric_time_in_query_filter__metrics_with_same_time_grains__result.txt
  metricflow-semantics/tests_metricflow_semantics/snapshots/test_matching_item_for_filters.py/GroupByItemResolution/test_ambiguous_metric_time_in_query_filter__no_metrics__result.txt
  metricflow-semantics/tests_metricflow_semantics/snapshots/test_matching_item_for_filters.py/GroupByItemResolution/test_ambiguous_metric_time_in_query_filter__simple_metric__result.txt
  metricflow-semantics/tests_metricflow_semantics/snapshots/test_spec_lookup.py/str/test_filter_resolution_for_derived_metrics_with_common_filtered_metric__result.txt
  metricflow-semantics/tests_metricflow_semantics/snapshots/test_spec_lookup.py/str/test_filter_resolution_for_invalid_metric_filter__result.txt
  metricflow-semantics/tests_metricflow_semantics/snapshots/test_spec_lookup.py/str/test_filter_resolution_for_invalid_metric_input_filter__result.txt
  metricflow-semantics/tests_metricflow_semantics/snapshots/test_spec_lookup.py/str/test_filter_resolution_for_valid_metric_filter__result.txt
  metricflow-semantics/tests_metricflow_semantics/snapshots/test_spec_lookup.py/str/test_filter_resolution_for_valid_metric_input_filter__result.txt
  metricflow-semantics/tests_metricflow_semantics/snapshots/test_spec_lookup.py/str/test_filter_spec_resolution__accumulate_last_2_months_metric__result.txt
  metricflow-semantics/tests_metricflow_semantics/snapshots/test_spec_lookup.py/str/test_filter_spec_resolution__derived_metric_with_different_parent_time_grains__result.txt
  metricflow-semantics/tests_metricflow_semantics/snapshots/test_spec_lookup.py/str/test_filter_spec_resolution__derived_metric_with_same_parent_time_grains__result.txt
  metricflow-semantics/tests_metricflow_semantics/snapshots/test_spec_lookup.py/str/test_filter_spec_resolution__metrics_with_different_time_grains__result.txt
  metricflow-semantics/tests_metricflow_semantics/snapshots/test_spec_lookup.py/str/test_filter_spec_resolution__metrics_with_same_time_grains__result.txt
  metricflow-semantics/tests_metricflow_semantics/snapshots/test_spec_lookup.py/str/test_filter_spec_resolution__simple_metric__result.txt
  tests_metricflow/snapshots/test_dataflow_plan_builder.py/DataflowPlan/test_distinct_values_plan__dfp_0.xml
  tests_metricflow/snapshots/test_dataflow_plan_builder.py/DataflowPlan/test_distinct_values_plan_with_join__dfp_0.xml
  tests_metricflow/snapshots/test_dataflow_plan_builder.py/DataflowPlan/test_join_to_time_spine_with_filters__dfp_0.xml
  tests_metricflow/snapshots/test_dataflow_plan_builder.py/DataflowPlan/test_measure_constraint_plan__dfp_0.xml
  tests_metricflow/snapshots/test_dataflow_plan_builder.py/DataflowPlan/test_measure_constraint_with_reused_measure_plan__dfp_0.xml
  tests_metricflow/snapshots/test_dataflow_plan_builder.py/DataflowPlan/test_offset_to_grain_metric_filter_and_query_have_different_granularities__dfp_0.xml
  tests_metricflow/snapshots/test_dataflow_plan_builder.py/DataflowPlan/test_offset_window_metric_filter_and_query_have_different_granularities__dfp_0.xml
  tests_metricflow/snapshots/test_dataflow_plan_builder.py/DataflowPlan/test_where_constrained_plan__dfp_0.xml
  tests_metricflow/snapshots/test_dataflow_plan_builder.py/DataflowPlan/test_where_constrained_plan_time_dimension__dfp_0.xml
  tests_metricflow/snapshots/test_dataflow_plan_builder.py/DataflowPlan/test_where_constrained_with_common_linkable_plan__dfp_0.xml
  tests_metricflow/snapshots/test_source_scan_optimizer.py/DataflowPlan/test_constrained_metric_not_combined__dfp_0.xml
  tests_metricflow/snapshots/test_source_scan_optimizer.py/DataflowPlan/test_constrained_metric_not_combined__dfpo_0.xml
Labels: cla:yes, Skip Changelog

#1180 Track `derived_from_semantic_models` properly for `LinkableMetrics`
  metricflow-semantics/metricflow_semantics/model/semantics/linkable_element.py
  metricflow-semantics/metricflow_semantics/model/semantics/linkable_spec_resolver.py
  metricflow-semantics/metricflow_semantics/specs/spec_classes.py
  metricflow-semantics/tests_metricflow_semantics/model/semantics/test_linkable_element_set.py
  metricflow-semantics/tests_metricflow_semantics/model/test_where_filter_spec.py
Labels: cla:yes, Skip Changelog

#1187 Fix path key conversion bug for `LinkableMetrics`
  metricflow-semantics/metricflow_semantics/model/semantics/linkable_element.py
  metricflow-semantics/tests_metricflow_semantics/model/semantics/test_linkable_element_set.py
  metricflow-semantics/tests_metricflow_semantics/model/test_where_filter_spec.py
Labels: cla:yes, Skip Changelog

#1192 Update snapshot-diff error-messages to be more compact
  metricflow-semantics/metricflow_semantics/test_helpers/snapshot_helpers.py
Labels: cla:yes, Skip Changelog

#1184 Finalize V1 LinkableMetric options
  metricflow-semantics/metricflow_semantics/model/semantics/linkable_spec_resolver.py
  metricflow-semantics/tests_metricflow_semantics/snapshots/test_linkable_spec_resolver.py/list/test_linkable_element_set_as_spec_set__set0.txt
  metricflow-semantics/tests_metricflow_semantics/snapshots/test_linkable_spec_resolver.py/str/test_create_linkable_element_set_from_join_path__result0.txt
  metricflow-semantics/tests_metricflow_semantics/snapshots/test_linkable_spec_resolver.py/str/test_create_linkable_element_set_from_join_path_multi_hop__result0.txt
  metricflow-semantics/tests_metricflow_semantics/snapshots/test_semantic_model_container.py/str/test_linkable_elements_for_measure__result0.txt
  metricflow-semantics/tests_metricflow_semantics/snapshots/test_semantic_model_container.py/str/test_linkable_elements_for_measure_multi_hop_model__result0.txt
  metricflow/dataflow/builder/dataflow_plan_builder.py
  tests_metricflow/dataflow/builder/test_dataflow_plan_builder.py
Labels: cla:yes, Skip Changelog

#1194 Add tests for metric filters using local entity prefix
  tests_metricflow/integration/test_cases/itest_metrics.yaml
  tests_metricflow/query_rendering/test_metric_filter_rendering.py
  tests_metricflow/snapshots/test_metric_filter_rendering.py/SqlQueryPlan/BigQuery/test_group_by_has_local_entity_prefix__plan0.sql
  tests_metricflow/snapshots/test_metric_filter_rendering.py/SqlQueryPlan/BigQuery/test_group_by_has_local_entity_prefix__plan0_optimized.sql
  tests_metricflow/snapshots/test_metric_filter_rendering.py/SqlQueryPlan/Databricks/test_group_by_has_local_entity_prefix__plan0.sql
  tests_metricflow/snapshots/test_metric_filter_rendering.py/SqlQueryPlan/Databricks/test_group_by_has_local_entity_prefix__plan0_optimized.sql
  tests_metricflow/snapshots/test_metric_filter_rendering.py/SqlQueryPlan/DuckDB/test_group_by_has_local_entity_prefix__plan0.sql
  tests_metricflow/snapshots/test_metric_filter_rendering.py/SqlQueryPlan/DuckDB/test_group_by_has_local_entity_prefix__plan0_optimized.sql
  tests_metricflow/snapshots/test_metric_filter_rendering.py/SqlQueryPlan/Postgres/test_group_by_has_local_entity_prefix__plan0.sql
  tests_metricflow/snapshots/test_metric_filter_rendering.py/SqlQueryPlan/Postgres/test_group_by_has_local_entity_prefix__plan0_optimized.sql
  tests_metricflow/snapshots/test_metric_filter_rendering.py/SqlQueryPlan/Redshift/test_group_by_has_local_entity_prefix__plan0.sql
  tests_metricflow/snapshots/test_metric_filter_rendering.py/SqlQueryPlan/Redshift/test_group_by_has_local_entity_prefix__plan0_optimized.sql
  tests_metricflow/snapshots/test_metric_filter_rendering.py/SqlQueryPlan/Snowflake/test_group_by_has_local_entity_prefix__plan0.sql
  tests_metricflow/snapshots/test_metric_filter_rendering.py/SqlQueryPlan/Snowflake/test_group_by_has_local_entity_prefix__plan0_optimized.sql
  tests_metricflow/snapshots/test_metric_filter_rendering.py/SqlQueryPlan/Trino/test_group_by_has_local_entity_prefix__plan0.sql
  tests_metricflow/snapshots/test_metric_filter_rendering.py/SqlQueryPlan/Trino/test_group_by_has_local_entity_prefix__plan0_optimized.sql
Labels: cla:yes, Skip Changelog

#1195 Test rendering for conversion metric filter
  tests_metricflow/query_rendering/test_metric_filter_rendering.py
  tests_metricflow/snapshots/test_metric_filter_rendering.py/SqlQueryPlan/BigQuery/test_filter_with_conversion_metric__plan0.sql
  tests_metricflow/snapshots/test_metric_filter_rendering.py/SqlQueryPlan/BigQuery/test_filter_with_conversion_metric__plan0_optimized.sql
  tests_metricflow/snapshots/test_metric_filter_rendering.py/SqlQueryPlan/BigQuery/test_group_by_has_local_entity_prefix2__plan0.sql
  tests_metricflow/snapshots/test_metric_filter_rendering.py/SqlQueryPlan/BigQuery/test_group_by_has_local_entity_prefix2__plan0_optimized.sql
  tests_metricflow/snapshots/test_metric_filter_rendering.py/SqlQueryPlan/Databricks/test_filter_with_conversion_metric__plan0.sql
  tests_metricflow/snapshots/test_metric_filter_rendering.py/SqlQueryPlan/Databricks/test_filter_with_conversion_metric__plan0_optimized.sql
  tests_metricflow/snapshots/test_metric_filter_rendering.py/SqlQueryPlan/Databricks/test_group_by_has_local_entity_prefix2__plan0.sql
  tests_metricflow/snapshots/test_metric_filter_rendering.py/SqlQueryPlan/Databricks/test_group_by_has_local_entity_prefix2__plan0_optimized.sql
  tests_metricflow/snapshots/test_metric_filter_rendering.py/SqlQueryPlan/DuckDB/test_filter_with_conversion_metric__plan0.sql
  tests_metricflow/snapshots/test_metric_filter_rendering.py/SqlQueryPlan/DuckDB/test_filter_with_conversion_metric__plan0_optimized.sql
  tests_metricflow/snapshots/test_metric_filter_rendering.py/SqlQueryPlan/Postgres/test_filter_with_conversion_metric__plan0.sql
  tests_metricflow/snapshots/test_metric_filter_rendering.py/SqlQueryPlan/Postgres/test_filter_with_conversion_metric__plan0_optimized.sql
  tests_metricflow/snapshots/test_metric_filter_rendering.py/SqlQueryPlan/Postgres/test_group_by_has_local_entity_prefix2__plan0.sql
  tests_metricflow/snapshots/test_metric_filter_rendering.py/SqlQueryPlan/Postgres/test_group_by_has_local_entity_prefix2__plan0_optimized.sql
  tests_metricflow/snapshots/test_metric_filter_rendering.py/SqlQueryPlan/Redshift/test_filter_with_conversion_metric__plan0.sql
  tests_metricflow/snapshots/test_metric_filter_rendering.py/SqlQueryPlan/Redshift/test_filter_with_conversion_metric__plan0_optimized.sql
  tests_metricflow/snapshots/test_metric_filter_rendering.py/SqlQueryPlan/Redshift/test_group_by_has_local_entity_prefix2__plan0.sql
  tests_metricflow/snapshots/test_metric_filter_rendering.py/SqlQueryPlan/Redshift/test_group_by_has_local_entity_prefix2__plan0_optimized.sql
  tests_metricflow/snapshots/test_metric_filter_rendering.py/SqlQueryPlan/Snowflake/test_filter_with_conversion_metric__plan0.sql
  tests_metricflow/snapshots/test_metric_filter_rendering.py/SqlQueryPlan/Snowflake/test_filter_with_conversion_metric__plan0_optimized.sql
  tests_metricflow/snapshots/test_metric_filter_rendering.py/SqlQueryPlan/Snowflake/test_group_by_has_local_entity_prefix2__plan0.sql
  tests_metricflow/snapshots/test_metric_filter_rendering.py/SqlQueryPlan/Snowflake/test_group_by_has_local_entity_prefix2__plan0_optimized.sql
  tests_metricflow/snapshots/test_metric_filter_rendering.py/SqlQueryPlan/Trino/test_filter_with_conversion_metric__plan0.sql
  tests_metricflow/snapshots/test_metric_filter_rendering.py/SqlQueryPlan/Trino/test_filter_with_conversion_metric__plan0_optimized.sql
  tests_metricflow/snapshots/test_metric_filter_rendering.py/SqlQueryPlan/Trino/test_group_by_has_local_entity_prefix2__plan0.sql
  tests_metricflow/snapshots/test_metric_filter_rendering.py/SqlQueryPlan/Trino/test_group_by_has_local_entity_prefix2__plan0_optimized.sql
Labels: cla:yes, Skip Changelog

#1198 Remove error that users are running into
  metricflow-semantics/metricflow_semantics/model/semantics/linkable_element.py
Labels: cla:yes, Skip Changelog

#1200 Don't allow LinkableMetrics for case when entity reference is in entity links
  metricflow-semantics/metricflow_semantics/model/semantics/linkable_spec_resolver.py
Labels: cla:yes, Skip Changelog

#1201 Update `SemanticModelJoinPath` to Include Left-Most Semantic Model
  metricflow-semantics/metricflow_semantics/model/semantic_model_derivation.py
  metricflow-semantics/metricflow_semantics/model/semantics/linkable_element.py
  metricflow-semantics/metricflow_semantics/model/semantics/linkable_spec_resolver.py
  metricflow-semantics/metricflow_semantics/model/semantics/semantic_model_lookup.py
  metricflow-semantics/metricflow_semantics/test_helpers/snapshot_helpers.py
  metricflow-semantics/metricflow_semantics/workarounds/__init__.py
  metricflow-semantics/metricflow_semantics/workarounds/reference.py
  metricflow-semantics/tests_metricflow_semantics/model/semantics/test_linkable_element_set.py
  metricflow-semantics/tests_metricflow_semantics/model/semantics/test_linkable_spec_resolver.py
  metricflow-semantics/tests_metricflow_semantics/model/test_where_filter_spec.py
  metricflow-semantics/tests_metricflow_semantics/snapshots/test_linkable_spec_resolver.py/str/test_all_properties__result0.txt
  metricflow-semantics/tests_metricflow_semantics/snapshots/test_linkable_spec_resolver.py/str/test_create_linkable_element_set_from_join_path__result0.txt
  metricflow-semantics/tests_metricflow_semantics/snapshots/test_linkable_spec_resolver.py/str/test_create_linkable_element_set_from_join_path_multi_hop__result0.txt
  metricflow-semantics/tests_metricflow_semantics/snapshots/test_linkable_spec_resolver.py/str/test_cyclic_join_manifest__result0.txt
  metricflow-semantics/tests_metricflow_semantics/snapshots/test_linkable_spec_resolver.py/str/test_metric_time_property_for_cumulative_metric__result0.txt
  metricflow-semantics/tests_metricflow_semantics/snapshots/test_linkable_spec_resolver.py/str/test_metric_time_property_for_derived_metrics__result0.txt
  metricflow-semantics/tests_metricflow_semantics/snapshots/test_linkable_spec_resolver.py/str/test_one_property__result0.txt
  metricflow-semantics/tests_metricflow_semantics/snapshots/test_matching_item_for_filters.py/GroupByItemResolution/test_ambiguous_metric_time_in_query_filter__accumulate_last_2_months_metric__result.txt
  metricflow-semantics/tests_metricflow_semantics/snapshots/test_matching_item_for_filters.py/GroupByItemResolution/test_ambiguous_metric_time_in_query_filter__derived_metric_with_different_parent_time_grains__result.txt
  metricflow-semantics/tests_metricflow_semantics/snapshots/test_matching_item_for_filters.py/GroupByItemResolution/test_ambiguous_metric_time_in_query_filter__derived_metric_with_same_parent_time_grains__result.txt
  metricflow-semantics/tests_metricflow_semantics/snapshots/test_matching_item_for_filters.py/GroupByItemResolution/test_ambiguous_metric_time_in_query_filter__metrics_with_different_time_grains__result.txt
  metricflow-semantics/tests_metricflow_semantics/snapshots/test_matching_item_for_filters.py/GroupByItemResolution/test_ambiguous_metric_time_in_query_filter__metrics_with_same_time_grains__result.txt
  metricflow-semantics/tests_metricflow_semantics/snapshots/test_matching_item_for_filters.py/GroupByItemResolution/test_ambiguous_metric_time_in_query_filter__no_metrics__result.txt
  metricflow-semantics/tests_metricflow_semantics/snapshots/test_matching_item_for_filters.py/GroupByItemResolution/test_ambiguous_metric_time_in_query_filter__simple_metric__result.txt
  metricflow-semantics/tests_metricflow_semantics/snapshots/test_semantic_model_container.py/str/test_linkable_elements_for_measure__result0.txt
  metricflow-semantics/tests_metricflow_semantics/snapshots/test_semantic_model_container.py/str/test_linkable_elements_for_measure_multi_hop_model__result0.txt
  metricflow-semantics/tests_metricflow_semantics/snapshots/test_semantic_model_container.py/str/test_linkable_elements_for_metrics__result0.txt
  metricflow-semantics/tests_metricflow_semantics/snapshots/test_semantic_model_container.py/str/test_linkable_set_for_common_dimensions_in_different_models__result0.txt
  metricflow-semantics/tests_metricflow_semantics/snapshots/test_spec_lookup.py/str/test_filter_resolution_for_derived_metrics_with_common_filtered_metric__result.txt
  metricflow-semantics/tests_metricflow_semantics/snapshots/test_spec_lookup.py/str/test_filter_resolution_for_invalid_metric_filter__result.txt
  metricflow-semantics/tests_metricflow_semantics/snapshots/test_spec_lookup.py/str/test_filter_resolution_for_invalid_metric_input_filter__result.txt
  metricflow-semantics/tests_metricflow_semantics/snapshots/test_spec_lookup.py/str/test_filter_resolution_for_valid_metric_filter__result.txt
  metricflow-semantics/tests_metricflow_semantics/snapshots/test_spec_lookup.py/str/test_filter_resolution_for_valid_metric_input_filter__result.txt
  metricflow-semantics/tests_metricflow_semantics/snapshots/test_spec_lookup.py/str/test_filter_spec_resolution__accumulate_last_2_months_metric__result.txt
  metricflow-semantics/tests_metricflow_semantics/snapshots/test_spec_lookup.py/str/test_filter_spec_resolution__derived_metric_with_different_parent_time_grains__result.txt
  metricflow-semantics/tests_metricflow_semantics/snapshots/test_spec_lookup.py/str/test_filter_spec_resolution__derived_metric_with_same_parent_time_grains__result.txt
  metricflow-semantics/tests_metricflow_semantics/snapshots/test_spec_lookup.py/str/test_filter_spec_resolution__metrics_with_different_time_grains__result.txt
  metricflow-semantics/tests_metricflow_semantics/snapshots/test_spec_lookup.py/str/test_filter_spec_resolution__metrics_with_same_time_grains__result.txt
  metricflow-semantics/tests_metricflow_semantics/snapshots/test_spec_lookup.py/str/test_filter_spec_resolution__simple_metric__result.txt
  tests_metricflow/plan_conversion/test_dataflow_to_sql_plan.py
  tests_metricflow/semantics/__init__.py
  tests_metricflow/snapshots/test_dataflow_plan_builder.py/DataflowPlan/test_distinct_values_plan__dfp_0.xml
  tests_metricflow/snapshots/test_dataflow_plan_builder.py/DataflowPlan/test_distinct_values_plan_with_join__dfp_0.xml
  tests_metricflow/snapshots/test_dataflow_plan_builder.py/DataflowPlan/test_join_to_time_spine_with_filters__dfp_0.xml
  tests_metricflow/snapshots/test_dataflow_plan_builder.py/DataflowPlan/test_measure_constraint_plan__dfp_0.xml
  tests_metricflow/snapshots/test_dataflow_plan_builder.py/DataflowPlan/test_measure_constraint_with_reused_measure_plan__dfp_0.xml
  tests_metricflow/snapshots/test_dataflow_plan_builder.py/DataflowPlan/test_offset_to_grain_metric_filter_and_query_have_different_granularities__dfp_0.xml
  tests_metricflow/snapshots/test_dataflow_plan_builder.py/DataflowPlan/test_offset_window_metric_filter_and_query_have_different_granularities__dfp_0.xml
  tests_metricflow/snapshots/test_dataflow_plan_builder.py/DataflowPlan/test_where_constrained_plan__dfp_0.xml
  tests_metricflow/snapshots/test_dataflow_plan_builder.py/DataflowPlan/test_where_constrained_plan_time_dimension__dfp_0.xml
  tests_metricflow/snapshots/test_dataflow_plan_builder.py/DataflowPlan/test_where_constrained_with_common_linkable_plan__dfp_0.xml
  tests_metricflow/snapshots/test_source_scan_optimizer.py/DataflowPlan/test_constrained_metric_not_combined__dfp_0.xml
  tests_metricflow/snapshots/test_source_scan_optimizer.py/DataflowPlan/test_constrained_metric_not_combined__dfpo_0.xml
Labels: cla:yes, Skip Changelog

#1212 Appropriate handling for group by source nodes in `ComputeMetricsBranchCombiner`
  metricflow-semantics/metricflow_semantics/test_helpers/semantic_manifest_yamls/simple_manifest/metrics.yaml
  metricflow-semantics/tests_metricflow_semantics/snapshots/test_linkable_spec_resolver.py/list/test_linkable_element_set_as_spec_set__set0.txt
  metricflow-semantics/tests_metricflow_semantics/snapshots/test_semantic_model_container.py/str/test_linkable_elements_for_measure__result0.txt
  metricflow-semantics/tests_metricflow_semantics/snapshots/test_semantic_model_container.py/tuple/test_linkable_elements_for_no_metrics_query__result0.txt
  metricflow/dataflow/nodes/compute_metrics.py
  metricflow/dataflow/optimizer/source_scan/cm_branch_combiner.py
  tests_metricflow/integration/test_cases/itest_metrics.yaml
Labels: cla:yes, Skip Changelog

#1202 Change `MetricFlowQueryParser.parse_and_validate_query()` to return `ParseQueryResult`
  metricflow-semantics/metricflow_semantics/query/query_parser.py
  metricflow-semantics/tests_metricflow_semantics/query/test_ambiguous_entity_path.py
  metricflow-semantics/tests_metricflow_semantics/query/test_query_parser.py
  metricflow-semantics/tests_metricflow_semantics/query/test_suggestions.py
  metricflow/engine/metricflow_engine.py
  scripts/ci_tests/metricflow_semantics_package_test.py
  tests_metricflow/dataflow/builder/test_dataflow_plan_builder.py
  tests_metricflow/dataflow/optimizer/source_scan/test_source_scan_optimizer.py
  tests_metricflow/plan_conversion/dataflow_to_sql/test_distinct_values_to_sql.py
  tests_metricflow/plan_conversion/test_dataflow_to_sql_plan.py
  tests_metricflow/query_rendering/test_cumulative_metric_rendering.py
  tests_metricflow/query_rendering/test_derived_metric_rendering.py
  tests_metricflow/query_rendering/test_fill_nulls_with_rendering.py
  tests_metricflow/query_rendering/test_metric_filter_rendering.py
  tests_metricflow/query_rendering/test_query_rendering.py
Labels: cla:yes, Skip Changelog

#1204 Update `MetricFlowQueryResolution.queried_semantic_models` for Conversion Metrics
  metricflow-semantics/metricflow_semantics/query/group_by_item/resolution_dag/resolution_nodes/base_node.py
  metricflow-semantics/metricflow_semantics/query/group_by_item/resolution_dag/resolution_nodes/measure_source_node.py
  metricflow-semantics/metricflow_semantics/query/group_by_item/resolution_dag/resolution_nodes/metric_resolution_node.py
  metricflow-semantics/metricflow_semantics/query/group_by_item/resolution_dag/resolution_nodes/no_metrics_query_source_node.py
  metricflow-semantics/metricflow_semantics/query/group_by_item/resolution_dag/resolution_nodes/query_resolution_node.py
  metricflow-semantics/metricflow_semantics/query/query_resolver.py
  metricflow-semantics/tests_metricflow_semantics/query/test_conversion_metrics.py
  metricflow-semantics/tests_metricflow_semantics/snapshots/test_conversion_metrics.py/ParseQueryResult/test_conversion_rate_with_constant_properties__result.txt
Labels: cla:yes, Skip Changelog

#1223 Add logging to track latency for metrics as dimensions in query parsing
  metricflow-semantics/metricflow_semantics/model/semantics/linkable_spec_resolver.py
  metricflow-semantics/metricflow_semantics/model/semantics/metric_lookup.py
  metricflow-semantics/metricflow_semantics/query/group_by_item/candidate_push_down/push_down_visitor.py
Labels: cla:yes, Skip Changelog

#1120 Bug fix: selective where filters after join to time spine
  .changes/unreleased/Fixes-20240521-165853.yaml
  metricflow/dataflow/builder/dataflow_plan_builder.py
  tests_metricflow/integration/test_cases/itest_metrics.yaml
  tests_metricflow/query_rendering/test_time_spine_join_rendering.py
  tests_metricflow/snapshots/test_time_spine_join_rendering.py/SqlQueryPlan/BigQuery/test_join_to_time_spine_with_queried_time_constraint__plan0.sql
  tests_metricflow/snapshots/test_time_spine_join_rendering.py/SqlQueryPlan/BigQuery/test_join_to_time_spine_with_queried_time_constraint__plan0_optimized.sql
  tests_metricflow/snapshots/test_time_spine_join_rendering.py/SqlQueryPlan/BigQuery/test_join_to_time_spine_with_time_constraint__plan0.sql
  tests_metricflow/snapshots/test_time_spine_join_rendering.py/SqlQueryPlan/BigQuery/test_join_to_time_spine_with_time_constraint__plan0_optimized.sql
  tests_metricflow/snapshots/test_time_spine_join_rendering.py/SqlQueryPlan/BigQuery/test_simple_join_to_time_spine_with_filter__plan0.sql
  tests_metricflow/snapshots/test_time_spine_join_rendering.py/SqlQueryPlan/BigQuery/test_simple_join_to_time_spine_with_filter__plan0_optimized.sql
  tests_metricflow/snapshots/test_time_spine_join_rendering.py/SqlQueryPlan/BigQuery/test_simple_join_to_time_spine_with_queried_filter__plan0.sql
  tests_metricflow/snapshots/test_time_spine_join_rendering.py/SqlQueryPlan/BigQuery/test_simple_join_to_time_spine_with_queried_filter__plan0_optimized.sql
  tests_metricflow/snapshots/test_time_spine_join_rendering.py/SqlQueryPlan/Databricks/test_join_to_time_spine_with_queried_time_constraint__plan0.sql
  tests_metricflow/snapshots/test_time_spine_join_rendering.py/SqlQueryPlan/Databricks/test_join_to_time_spine_with_queried_time_constraint__plan0_optimized.sql
  tests_metricflow/snapshots/test_time_spine_join_rendering.py/SqlQueryPlan/Databricks/test_join_to_time_spine_with_time_constraint__plan0.sql
  tests_metricflow/snapshots/test_time_spine_join_rendering.py/SqlQueryPlan/Databricks/test_join_to_time_spine_with_time_constraint__plan0_optimized.sql
  tests_metricflow/snapshots/test_time_spine_join_rendering.py/SqlQueryPlan/Databricks/test_simple_join_to_time_spine_with_filter__plan0.sql
  tests_metricflow/snapshots/test_time_spine_join_rendering.py/SqlQueryPlan/Databricks/test_simple_join_to_time_spine_with_filter__plan0_optimized.sql
  tests_metricflow/snapshots/test_time_spine_join_rendering.py/SqlQueryPlan/Databricks/test_simple_join_to_time_spine_with_queried_filter__plan0.sql
  tests_metricflow/snapshots/test_time_spine_join_rendering.py/SqlQueryPlan/Databricks/test_simple_join_to_time_spine_with_queried_filter__plan0_optimized.sql
  tests_metricflow/snapshots/test_time_spine_join_rendering.py/SqlQueryPlan/DuckDB/test_join_to_time_spine_with_queried_time_constraint__plan0.sql
  tests_metricflow/snapshots/test_time_spine_join_rendering.py/SqlQueryPlan/DuckDB/test_join_to_time_spine_with_queried_time_constraint__plan0_optimized.sql
  tests_metricflow/snapshots/test_time_spine_join_rendering.py/SqlQueryPlan/DuckDB/test_join_to_time_spine_with_time_constraint__plan0.sql
  tests_metricflow/snapshots/test_time_spine_join_rendering.py/SqlQueryPlan/DuckDB/test_join_to_time_spine_with_time_constraint__plan0_optimized.sql
  tests_metricflow/snapshots/test_time_spine_join_rendering.py/SqlQueryPlan/DuckDB/test_simple_join_to_time_spine_with_filter__plan0.sql
  tests_metricflow/snapshots/test_time_spine_join_rendering.py/SqlQueryPlan/DuckDB/test_simple_join_to_time_spine_with_filter__plan0_optimized.sql
  tests_metricflow/snapshots/test_time_spine_join_rendering.py/SqlQueryPlan/DuckDB/test_simple_join_to_time_spine_with_queried_filter__plan0.sql
  tests_metricflow/snapshots/test_time_spine_join_rendering.py/SqlQueryPlan/DuckDB/test_simple_join_to_time_spine_with_queried_filter__plan0_optimized.sql
  tests_metricflow/snapshots/test_time_spine_join_rendering.py/SqlQueryPlan/Postgres/test_join_to_time_spine_with_queried_time_constraint__plan0.sql
  tests_metricflow/snapshots/test_time_spine_join_rendering.py/SqlQueryPlan/Postgres/test_join_to_time_spine_with_queried_time_constraint__plan0_optimized.sql
  tests_metricflow/snapshots/test_time_spine_join_rendering.py/SqlQueryPlan/Postgres/test_join_to_time_spine_with_time_constraint__plan0.sql
  tests_metricflow/snapshots/test_time_spine_join_rendering.py/SqlQueryPlan/Postgres/test_join_to_time_spine_with_time_constraint__plan0_optimized.sql
  tests_metricflow/snapshots/test_time_spine_join_rendering.py/SqlQueryPlan/Postgres/test_simple_join_to_time_spine_with_filter__plan0.sql
  tests_metricflow/snapshots/test_time_spine_join_rendering.py/SqlQueryPlan/Postgres/test_simple_join_to_time_spine_with_filter__plan0_optimized.sql
  tests_metricflow/snapshots/test_time_spine_join_rendering.py/SqlQueryPlan/Postgres/test_simple_join_to_time_spine_with_queried_filter__plan0.sql
  tests_metricflow/snapshots/test_time_spine_join_rendering.py/SqlQueryPlan/Postgres/test_simple_join_to_time_spine_with_queried_filter__plan0_optimized.sql
  tests_metricflow/snapshots/test_time_spine_join_rendering.py/SqlQueryPlan/Redshift/test_join_to_time_spine_with_queried_time_constraint__plan0.sql
  tests_metricflow/snapshots/test_time_spine_join_rendering.py/SqlQueryPlan/Redshift/test_join_to_time_spine_with_queried_time_constraint__plan0_optimized.sql
  tests_metricflow/snapshots/test_time_spine_join_rendering.py/SqlQueryPlan/Redshift/test_join_to_time_spine_with_time_constraint__plan0.sql
  tests_metricflow/snapshots/test_time_spine_join_rendering.py/SqlQueryPlan/Redshift/test_join_to_time_spine_with_time_constraint__plan0_optimized.sql
  tests_metricflow/snapshots/test_time_spine_join_rendering.py/SqlQueryPlan/Redshift/test_simple_join_to_time_spine_with_filter__plan0.sql
  tests_metricflow/snapshots/test_time_spine_join_rendering.py/SqlQueryPlan/Redshift/test_simple_join_to_time_spine_with_filter__plan0_optimized.sql
  tests_metricflow/snapshots/test_time_spine_join_rendering.py/SqlQueryPlan/Redshift/test_simple_join_to_time_spine_with_queried_filter__plan0.sql
  tests_metricflow/snapshots/test_time_spine_join_rendering.py/SqlQueryPlan/Redshift/test_simple_join_to_time_spine_with_queried_filter__plan0_optimized.sql
  tests_metricflow/snapshots/test_time_spine_join_rendering.py/SqlQueryPlan/Snowflake/test_join_to_time_spine_with_queried_time_constraint__plan0.sql
  tests_metricflow/snapshots/test_time_spine_join_rendering.py/SqlQueryPlan/Snowflake/test_join_to_time_spine_with_queried_time_constraint__plan0_optimized.sql
  tests_metricflow/snapshots/test_time_spine_join_rendering.py/SqlQueryPlan/Snowflake/test_join_to_time_spine_with_time_constraint__plan0.sql
  tests_metricflow/snapshots/test_time_spine_join_rendering.py/SqlQueryPlan/Snowflake/test_join_to_time_spine_with_time_constraint__plan0_optimized.sql
  tests_metricflow/snapshots/test_time_spine_join_rendering.py/SqlQueryPlan/Snowflake/test_simple_join_to_time_spine_with_filter__plan0.sql
  tests_metricflow/snapshots/test_time_spine_join_rendering.py/SqlQueryPlan/Snowflake/test_simple_join_to_time_spine_with_filter__plan0_optimized.sql
  tests_metricflow/snapshots/test_time_spine_join_rendering.py/SqlQueryPlan/Snowflake/test_simple_join_to_time_spine_with_queried_filter__plan0.sql
  tests_metricflow/snapshots/test_time_spine_join_rendering.py/SqlQueryPlan/Snowflake/test_simple_join_to_time_spine_with_queried_filter__plan0_optimized.sql
  tests_metricflow/snapshots/test_time_spine_join_rendering.py/SqlQueryPlan/Trino/test_join_to_time_spine_with_queried_time_constraint__plan0.sql
  tests_metricflow/snapshots/test_time_spine_join_rendering.py/SqlQueryPlan/Trino/test_join_to_time_spine_with_queried_time_constraint__plan0_optimized.sql
  tests_metricflow/snapshots/test_time_spine_join_rendering.py/SqlQueryPlan/Trino/test_join_to_time_spine_with_time_constraint__plan0.sql
  tests_metricflow/snapshots/test_time_spine_join_rendering.py/SqlQueryPlan/Trino/test_join_to_time_spine_with_time_constraint__plan0_optimized.sql
  tests_metricflow/snapshots/test_time_spine_join_rendering.py/SqlQueryPlan/Trino/test_simple_join_to_time_spine_with_filter__plan0.sql
  tests_metricflow/snapshots/test_time_spine_join_rendering.py/SqlQueryPlan/Trino/test_simple_join_to_time_spine_with_filter__plan0_optimized.sql
  tests_metricflow/snapshots/test_time_spine_join_rendering.py/SqlQueryPlan/Trino/test_simple_join_to_time_spine_with_queried_filter__plan0.sql
  tests_metricflow/snapshots/test_time_spine_join_rendering.py/SqlQueryPlan/Trino/test_simple_join_to_time_spine_with_queried_filter__plan0_optimized.sql
Labels: cla:yes

#1215 Encapsulate time range constraints for predicate pushdown
  metricflow/dataflow/builder/dataflow_plan_builder.py
  metricflow/plan_conversion/node_processor.py
Labels: cla:yes, Skip Changelog

#1216 Use pushdown params to disable time range constraint pushdown
  metricflow/dataflow/builder/dataflow_plan_builder.py
  metricflow/plan_conversion/node_processor.py
  tests_metricflow/dataflow/builder/test_predicate_pushdown.py
Labels: cla:yes, Skip Changelog

#1218 Make source_semantic_models property accessible from a DataflowPlanNode
  .changes/unreleased/Under the Hood-20240516-144603.yaml
  metricflow-semantics/metricflow_semantics/dag/id_prefix.py
  metricflow/dataflow/dataflow_plan.py
  metricflow/dataflow/nodes/read_sql_source.py
  tests_metricflow/dataflow/test_dataflow_plan.py
Labels: cla:yes

#1224 Rename PredicatePushdownParameters to PredicatePushdownState
  metricflow/dataflow/builder/dataflow_plan_builder.py
  metricflow/plan_conversion/node_processor.py
  tests_metricflow/dataflow/builder/test_predicate_pushdown.py
Labels: cla:yes, Skip Changelog

#1225 Encapsulate time range constraint application in more general method
  metricflow/dataflow/builder/dataflow_plan_builder.py
  metricflow/plan_conversion/node_processor.py
  tests_metricflow/dataflow/builder/test_predicate_pushdown.py
Labels: cla:yes, Skip Changelog

#1226 Add element type property to LinkableElement interface
  metricflow-semantics/metricflow_semantics/model/semantics/linkable_element.py
Labels: cla:yes, Skip Changelog

#1229 Cache linkable elements
  .changes/unreleased/Under the Hood-20240523-155148.yaml
  metricflow-semantics/metricflow_semantics/model/semantics/linkable_element_set.py
  metricflow-semantics/metricflow_semantics/model/semantics/metric_lookup.py
  metricflow-semantics/metricflow_semantics/query/group_by_item/candidate_push_down/push_down_visitor.py
  metricflow-semantics/tests_metricflow_semantics/model/test_semantic_model_container.py
  metricflow/engine/metricflow_engine.py
Labels: cla:yes

#1231 Add context to `AssertionError` for derived metric `expr`
  metricflow/plan_conversion/dataflow_to_sql.py
Labels: cla:yes, Skip Changelog

#1188 Assorted Cleanup
  metricflow-semantics/metricflow_semantics/test_helpers/example_project_configuration.py
  metricflow-semantics/metricflow_semantics/test_helpers/manifest_helpers.py
  metricflow-semantics/metricflow_semantics/test_helpers/semantic_manifest_yamls/ambiguous_resolution_manifest/__init__.py
  metricflow-semantics/metricflow_semantics/test_helpers/semantic_manifest_yamls/config_linter_manifest/__init__.py
  metricflow-semantics/metricflow_semantics/test_helpers/semantic_manifest_yamls/cyclic_join_manifest/__init__.py
  metricflow-semantics/metricflow_semantics/test_helpers/semantic_manifest_yamls/data_warehouse_validation_manifest/__init__.py
  metricflow-semantics/metricflow_semantics/test_helpers/semantic_manifest_yamls/extended_date_manifest/__init__.py
  metricflow-semantics/metricflow_semantics/test_helpers/semantic_manifest_yamls/join_types_manifest/__init__.py
  metricflow-semantics/metricflow_semantics/test_helpers/semantic_manifest_yamls/multi_hop_join_manifest/__init__.py
  metricflow-semantics/metricflow_semantics/test_helpers/semantic_manifest_yamls/non_sm_manifest/__init__.py
  metricflow-semantics/metricflow_semantics/test_helpers/semantic_manifest_yamls/partitioned_multi_hop_join_manifest/__init__.py
  metricflow-semantics/metricflow_semantics/test_helpers/semantic_manifest_yamls/scd_manifest/__init__.py
  metricflow-semantics/metricflow_semantics/test_helpers/semantic_manifest_yamls/simple_manifest/__init__.py
  metricflow-semantics/metricflow_semantics/test_helpers/semantic_manifest_yamls/simple_multi_hop_join_manifest/__init__.py
  metricflow-semantics/tests_metricflow_semantics/fixtures/manifest_fixtures.py
  metricflow-semantics/tests_metricflow_semantics/query/test_query_parser.py
  tests_metricflow/cli/test_cli.py
  tests_metricflow/fixtures/manifest_fixtures.py
  tests_metricflow/fixtures/sql_clients/base_sql_client_implementation.py
  tests_metricflow/fixtures/sql_clients/sqlalchemy_dialect.py
Labels: cla:yes, Skip Changelog

#1232 Move `pandas` time-period calls to an interface
  metricflow-semantics/metricflow_semantics/filters/time_constraint.py
  metricflow-semantics/metricflow_semantics/query/query_parser.py
  metricflow-semantics/metricflow_semantics/time/pandas_adjuster.py
  metricflow-semantics/metricflow_semantics/time/time_granularity.py
  metricflow-semantics/metricflow_semantics/time/time_period.py
  metricflow/dataflow/builder/dataflow_plan_builder.py
Labels: cla:yes, Skip Changelog

#1233 Add `DateutilTimePeriodAdjuster`
  metricflow-semantics/metricflow_semantics/query/query_parser.py
  metricflow-semantics/metricflow_semantics/time/dateutil_adjuster.py
  metricflow-semantics/tests_metricflow_semantics/snapshots/test_time_adjuster.py/str/test_start_and_end_periods__results.txt
  metricflow-semantics/tests_metricflow_semantics/time/test_time_adjuster.py
  metricflow/dataflow/builder/dataflow_plan_builder.py
Labels: cla:yes, Skip Changelog

#1234 Add replacement class for dataframes
  metricflow/data_table/__init__.py
  metricflow/data_table/column_types.py
  metricflow/data_table/mf_column.py
  metricflow/data_table/mf_table.py
  tests_metricflow/sql/compare_data_table.py
  tests_metricflow/sql/test_data_table.py
Labels: cla:yes, Skip Changelog
