Repository dbt-labs/metricflow, pull requests merged in 2025-01, with the labels that each got.

#1593 Bug fix: don't erase order by for metric alias query
  metricflow-semantics/metricflow_semantics/query/query_resolver.py
  metricflow-semantics/metricflow_semantics/sql/sql_exprs.py
  metricflow/sql/optimizer/rewriting_sub_query_reducer.py
  tests_metricflow/integration/query_output/test_query_output.py
  tests_metricflow/snapshots/test_query_rendering.py/SqlPlan/DuckDB/test_derived_metric_alias__plan0.sql
  tests_metricflow/snapshots/test_query_rendering.py/SqlPlan/DuckDB/test_derived_metric_alias__plan0_optimized.sql
  tests_metricflow/snapshots/test_query_rendering.py/SqlPlan/DuckDB/test_metric_alias__plan0.sql
  tests_metricflow/snapshots/test_query_rendering.py/SqlPlan/DuckDB/test_metric_alias__plan0_optimized.sql
Labels: cla:yes, Skip Changelog

#1596 Restore type checking for functions decorated with `@lru_cache`
  metricflow-semantics/metricflow_semantics/collection_helpers/lru_cache.py
  metricflow-semantics/metricflow_semantics/naming/linkable_spec_name.py
  metricflow-semantics/metricflow_semantics/specs/time_dimension_spec.py
  metricflow-semantics/metricflow_semantics/time/granularity.py
  metricflow-semantics/metricflow_semantics/time/time_spine_source.py
Labels: cla:yes, Skip Changelog

#1597 Move metric alias details from `MetricSpecPattern` to `ResolverInputForMetric`
  metricflow-semantics/metricflow_semantics/naming/metric_scheme.py
  metricflow-semantics/metricflow_semantics/query/query_resolver.py
  metricflow-semantics/metricflow_semantics/query/resolver_inputs/query_resolver_inputs.py
  metricflow-semantics/metricflow_semantics/specs/patterns/entity_link_pattern.py
  metricflow-semantics/metricflow_semantics/specs/patterns/metric_pattern.py
  metricflow-semantics/metricflow_semantics/specs/query_param_implementations.py
Labels: cla:yes, Skip Changelog

#1606 Add config to get_measures_for_metrics response
  .changes/unreleased/Fixes-20250116-124630.yaml
  metricflow/engine/metricflow_engine.py
Labels: cla:yes

#1605 Add `actionlint` to pre-commit hooks
  .github/workflows/cd-push-dbt-metricflow-to-pypi.yaml
  .github/workflows/cd-push-metricflow-to-pypi.yaml
  .github/workflows/cd-sql-engine-populate-persistent-source-schema.yaml
  .github/workflows/cd-sql-engine-tests.yaml
  .github/workflows/ci-linting.yaml
  .github/workflows/ci-metricflow-unit-tests.yaml
  .pre-commit-config.yaml
Labels: cla:yes, Skip Changelog

#1600 Release PR for MetricFlow 0.207.0
  .changes/0.207.0.md
  .changes/unreleased/Breaking Changes-20241007-142032.yaml
  .changes/unreleased/Breaking Changes-20241021-115548.yaml
  .changes/unreleased/Dependencies-20240624-182325.yaml
  .changes/unreleased/Features-20240521-202252.yaml
  .changes/unreleased/Features-20240607-161232.yaml
  .changes/unreleased/Features-20240613-160758.yaml
  .changes/unreleased/Features-20240613-172315.yaml
  .changes/unreleased/Features-20240614-071108.yaml
  .changes/unreleased/Features-20240625-152952.yaml
  .changes/unreleased/Features-20240628-074617.yaml
  .changes/unreleased/Features-20240725-160038.yaml
  .changes/unreleased/Features-20240727-081106.yaml
  .changes/unreleased/Features-20240813-164801.yaml
  .changes/unreleased/Features-20240821-112601.yaml
  .changes/unreleased/Features-20240827-112415.yaml
  .changes/unreleased/Features-20240920-120114.yaml
  .changes/unreleased/Features-20241023-161720.yaml
  .changes/unreleased/Features-20241104-193531.yaml
  .changes/unreleased/Features-20241112-215817.yaml
  .changes/unreleased/Features-20241210-110613.yaml
  .changes/unreleased/Features-20241210-172725.yaml
  .changes/unreleased/Features-20241213-110407.yaml
  .changes/unreleased/Fixes-20240612-161605.yaml
  .changes/unreleased/Fixes-20240625-114914.yaml
  .changes/unreleased/Fixes-20240716-090114.yaml
  .changes/unreleased/Fixes-20240821-111857.yaml
  .changes/unreleased/Fixes-20240823-123108.yaml
  .changes/unreleased/Fixes-20240827-130128.yaml
  .changes/unreleased/Fixes-20241009-171939.yaml
  .changes/unreleased/Fixes-20241009-174346.yaml
  .changes/unreleased/Fixes-20241011-161926.yaml
  .changes/unreleased/Fixes-20241021-120748.yaml
  .changes/unreleased/Fixes-20241030-201214.yaml
  .changes/unreleased/Fixes-20241121-073923.yaml
  .changes/unreleased/Fixes-20241121-140607.yaml
  .changes/unreleased/Under the Hood-20240603-170530.yaml
  .changes/unreleased/Under the Hood-20240611-162735.yaml
  .changes/unreleased/Under the Hood-20240612-233459.yaml
  .changes/unreleased/Under the Hood-20240613-171930.yaml
  .changes/unreleased/Under the Hood-20240617-110749.yaml
  .changes/unreleased/Under the Hood-20240618-161241.yaml
  ATTRIBUTION.md
  CHANGELOG.md
  pyproject.toml
Labels: cla:yes, Skip Changelog

#1601 Update `pyproject.toml` files to use a dynamic version configuration
  dbt-metricflow/dbt_metricflow/__about__.py
  dbt-metricflow/pyproject.toml
  metricflow/__about__.py
  pyproject.toml
Labels: cla:yes, Skip Changelog

#1581 Renames related to `SqlPlan` - Part 1
  metricflow/dataset/sql_dataset.py
  metricflow/engine/metricflow_engine.py
  metricflow/execution/dataflow_to_execution.py
  metricflow/plan_conversion/dataflow_to_sql.py
  metricflow/plan_conversion/sql_join_builder.py
  metricflow/sql/optimizer/column_pruner.py
  metricflow/sql/optimizer/optimization_levels.py
  metricflow/sql/optimizer/required_column_aliases.py
  metricflow/sql/optimizer/rewriting_sub_query_reducer.py
  metricflow/sql/optimizer/sql_query_plan_optimizer.py
  metricflow/sql/optimizer/sub_query_reducer.py
  metricflow/sql/optimizer/table_alias_simplifier.py
  metricflow/sql/optimizer/tag_column_aliases.py
  metricflow/sql/render/sql_plan_renderer.py
  metricflow/sql/sql_plan.py
  metricflow/validation/data_warehouse_model_validator.py
  tests_metricflow/examples/test_node_sql.py
  tests_metricflow/fixtures/manifest_fixtures.py
  tests_metricflow/fixtures/sql_fixtures.py
  tests_metricflow/plan_conversion/dataflow_to_sql/test_conversion_metrics_to_sql.py
  tests_metricflow/plan_conversion/dataflow_to_sql/test_cte_sql.py
  tests_metricflow/plan_conversion/dataflow_to_sql/test_distinct_values_to_sql.py
  tests_metricflow/plan_conversion/dataflow_to_sql/test_metric_time_dimension_to_sql.py
  tests_metricflow/plan_conversion/test_dataflow_to_execution.py
  tests_metricflow/plan_conversion/test_dataflow_to_sql_plan.py
  tests_metricflow/query_rendering/compare_rendered_query.py
  tests_metricflow/query_rendering/test_conversion_metric_rendering.py
  tests_metricflow/query_rendering/test_cumulative_metric_rendering.py
  tests_metricflow/query_rendering/test_custom_granularity.py
  tests_metricflow/query_rendering/test_derived_metric_rendering.py
  tests_metricflow/query_rendering/test_fill_nulls_with_rendering.py
  tests_metricflow/query_rendering/test_granularity_date_part_rendering.py
  tests_metricflow/query_rendering/test_metric_filter_rendering.py
  tests_metricflow/query_rendering/test_metric_time_without_metrics.py
  tests_metricflow/query_rendering/test_predicate_pushdown_rendering.py
  tests_metricflow/query_rendering/test_query_rendering.py
  tests_metricflow/query_rendering/test_time_spine_join_rendering.py
  tests_metricflow/sql/compare_sql_plan.py
  tests_metricflow/sql/optimizer/check_optimizer.py
  tests_metricflow/sql/optimizer/test_column_pruner.py
Labels: cla:yes, Skip Changelog

#1582 Renames related to `SqlPlan` - Part 2
  metricflow-semantics/metricflow_semantics/dag/id_prefix.py
  metricflow/engine/metricflow_engine.py
  metricflow/execution/dataflow_to_execution.py
  metricflow/plan_conversion/dataflow_to_sql.py
  metricflow/sql/optimizer/optimization_levels.py
  metricflow/sql/sql_plan.py
  metricflow/validation/data_warehouse_model_validator.py
  tests_metricflow/engine/test_explain.py
  tests_metricflow/examples/test_node_sql.py
  tests_metricflow/plan_conversion/dataflow_to_sql/test_cte_sql.py
  tests_metricflow/plan_conversion/test_dataflow_to_execution.py
  tests_metricflow/plan_conversion/test_dataflow_to_sql_plan.py
  tests_metricflow/query_rendering/compare_rendered_query.py
  tests_metricflow/snapshots/test_explain.py/str/test_optimization_level__result.txt
Labels: cla:yes, Skip Changelog

#1583 Renames related to `SqlPlan` - Part 3
  dbt-metricflow/dbt_metricflow/cli/dbt_connectors/adapter_backed_client.py
  metricflow/engine/metricflow_engine.py
  metricflow/execution/dataflow_to_execution.py
  metricflow/protocols/sql_client.py
  metricflow/sql/render/big_query.py
  metricflow/sql/render/databricks.py
  metricflow/sql/render/duckdb_renderer.py
  metricflow/sql/render/postgres.py
  metricflow/sql/render/redshift.py
  metricflow/sql/render/snowflake.py
  metricflow/sql/render/sql_plan_renderer.py
  metricflow/sql/render/trino.py
  metricflow/validation/data_warehouse_model_validator.py
  tests_metricflow/examples/test_node_sql.py
  tests_metricflow/fixtures/sql_clients/adapter_backed_ddl_client.py
  tests_metricflow/fixtures/sql_fixtures.py
  tests_metricflow/integration/query_output/test_cumulative_metrics.py
  tests_metricflow/integration/test_configured_cases.py
  tests_metricflow/plan_conversion/dataflow_to_sql/test_cte_sql.py
  tests_metricflow/plan_conversion/test_dataflow_to_execution.py
  tests_metricflow/sql/compare_sql_plan.py
  tests_metricflow/sql/optimizer/check_optimizer.py
  tests_metricflow/sql/optimizer/test_column_pruner.py
  tests_metricflow/sql/optimizer/test_cte_column_pruner.py
  tests_metricflow/sql/optimizer/test_cte_rewriting_sub_query_reducer.py
  tests_metricflow/sql/optimizer/test_cte_table_alias_simplifier.py
  tests_metricflow/sql/optimizer/test_table_alias_simplifier.py
  tests_metricflow/sql/test_engine_specific_rendering.py
  tests_metricflow/sql_clients/test_date_time_operations.py
Labels: cla:yes, Skip Changelog

#1608 Allow direct references for `dbt-metricfow` dependencies
  dbt-metricflow/pyproject.toml
Labels: cla:yes, Skip Changelog

#1610 Cache Python Environments in CI
  .github/actions/run-mf-tests/action.yaml
  .github/actions/setup-python-env/action.yaml
  .github/workflows/cd-sql-engine-tests.yaml
  .github/workflows/ci-linting.yaml
  .github/workflows/ci-metricflow-unit-tests.yaml
  scripts/ci_tests/install_hatch_environments.py
  scripts/ci_tests/run_package_build_tests.py
  scripts/mf_script_helper.py
Labels: cla:yes, Skip Changelog

#1612 Add `SqlCteAliasMapping` to replace `dict`
  metricflow/sql/optimizer/column_pruner.py
  metricflow/sql/optimizer/required_column_aliases.py
  metricflow/sql/sql_plan.py
Labels: cla:yes, Skip Changelog

#1613 For `SqlColumnPrunerOptimizer` - add support for CTEs in sub-queries
  metricflow/sql/optimizer/column_pruner.py
  metricflow/sql/optimizer/cte_alias_to_cte_node_mapping.py
  metricflow/sql/optimizer/cte_mapping_lookup_builder.py
  metricflow/sql/optimizer/required_column_aliases.py
  tests_metricflow/snapshots/test_cte_column_pruner.py/str/test_common_cte_aliases_in_nested_query__result.txt
  tests_metricflow/sql/optimizer/check_optimizer.py
  tests_metricflow/sql/optimizer/test_cte_column_pruner.py
Labels: cla:yes, Skip Changelog

#1614 For `SqlRewritingSubQueryReducer`, add support for CTEs defined in sub-queries
  metricflow/sql/optimizer/rewriting_sub_query_reducer.py
  tests_metricflow/snapshots/test_cte_rewriting_sub_query_reducer.py/str/test_cte_in_subquery_not_reduced__result.txt
  tests_metricflow/sql/optimizer/test_cte_rewriting_sub_query_reducer.py
Labels: cla:yes, Skip Changelog

#1579 Add new dataflow plan node for custom offset windows
  metricflow-semantics/metricflow_semantics/dag/id_prefix.py
  metricflow-semantics/metricflow_semantics/specs/dunder_column_association_resolver.py
  metricflow-semantics/metricflow_semantics/specs/time_dimension_spec.py
  metricflow-semantics/metricflow_semantics/sql/sql_exprs.py
  metricflow-semantics/tests_metricflow_semantics/collection_helpers/test_pretty_print.py
  metricflow/dataflow/builder/dataflow_plan_builder.py
  metricflow/dataflow/dataflow_plan_visitor.py
  metricflow/dataflow/nodes/offset_by_custom_granularity.py
  metricflow/dataflow/optimizer/predicate_pushdown_optimizer.py
  metricflow/dataflow/optimizer/source_scan/cm_branch_combiner.py
  metricflow/dataflow/optimizer/source_scan/source_scan_optimizer.py
  metricflow/dataset/convert_semantic_model.py
  metricflow/dataset/sql_dataset.py
  metricflow/execution/dataflow_to_execution.py
  metricflow/plan_conversion/dataflow_to_sql.py
  metricflow/sql/sql_plan.py
  tests_metricflow/dataflow/optimizer/source_scan/test_source_scan_optimizer.py
Labels: cla:yes, Skip Changelog

#1585 Tests for custom offset window
  metricflow-semantics/metricflow_semantics/test_helpers/semantic_manifest_yamls/simple_manifest/metrics.yaml
  metricflow/dataflow/builder/node_data_set.py
  tests_metricflow/integration/query_output/test_offset_metrics.py
  tests_metricflow/integration/test_cases/itest_granularity.yaml
  tests_metricflow/integration/test_configured_cases.py
  tests_metricflow/query_rendering/test_custom_granularity.py
  tests_metricflow/snapshots/test_custom_granularity.py/SqlPlan/BigQuery/test_custom_offset_window__plan0.sql
  tests_metricflow/snapshots/test_custom_granularity.py/SqlPlan/BigQuery/test_custom_offset_window__plan0_optimized.sql
  tests_metricflow/snapshots/test_custom_granularity.py/SqlPlan/BigQuery/test_custom_offset_window_with_granularity_and_date_part__plan0.sql
  tests_metricflow/snapshots/test_custom_granularity.py/SqlPlan/BigQuery/test_custom_offset_window_with_granularity_and_date_part__plan0_optimized.sql
  tests_metricflow/snapshots/test_custom_granularity.py/SqlPlan/Databricks/test_custom_offset_window__plan0.sql
  tests_metricflow/snapshots/test_custom_granularity.py/SqlPlan/Databricks/test_custom_offset_window__plan0_optimized.sql
  tests_metricflow/snapshots/test_custom_granularity.py/SqlPlan/Databricks/test_custom_offset_window_with_granularity_and_date_part__plan0.sql
  tests_metricflow/snapshots/test_custom_granularity.py/SqlPlan/Databricks/test_custom_offset_window_with_granularity_and_date_part__plan0_optimized.sql
  tests_metricflow/snapshots/test_custom_granularity.py/SqlPlan/DuckDB/test_custom_offset_window__plan0.sql
  tests_metricflow/snapshots/test_custom_granularity.py/SqlPlan/DuckDB/test_custom_offset_window__plan0_optimized.sql
  tests_metricflow/snapshots/test_custom_granularity.py/SqlPlan/DuckDB/test_custom_offset_window_with_granularity_and_date_part__plan0.sql
  tests_metricflow/snapshots/test_custom_granularity.py/SqlPlan/DuckDB/test_custom_offset_window_with_granularity_and_date_part__plan0_optimized.sql
  tests_metricflow/snapshots/test_custom_granularity.py/SqlPlan/Postgres/test_custom_offset_window__plan0.sql
  tests_metricflow/snapshots/test_custom_granularity.py/SqlPlan/Postgres/test_custom_offset_window__plan0_optimized.sql
  tests_metricflow/snapshots/test_custom_granularity.py/SqlPlan/Postgres/test_custom_offset_window_with_granularity_and_date_part__plan0.sql
  tests_metricflow/snapshots/test_custom_granularity.py/SqlPlan/Postgres/test_custom_offset_window_with_granularity_and_date_part__plan0_optimized.sql
  tests_metricflow/snapshots/test_custom_granularity.py/SqlPlan/Redshift/test_custom_offset_window__plan0.sql
  tests_metricflow/snapshots/test_custom_granularity.py/SqlPlan/Redshift/test_custom_offset_window__plan0_optimized.sql
  tests_metricflow/snapshots/test_custom_granularity.py/SqlPlan/Redshift/test_custom_offset_window_with_granularity_and_date_part__plan0.sql
  tests_metricflow/snapshots/test_custom_granularity.py/SqlPlan/Redshift/test_custom_offset_window_with_granularity_and_date_part__plan0_optimized.sql
  tests_metricflow/snapshots/test_custom_granularity.py/SqlPlan/Snowflake/test_custom_offset_window__plan0.sql
  tests_metricflow/snapshots/test_custom_granularity.py/SqlPlan/Snowflake/test_custom_offset_window__plan0_optimized.sql
  tests_metricflow/snapshots/test_custom_granularity.py/SqlPlan/Snowflake/test_custom_offset_window_with_granularity_and_date_part__plan0.sql
  tests_metricflow/snapshots/test_custom_granularity.py/SqlPlan/Snowflake/test_custom_offset_window_with_granularity_and_date_part__plan0_optimized.sql
  tests_metricflow/snapshots/test_custom_granularity.py/SqlPlan/Trino/test_custom_offset_window__plan0.sql
  tests_metricflow/snapshots/test_custom_granularity.py/SqlPlan/Trino/test_custom_offset_window__plan0_optimized.sql
  tests_metricflow/snapshots/test_custom_granularity.py/SqlPlan/Trino/test_custom_offset_window_with_granularity_and_date_part__plan0.sql
  tests_metricflow/snapshots/test_custom_granularity.py/SqlPlan/Trino/test_custom_offset_window_with_granularity_and_date_part__plan0_optimized.sql
  tests_metricflow/snapshots/test_offset_metrics.py/str/BigQuery/test_custom_offset_window_with_base_grain__query_output.txt
  tests_metricflow/snapshots/test_offset_metrics.py/str/BigQuery/test_custom_offset_window_with_grains_and_date_part__query_output.txt
  tests_metricflow/snapshots/test_offset_metrics.py/str/Databricks/test_custom_offset_window_with_base_grain__query_output.txt
  tests_metricflow/snapshots/test_offset_metrics.py/str/Databricks/test_custom_offset_window_with_grains_and_date_part__query_output.txt
  tests_metricflow/snapshots/test_offset_metrics.py/str/DuckDB/test_custom_offset_window_with_base_grain__query_output.txt
  tests_metricflow/snapshots/test_offset_metrics.py/str/DuckDB/test_custom_offset_window_with_grains_and_date_part__query_output.txt
  tests_metricflow/snapshots/test_offset_metrics.py/str/Postgres/test_custom_offset_window_with_base_grain__query_output.txt
  tests_metricflow/snapshots/test_offset_metrics.py/str/Postgres/test_custom_offset_window_with_grains_and_date_part__query_output.txt
  tests_metricflow/snapshots/test_offset_metrics.py/str/Redshift/test_custom_offset_window_with_base_grain__query_output.txt
  tests_metricflow/snapshots/test_offset_metrics.py/str/Redshift/test_custom_offset_window_with_grains_and_date_part__query_output.txt
  tests_metricflow/snapshots/test_offset_metrics.py/str/Snowflake/test_custom_offset_window_with_base_grain__query_output.txt
  tests_metricflow/snapshots/test_offset_metrics.py/str/Snowflake/test_custom_offset_window_with_grains_and_date_part__query_output.txt
  tests_metricflow/snapshots/test_offset_metrics.py/str/Trino/test_custom_offset_window_with_base_grain__query_output.txt
  tests_metricflow/snapshots/test_offset_metrics.py/str/Trino/test_custom_offset_window_with_grains_and_date_part__query_output.txt
Labels: cla:yes, Skip Changelog

#1619 Fix reuse of `SelectStatementNode` for semi-additive join SQL
  metricflow/plan_conversion/dataflow_to_sql.py
  metricflow/sql/sql_plan.py
  tests_metricflow/snapshots/test_dataflow_to_sql_plan.py/SqlPlan/test_semi_additive_join_node__plan0.xml
  tests_metricflow/snapshots/test_dataflow_to_sql_plan.py/SqlPlan/test_semi_additive_join_node_with_grouping__plan0.xml
  tests_metricflow/snapshots/test_dataflow_to_sql_plan.py/SqlPlan/test_semi_additive_join_node_with_queried_group_by__plan0.xml
Labels: cla:yes, Skip Changelog

#1509 Add performance tracking machinery
  .gitignore
  Makefile
  metricflow-semantics/metricflow_semantics/test_helpers/performance_helpers.py
  pyproject.toml
  tests_metricflow/performance/__init__.py
  tests_metricflow/performance/compare_reports.py
  tests_metricflow/performance/conftest.py
  tests_metricflow/performance/test_simple_manifest.py
Labels: cla:yes, Skip Changelog

#1624 Add helper functions for building `JoinToTimeSpineNodes`
  metricflow/dataflow/builder/dataflow_plan_builder.py
Labels: cla:yes, Skip Changelog

#1633 Redo: #1628
  .changes/unreleased/Fixes-20250124-140300.yaml
  dbt-metricflow/dbt_metricflow/cli/cli_configuration.py
  dbt-metricflow/dbt_metricflow/cli/main.py
  dbt-metricflow/dbt_metricflow/cli/mf_tutorial_project/dbt_project.yml
  dbt-metricflow/dbt_metricflow/cli/mf_tutorial_project/models/metricflow_time_spine.sql
  dbt-metricflow/dbt_metricflow/cli/mf_tutorial_project/profiles.yml
  dbt-metricflow/dbt_metricflow/cli/tutorial.py
  dbt-metricflow/dbt_metricflow/cli/utils.py
  tests_metricflow/cli/test_cli.py
  tests_metricflow/fixtures/cli_fixtures.py
Labels: cla:yes, Skip Changelog

#1625 Split `dataflow_to_sql.py` into separate files
  CONTRIBUTING.md
  metricflow/dataflow/builder/node_data_set.py
  metricflow/engine/metricflow_engine.py
  metricflow/execution/dataflow_to_execution.py
  metricflow/plan_conversion/to_sql_plan/__init__.py
  metricflow/plan_conversion/to_sql_plan/dataflow_to_cte.py
  metricflow/plan_conversion/to_sql_plan/dataflow_to_sql.py
  metricflow/plan_conversion/to_sql_plan/dataflow_to_subquery.py
  metricflow/plan_conversion/to_sql_plan/sql_join_builder.py
  metricflow/validation/data_warehouse_model_validator.py
  tests_metricflow/examples/test_node_sql.py
  tests_metricflow/fixtures/manifest_fixtures.py
  tests_metricflow/fixtures/sql_fixtures.py
  tests_metricflow/plan_conversion/dataflow_to_sql/test_conversion_metrics_to_sql.py
  tests_metricflow/plan_conversion/dataflow_to_sql/test_cte_sql.py
  tests_metricflow/plan_conversion/dataflow_to_sql/test_distinct_values_to_sql.py
  tests_metricflow/plan_conversion/dataflow_to_sql/test_metric_time_dimension_to_sql.py
  tests_metricflow/plan_conversion/test_dataflow_to_execution.py
  tests_metricflow/plan_conversion/test_dataflow_to_sql_plan.py
  tests_metricflow/query_rendering/compare_rendered_query.py
  tests_metricflow/query_rendering/test_conversion_metric_rendering.py
  tests_metricflow/query_rendering/test_cumulative_metric_rendering.py
  tests_metricflow/query_rendering/test_custom_granularity.py
  tests_metricflow/query_rendering/test_derived_metric_rendering.py
  tests_metricflow/query_rendering/test_fill_nulls_with_rendering.py
  tests_metricflow/query_rendering/test_granularity_date_part_rendering.py
  tests_metricflow/query_rendering/test_metric_filter_rendering.py
  tests_metricflow/query_rendering/test_metric_time_without_metrics.py
  tests_metricflow/query_rendering/test_predicate_pushdown_rendering.py
  tests_metricflow/query_rendering/test_query_rendering.py
  tests_metricflow/query_rendering/test_time_spine_join_rendering.py
Labels: cla:yes, Skip Changelog

#1626 Split `sql_plan.py` into separate files
  metricflow/dataset/convert_semantic_model.py
  metricflow/dataset/semantic_model_adapter.py
  metricflow/dataset/sql_dataset.py
  metricflow/plan_conversion/to_sql_plan/dataflow_to_cte.py
  metricflow/plan_conversion/to_sql_plan/dataflow_to_sql.py
  metricflow/plan_conversion/to_sql_plan/dataflow_to_subquery.py
  metricflow/plan_conversion/to_sql_plan/sql_join_builder.py
  metricflow/sql/optimizer/column_pruner.py
  metricflow/sql/optimizer/cte_alias_to_cte_node_mapping.py
  metricflow/sql/optimizer/cte_mapping_lookup_builder.py
  metricflow/sql/optimizer/required_column_aliases.py
  metricflow/sql/optimizer/rewriting_sub_query_reducer.py
  metricflow/sql/optimizer/table_alias_simplifier.py
  metricflow/sql/render/sql_plan_renderer.py
  metricflow/sql/sql_ctas_node.py
  metricflow/sql/sql_cte_node.py
  metricflow/sql/sql_plan.py
  metricflow/sql/sql_select_node.py
  metricflow/sql/sql_select_text_node.py
  metricflow/sql/sql_table_node.py
  tests_metricflow/dataflow/builder/test_node_data_set.py
  tests_metricflow/mf_logging/test_dag_to_text.py
  tests_metricflow/performance/conftest.py
  tests_metricflow/performance/test_simple_manifest.py
  tests_metricflow/sql/optimizer/check_optimizer.py
  tests_metricflow/sql/optimizer/test_column_pruner.py
  tests_metricflow/sql/optimizer/test_cte_column_pruner.py
  tests_metricflow/sql/optimizer/test_cte_rewriting_sub_query_reducer.py
  tests_metricflow/sql/optimizer/test_cte_table_alias_simplifier.py
  tests_metricflow/sql/optimizer/test_rewriting_sub_query_reducer.py
  tests_metricflow/sql/optimizer/test_table_alias_simplifier.py
  tests_metricflow/sql/test_engine_specific_rendering.py
  tests_metricflow/sql/test_render_cte.py
  tests_metricflow/sql/test_sql_plan_render.py
Labels: cla:yes, Skip Changelog

#1627 Move column pruner classes to a separate module
  metricflow/sql/optimizer/column_pruning/__init__.py
  metricflow/sql/optimizer/column_pruning/column_pruner.py
  metricflow/sql/optimizer/column_pruning/cte_alias_to_cte_node_mapping.py
  metricflow/sql/optimizer/column_pruning/cte_mapping_lookup_builder.py
  metricflow/sql/optimizer/column_pruning/node_to_column_alias_maping.py
  metricflow/sql/optimizer/column_pruning/required_column_aliases.py
  metricflow/sql/optimizer/optimization_levels.py
  tests_metricflow/sql/optimizer/test_column_pruner.py
  tests_metricflow/sql/optimizer/test_cte_column_pruner.py
Labels: cla:yes, Skip Changelog

#1636 Run the Github cache workflow using the `main` branch
  .github/workflows/ci-cache-environments.yaml
Labels: cla:yes, Skip Changelog

#1634 Update time-spine configuration for tutorial project
  dbt-metricflow/dbt_metricflow/cli/__init__.py
  dbt-metricflow/dbt_metricflow/cli/main.py
  dbt-metricflow/dbt_metricflow/cli/mf_tutorial_project/models/_models.yml
  dbt-metricflow/dbt_metricflow/cli/mf_tutorial_project/models/all_days.sql
Labels: cla:yes, Skip Changelog

#1635 Update tutorial flow for missing adapter packages
  dbt-metricflow/dbt_metricflow/cli/cli_configuration.py
  dbt-metricflow/dbt_metricflow/cli/main.py
Labels: cla:yes, Skip Changelog

#1629 Prettify`semantic_manifes_pretty.json`
  dbt-metricflow/dbt_metricflow/cli/sample_dbt_models/semantic_manifest.json
Labels: cla:yes, Skip Changelog

#1621 Allow querying SCDs without `metric_time`
  .changes/unreleased/Features-20250124-133535.yaml
  metricflow-semantics/metricflow_semantics/query/validation_rules/metric_time_requirements.py
  metricflow-semantics/tests_metricflow_semantics/query/test_query_parser.py
  metricflow-semantics/tests_metricflow_semantics/snapshots/test_query_parser.py/str/test_join_through_scd_no_time_dimension_validation__error.txt
  metricflow-semantics/tests_metricflow_semantics/snapshots/test_query_parser.py/str/test_join_to_scd_no_time_dimension_validation__error.txt
  tests_metricflow/integration/conftest.py
  tests_metricflow/integration/query_output/test_query_output.py
  tests_metricflow/query_rendering/test_query_rendering.py
  tests_metricflow/snapshots/test_query_output.py/str/DuckDB/test_scd_filter_without_metric_time__query_output.txt
  tests_metricflow/snapshots/test_query_output.py/str/DuckDB/test_scd_group_by_without_metric_time__query_output.txt
  tests_metricflow/snapshots/test_query_output.py/str/DuckDB/test_scd_with_coarser_grain__query_output.txt
  tests_metricflow/snapshots/test_query_rendering.py/SqlPlan/BigQuery/test_scd_dimension_filter_without_metric_time__plan0.sql
  tests_metricflow/snapshots/test_query_rendering.py/SqlPlan/BigQuery/test_scd_dimension_filter_without_metric_time__plan0_optimized.sql
  tests_metricflow/snapshots/test_query_rendering.py/SqlPlan/BigQuery/test_scd_dimension_group_by_without_metric_time__plan0.sql
  tests_metricflow/snapshots/test_query_rendering.py/SqlPlan/BigQuery/test_scd_dimension_group_by_without_metric_time__plan0_optimized.sql
  tests_metricflow/snapshots/test_query_rendering.py/SqlPlan/BigQuery/test_scd_group_by_and_coarser_grain__plan0.sql
  tests_metricflow/snapshots/test_query_rendering.py/SqlPlan/BigQuery/test_scd_group_by_and_coarser_grain__plan0_optimized.sql
  tests_metricflow/snapshots/test_query_rendering.py/SqlPlan/Databricks/test_scd_dimension_filter_without_metric_time__plan0.sql
  tests_metricflow/snapshots/test_query_rendering.py/SqlPlan/Databricks/test_scd_dimension_filter_without_metric_time__plan0_optimized.sql
  tests_metricflow/snapshots/test_query_rendering.py/SqlPlan/Databricks/test_scd_dimension_group_by_without_metric_time__plan0.sql
  tests_metricflow/snapshots/test_query_rendering.py/SqlPlan/Databricks/test_scd_dimension_group_by_without_metric_time__plan0_optimized.sql
  tests_metricflow/snapshots/test_query_rendering.py/SqlPlan/Databricks/test_scd_group_by_and_coarser_grain__plan0.sql
  tests_metricflow/snapshots/test_query_rendering.py/SqlPlan/Databricks/test_scd_group_by_and_coarser_grain__plan0_optimized.sql
  tests_metricflow/snapshots/test_query_rendering.py/SqlPlan/DuckDB/test_scd_dimension_filter_without_metric_time__plan0.sql
  tests_metricflow/snapshots/test_query_rendering.py/SqlPlan/DuckDB/test_scd_dimension_filter_without_metric_time__plan0_optimized.sql
  tests_metricflow/snapshots/test_query_rendering.py/SqlPlan/DuckDB/test_scd_dimension_group_by_without_metric_time__plan0.sql
  tests_metricflow/snapshots/test_query_rendering.py/SqlPlan/DuckDB/test_scd_dimension_group_by_without_metric_time__plan0_optimized.sql
  tests_metricflow/snapshots/test_query_rendering.py/SqlPlan/DuckDB/test_scd_group_by_and_coarser_grain__plan0.sql
  tests_metricflow/snapshots/test_query_rendering.py/SqlPlan/DuckDB/test_scd_group_by_and_coarser_grain__plan0_optimized.sql
  tests_metricflow/snapshots/test_query_rendering.py/SqlPlan/Postgres/test_scd_dimension_filter_without_metric_time__plan0.sql
  tests_metricflow/snapshots/test_query_rendering.py/SqlPlan/Postgres/test_scd_dimension_filter_without_metric_time__plan0_optimized.sql
  tests_metricflow/snapshots/test_query_rendering.py/SqlPlan/Postgres/test_scd_dimension_group_by_without_metric_time__plan0.sql
  tests_metricflow/snapshots/test_query_rendering.py/SqlPlan/Postgres/test_scd_dimension_group_by_without_metric_time__plan0_optimized.sql
  tests_metricflow/snapshots/test_query_rendering.py/SqlPlan/Postgres/test_scd_group_by_and_coarser_grain__plan0.sql
  tests_metricflow/snapshots/test_query_rendering.py/SqlPlan/Postgres/test_scd_group_by_and_coarser_grain__plan0_optimized.sql
  tests_metricflow/snapshots/test_query_rendering.py/SqlPlan/Redshift/test_scd_dimension_filter_without_metric_time__plan0.sql
  tests_metricflow/snapshots/test_query_rendering.py/SqlPlan/Redshift/test_scd_dimension_filter_without_metric_time__plan0_optimized.sql
  tests_metricflow/snapshots/test_query_rendering.py/SqlPlan/Redshift/test_scd_dimension_group_by_without_metric_time__plan0.sql
  tests_metricflow/snapshots/test_query_rendering.py/SqlPlan/Redshift/test_scd_dimension_group_by_without_metric_time__plan0_optimized.sql
  tests_metricflow/snapshots/test_query_rendering.py/SqlPlan/Redshift/test_scd_group_by_and_coarser_grain__plan0.sql
  tests_metricflow/snapshots/test_query_rendering.py/SqlPlan/Redshift/test_scd_group_by_and_coarser_grain__plan0_optimized.sql
  tests_metricflow/snapshots/test_query_rendering.py/SqlPlan/Snowflake/test_scd_dimension_filter_without_metric_time__plan0.sql
  tests_metricflow/snapshots/test_query_rendering.py/SqlPlan/Snowflake/test_scd_dimension_filter_without_metric_time__plan0_optimized.sql
  tests_metricflow/snapshots/test_query_rendering.py/SqlPlan/Snowflake/test_scd_dimension_group_by_without_metric_time__plan0.sql
  tests_metricflow/snapshots/test_query_rendering.py/SqlPlan/Snowflake/test_scd_dimension_group_by_without_metric_time__plan0_optimized.sql
  tests_metricflow/snapshots/test_query_rendering.py/SqlPlan/Snowflake/test_scd_group_by_and_coarser_grain__plan0.sql
  tests_metricflow/snapshots/test_query_rendering.py/SqlPlan/Snowflake/test_scd_group_by_and_coarser_grain__plan0_optimized.sql
  tests_metricflow/snapshots/test_query_rendering.py/SqlPlan/Trino/test_scd_dimension_filter_without_metric_time__plan0.sql
  tests_metricflow/snapshots/test_query_rendering.py/SqlPlan/Trino/test_scd_dimension_filter_without_metric_time__plan0_optimized.sql
  tests_metricflow/snapshots/test_query_rendering.py/SqlPlan/Trino/test_scd_dimension_group_by_without_metric_time__plan0.sql
  tests_metricflow/snapshots/test_query_rendering.py/SqlPlan/Trino/test_scd_dimension_group_by_without_metric_time__plan0_optimized.sql
  tests_metricflow/snapshots/test_query_rendering.py/SqlPlan/Trino/test_scd_group_by_and_coarser_grain__plan0.sql
  tests_metricflow/snapshots/test_query_rendering.py/SqlPlan/Trino/test_scd_group_by_and_coarser_grain__plan0_optimized.sql
Labels: cla:yes

#1630 Add `--yes` option to `mf tutorial`
  dbt-metricflow/dbt_metricflow/cli/main.py
Labels: cla:yes, Skip Changelog

#1615 Release `0.207.1`
  .changes/0.207.1.md
  .changes/unreleased/Breaking Changes-20241007-142032.yaml
  .changes/unreleased/Breaking Changes-20241021-115548.yaml
  .changes/unreleased/Dependencies-20240624-182325.yaml
  .changes/unreleased/Features-20240521-202252.yaml
  .changes/unreleased/Features-20240607-161232.yaml
  .changes/unreleased/Features-20240613-160758.yaml
  .changes/unreleased/Features-20240613-172315.yaml
  .changes/unreleased/Features-20240614-071108.yaml
  .changes/unreleased/Features-20240625-152952.yaml
  .changes/unreleased/Features-20240628-074617.yaml
  .changes/unreleased/Features-20240725-160038.yaml
  .changes/unreleased/Features-20240727-081106.yaml
  .changes/unreleased/Features-20240813-164801.yaml
  .changes/unreleased/Features-20240821-112601.yaml
  .changes/unreleased/Features-20240827-112415.yaml
  .changes/unreleased/Features-20240920-120114.yaml
  .changes/unreleased/Features-20241023-161720.yaml
  .changes/unreleased/Features-20241104-193531.yaml
  .changes/unreleased/Features-20241112-215817.yaml
  .changes/unreleased/Fixes-20240612-161605.yaml
  .changes/unreleased/Fixes-20240625-114914.yaml
  .changes/unreleased/Fixes-20240716-090114.yaml
  .changes/unreleased/Fixes-20240821-111857.yaml
  .changes/unreleased/Fixes-20240823-123108.yaml
  .changes/unreleased/Fixes-20240827-130128.yaml
  .changes/unreleased/Fixes-20241009-171939.yaml
  .changes/unreleased/Fixes-20241009-174346.yaml
  .changes/unreleased/Fixes-20241011-161926.yaml
  .changes/unreleased/Fixes-20241021-120748.yaml
  .changes/unreleased/Fixes-20241030-201214.yaml
  .changes/unreleased/Fixes-20250124-140300.yaml
  .changes/unreleased/Under the Hood-20240603-170530.yaml
  .changes/unreleased/Under the Hood-20240611-162735.yaml
  .changes/unreleased/Under the Hood-20240612-233459.yaml
  .changes/unreleased/Under the Hood-20240613-171930.yaml
  .changes/unreleased/Under the Hood-20240617-110749.yaml
  .changes/unreleased/Under the Hood-20240618-161241.yaml
  ATTRIBUTION.md
  CHANGELOG.md
  dbt-metricflow/extra-hatch-configuration/requirements-cli.txt
  dbt-metricflow/extra-hatch-configuration/requirements-dbt-bigquery.txt
  dbt-metricflow/extra-hatch-configuration/requirements-dbt-databricks.txt
  dbt-metricflow/extra-hatch-configuration/requirements-dbt-duckdb.txt
  dbt-metricflow/extra-hatch-configuration/requirements-dbt-postgres.txt
  dbt-metricflow/extra-hatch-configuration/requirements-dbt-redshift.txt
  dbt-metricflow/extra-hatch-configuration/requirements-dbt-snowflake.txt
  dbt-metricflow/extra-hatch-configuration/requirements-dbt-trino.txt
  dbt-metricflow/extra-hatch-configuration/requirements-metricflow.txt
  dbt-metricflow/pyproject.toml
  extra-hatch-configuration/requirements.txt
  metricflow-semantics/pyproject.toml
  pyproject.toml
Labels: cla:yes, Skip Changelog

#1638 Update Pypi publish workflow to use Python 3.9
  .github/actions/setup-python-env/action.yaml
  .github/workflows/cd-push-metricflow-to-pypi.yaml
Labels: cla:yes, Skip Changelog

#1640 Dummy commit
  dbt-metricflow/dbt_metricflow/cli/cli_context.py
Labels: Skip Changelog

#1639 Update `hatchling` to `1.27.0`
  pyproject.toml
Labels: cla:yes, Skip Changelog

#1645 Port updates from `0.207.1`
  .changes/unreleased/Fixes-20250124-140300.yaml
  .changes/unreleased/Fixes-20250124-181618.yaml
  .changes/unreleased/Fixes-20250124-181706.yaml
  .github/actions/setup-python-env/action.yaml
  .github/workflows/cd-push-dbt-metricflow-to-pypi.yaml
  .github/workflows/cd-push-metricflow-to-pypi.yaml
  dbt-metricflow/dbt_metricflow/__about__.py
  dbt-metricflow/dbt_metricflow/cli/__init__.py
  dbt-metricflow/dbt_metricflow/cli/cli_configuration.py
  dbt-metricflow/dbt_metricflow/cli/main.py
  dbt-metricflow/dbt_metricflow/cli/mf_tutorial_project/dbt_project.yml
  dbt-metricflow/dbt_metricflow/cli/mf_tutorial_project/models/_models.yml
  dbt-metricflow/dbt_metricflow/cli/mf_tutorial_project/models/all_days.sql
  dbt-metricflow/dbt_metricflow/cli/mf_tutorial_project/profiles.yml
  dbt-metricflow/dbt_metricflow/cli/sample_dbt_models/semantic_manifest.json
  dbt-metricflow/dbt_metricflow/cli/tutorial.py
  dbt-metricflow/dbt_metricflow/cli/utils.py
  dbt-metricflow/extra-hatch-configuration/requirements-cli.txt
  dbt-metricflow/extra-hatch-configuration/requirements-dbt-bigquery.txt
  dbt-metricflow/extra-hatch-configuration/requirements-dbt-databricks.txt
  dbt-metricflow/extra-hatch-configuration/requirements-dbt-duckdb.txt
  dbt-metricflow/extra-hatch-configuration/requirements-dbt-postgres.txt
  dbt-metricflow/extra-hatch-configuration/requirements-dbt-redshift.txt
  dbt-metricflow/extra-hatch-configuration/requirements-dbt-snowflake.txt
  dbt-metricflow/extra-hatch-configuration/requirements-dbt-trino.txt
  dbt-metricflow/extra-hatch-configuration/requirements-metricflow.txt
  dbt-metricflow/pyproject.toml
  metricflow-semantics/pyproject.toml
  pyproject.toml
  tests_metricflow/cli/test_cli.py
  tests_metricflow/fixtures/cli_fixtures.py
Labels: cla:yes, Skip Changelog

#1646 Update package version definitions to `*.dev0`
  dbt-metricflow/dbt_metricflow/__about__.py
  metricflow-semantics/pyproject.toml
  metricflow/__about__.py
Labels: cla:yes, Skip Changelog

#1647 Use `__about__.py` to define `metricflow-semantics` package version
  metricflow-semantics/metricflow_semantics/__about__.py
  metricflow-semantics/pyproject.toml
Labels: cla:yes, Skip Changelog

#1649 Backport CI test updates for packaging to `dbt-metricflow/v0.8.1`
  .github/actions/run-mf-tests/action.yaml
  .github/actions/setup-python-env/action.yaml
  .github/workflows/cd-push-dbt-metricflow-to-pypi.yaml
  .github/workflows/cd-push-metricflow-to-pypi.yaml
  .github/workflows/cd-sql-engine-populate-persistent-source-schema.yaml
  .github/workflows/cd-sql-engine-tests.yaml
  .github/workflows/ci-linting.yaml
  .github/workflows/ci-metricflow-unit-tests.yaml
  .pre-commit-config.yaml
  Makefile
  scripts/__init__.py
  scripts/ci_tests/__init__.py
  scripts/ci_tests/install_hatch_environments.py
  scripts/ci_tests/metricflow_package_test.py
  scripts/ci_tests/metricflow_package_test.sh
  scripts/ci_tests/metricflow_semantics_package_test.py
  scripts/ci_tests/metricflow_semantics_package_test.sh
  scripts/ci_tests/run_package_build_tests.py
  scripts/mf_script_helper.py
Labels: cla:yes, Skip Changelog

#1650 Skip CLI setup in tests
  tests_metricflow/fixtures/cli_fixtures.py
Labels: cla:yes, Skip Changelog

#1652 Update tutorial flow to always create a sample project
  .changes/unreleased/Fixes-20250129-152608.yaml
  dbt-metricflow/dbt_metricflow/cli/main.py
  dbt-metricflow/dbt_metricflow/cli/tutorial.py
Labels: cla:yes

#1653 Add a CI test for the `dbt-metricflow` package
  .github/workflows/ci-metricflow-unit-tests.yaml
  scripts/ci_tests/dbt_metricflow_package_test.py
  scripts/ci_tests/run_package_build_tests.py
Labels: cla:yes, Skip Changelog

#1620 Support for custom offset window queried with only the window's custom grain
  metricflow-semantics/metricflow_semantics/dag/id_prefix.py
  metricflow-semantics/metricflow_semantics/model/semantics/semantic_model_lookup.py
  metricflow-semantics/metricflow_semantics/specs/measure_spec.py
  metricflow-semantics/metricflow_semantics/specs/metric_spec.py
  metricflow-semantics/tests_metricflow_semantics/model/test_semantic_model_container.py
  metricflow/dataflow/builder/dataflow_plan_builder.py
  metricflow/dataflow/dataflow_plan_visitor.py
  metricflow/dataflow/nodes/offset_base_grain_by_custom_grain.py
  metricflow/dataflow/nodes/offset_custom_granularity.py
  metricflow/dataflow/optimizer/predicate_pushdown_optimizer.py
  metricflow/dataflow/optimizer/source_scan/cm_branch_combiner.py
  metricflow/dataflow/optimizer/source_scan/source_scan_optimizer.py
  metricflow/dataset/sql_dataset.py
  metricflow/execution/dataflow_to_execution.py
  metricflow/plan_conversion/instance_converters.py
  metricflow/plan_conversion/to_sql_plan/dataflow_to_cte.py
  metricflow/plan_conversion/to_sql_plan/dataflow_to_subquery.py
  tests_metricflow/dataflow/optimizer/source_scan/test_source_scan_optimizer.py
  tests_metricflow/integration/query_output/test_offset_metrics.py
  tests_metricflow/plan_conversion/test_dataflow_to_sql_plan.py
  tests_metricflow/query_rendering/test_custom_granularity.py
  tests_metricflow/snapshots/test_custom_granularity.py/SqlPlan/BigQuery/test_custom_offset_window_with_only_window_grain__plan0.sql
  tests_metricflow/snapshots/test_custom_granularity.py/SqlPlan/BigQuery/test_custom_offset_window_with_only_window_grain__plan0_optimized.sql
  tests_metricflow/snapshots/test_custom_granularity.py/SqlPlan/BigQuery/test_join_to_time_spine_metric_grouped_by_custom_grain__plan0.sql
  tests_metricflow/snapshots/test_custom_granularity.py/SqlPlan/BigQuery/test_join_to_timespine_metric_with_custom_granularity_filter__plan0.sql
  tests_metricflow/snapshots/test_custom_granularity.py/SqlPlan/Databricks/test_custom_offset_window_with_only_window_grain__plan0.sql
  tests_metricflow/snapshots/test_custom_granularity.py/SqlPlan/Databricks/test_custom_offset_window_with_only_window_grain__plan0_optimized.sql
  tests_metricflow/snapshots/test_custom_granularity.py/SqlPlan/Databricks/test_join_to_time_spine_metric_grouped_by_custom_grain__plan0.sql
  tests_metricflow/snapshots/test_custom_granularity.py/SqlPlan/Databricks/test_join_to_timespine_metric_with_custom_granularity_filter__plan0.sql
  tests_metricflow/snapshots/test_custom_granularity.py/SqlPlan/DuckDB/test_custom_offset_window_with_only_window_grain__plan0.sql
  tests_metricflow/snapshots/test_custom_granularity.py/SqlPlan/DuckDB/test_custom_offset_window_with_only_window_grain__plan0_optimized.sql
  tests_metricflow/snapshots/test_custom_granularity.py/SqlPlan/DuckDB/test_join_to_time_spine_metric_grouped_by_custom_grain__plan0.sql
  tests_metricflow/snapshots/test_custom_granularity.py/SqlPlan/DuckDB/test_join_to_timespine_metric_with_custom_granularity_filter__plan0.sql
  tests_metricflow/snapshots/test_custom_granularity.py/SqlPlan/Postgres/test_custom_offset_window_with_only_window_grain__plan0.sql
  tests_metricflow/snapshots/test_custom_granularity.py/SqlPlan/Postgres/test_custom_offset_window_with_only_window_grain__plan0_optimized.sql
  tests_metricflow/snapshots/test_custom_granularity.py/SqlPlan/Postgres/test_join_to_time_spine_metric_grouped_by_custom_grain__plan0.sql
  tests_metricflow/snapshots/test_custom_granularity.py/SqlPlan/Postgres/test_join_to_timespine_metric_with_custom_granularity_filter__plan0.sql
  tests_metricflow/snapshots/test_custom_granularity.py/SqlPlan/Redshift/test_custom_offset_window_with_only_window_grain__plan0.sql
  tests_metricflow/snapshots/test_custom_granularity.py/SqlPlan/Redshift/test_custom_offset_window_with_only_window_grain__plan0_optimized.sql
  tests_metricflow/snapshots/test_custom_granularity.py/SqlPlan/Redshift/test_join_to_time_spine_metric_grouped_by_custom_grain__plan0.sql
  tests_metricflow/snapshots/test_custom_granularity.py/SqlPlan/Redshift/test_join_to_timespine_metric_with_custom_granularity_filter__plan0.sql
  tests_metricflow/snapshots/test_custom_granularity.py/SqlPlan/Snowflake/test_custom_offset_window_with_only_window_grain__plan0.sql
  tests_metricflow/snapshots/test_custom_granularity.py/SqlPlan/Snowflake/test_custom_offset_window_with_only_window_grain__plan0_optimized.sql
  tests_metricflow/snapshots/test_custom_granularity.py/SqlPlan/Snowflake/test_join_to_time_spine_metric_grouped_by_custom_grain__plan0.sql
  tests_metricflow/snapshots/test_custom_granularity.py/SqlPlan/Snowflake/test_join_to_timespine_metric_with_custom_granularity_filter__plan0.sql
  tests_metricflow/snapshots/test_custom_granularity.py/SqlPlan/Trino/test_custom_offset_window_with_only_window_grain__plan0.sql
  tests_metricflow/snapshots/test_custom_granularity.py/SqlPlan/Trino/test_custom_offset_window_with_only_window_grain__plan0_optimized.sql
  tests_metricflow/snapshots/test_custom_granularity.py/SqlPlan/Trino/test_join_to_time_spine_metric_grouped_by_custom_grain__plan0.sql
  tests_metricflow/snapshots/test_custom_granularity.py/SqlPlan/Trino/test_join_to_timespine_metric_with_custom_granularity_filter__plan0.sql
  tests_metricflow/snapshots/test_dataflow_to_sql_plan.py/SqlPlan/DuckDB/test_offset_custom_granularity_node__plan0.sql
  tests_metricflow/snapshots/test_dataflow_to_sql_plan.py/SqlPlan/DuckDB/test_offset_custom_granularity_node__plan0_optimized.sql
  tests_metricflow/snapshots/test_dataflow_to_sql_plan.py/SqlPlan/test_offset_custom_granularity_node__plan0.xml
  tests_metricflow/snapshots/test_offset_metrics.py/str/BigQuery/test_custom_offset_window_with_matching_custom_grain__query_output.txt
  tests_metricflow/snapshots/test_offset_metrics.py/str/Databricks/test_custom_offset_window_with_matching_custom_grain__query_output.txt
  tests_metricflow/snapshots/test_offset_metrics.py/str/DuckDB/test_custom_offset_window_with_matching_custom_grain__query_output.txt
  tests_metricflow/snapshots/test_offset_metrics.py/str/Postgres/test_custom_offset_window_with_matching_custom_grain__query_output.txt
  tests_metricflow/snapshots/test_offset_metrics.py/str/Redshift/test_custom_offset_window_with_matching_custom_grain__query_output.txt
  tests_metricflow/snapshots/test_offset_metrics.py/str/Snowflake/test_custom_offset_window_with_matching_custom_grain__query_output.txt
  tests_metricflow/snapshots/test_offset_metrics.py/str/Trino/test_custom_offset_window_with_matching_custom_grain__query_output.txt
Labels: cla:yes, Skip Changelog

#1656 Port updates from `dbt-metricflow/v0.8.1` to `main`
  .changes/unreleased/Fixes-20250129-152608.yaml
  dbt-metricflow/dbt_metricflow/cli/main.py
  dbt-metricflow/dbt_metricflow/cli/tutorial.py
  tests_metricflow/fixtures/cli_fixtures.py
Labels: cla:yes, Skip Changelog
